### ISSUE TITLE
Revisit isEmpty methods

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#10]
Currently generating isEmpty methods, but they might actually not be needed.  It doesn't seem like the other languages need them, and if folks build their protos into modules/frameworks, they might not deadstrip, bloating things up.  So if they aren't really needed (maybe for the current isEqualTo (and that might not be fully correct)), dropping them is likely the correct call.

**Comment by jcanizales** [comment]
\<Standard reminder that adding stuff later if there's demand is always possible, but removing isn't.\>

**Comment by tbkka** [comment]
I think the generated `isEmpty` is only still being used in one case:  the equality test on messages uses it to ensure that a message with no allocated storage class is considered equal to one where the storage class is allocated but "empty."

An alternative approach would be to always allocate the backing storage object.  Then this case never arises.  Empty objects (allocated but with no fields set) should be uncommon, so I don't see a big drawback.  It would also simplify the `uniqueStorage()` implementation.
