### ISSUE TITLE
XCFramework build configuration/option?

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#1000]
Although the SwiftProtobuf project does not distribute any form of binary, it might help others if we provided the necessary configuration for building binary "xcframework" bundled libraries.

**Comment by thomasvl** [comment]
Does it make sense for SwiftPM to support this in some way?  Or Xcode via a Package.swift?  i.e. - seems like something most package would need a way to do, so hopefully it isn't something each one has to do.

**Comment by tbkka** [comment]
I was recently asked about this, so figured I'd record it for discussion.  Personally, I would also prefer for SwiftPM to handle it for us.

**Comment by bok-** [comment]
I was hoping we’d hear something at WWDC but unfortunately not. So here’s something to bridge the gap that you can use locally or generate automatically with a GitHub Action: https://github.com/unsignedapps/swift-create-xcframework

**Comment by thomasvl** [comment]
Closing this out since we'd dropped the local Xcode project in favor of SwiftPM and CocoaPods integration. Hopefully one of them would provide something vs. having to recreate a manually maintained Xcode project.
