### ISSUE TITLE
Consider support for `Google_Protobuf_Date` for birthdays? (and other timezone-free dates)

### ISSUE THREAD

**Issue by benguild** [apple/swift-protobuf#1010]
This is just a suggestion/proposal that for a representation of an entire 24 hour period in the local timezone (holiday, birthday, etc.) this may be worth including.

**Comment by thomasvl** [comment]
Library support the WellKnownTypes from the main https://github.com/protocolbuffers/protobuf repo.  If it becomes standardized there, we'll pick it up.

**Comment by thomasvl** [comment]
ps - if you are just looking to use something from https://github.com/googleapis/googleapis, using those should work, they just aren't something bundle with the this library because they aren't a core part the protobuf.
