### ISSUE TITLE
(macOS Mojave) Minimal example does not run in Release mode.

### ISSUE THREAD

**Issue by Reiszecke** [apple/swift-protobuf#1013]
It took me 40 hours of backtracing to pin down the issue to this repo (I expected the error to be caused somewhere on my end).

Using swift-protobuf in Release configuration causes `Thread 1: EXC_BAD_ACCESS (code=1, ...`. I am a bit surprised I could not find an open ticket listed here but maybe I'm just using it wrong.

Minimal example:

### PROTOBUF

minimal.proto
```
syntax = "proto2";
package proto;

message Text {
    optional int32 number = 1;
}
```

`pb.swift` code generated using `protoc --swift_out=. minimal.proto` (resulting 75-line Swift file not included in the post)

### XCODE PROJECT

Dependencies:
![image](https://user-images.githubusercontent.com/11237541/85574076-bdfa2d00-b636-11ea-9b63-25845b31ff21.png)

ViewController.swift:
```
override func viewDidLoad() {
        super.viewDidLoad()

        var text = Proto_Text()
        text.number = 3

        print(text) //crashes with Thread 1: EXC_BAD_ACCESS (code=1, address=0x176d51e8e)
```

The object itself appears to be stable, I can see it being listed in the debugger.
![image](https://user-images.githubusercontent.com/11237541/85574537-2943ff00-b637-11ea-873b-fba55e1d453e.png)

It's only when I'm trying to access it. Again, **this only happens in release configuration**

![image](https://user-images.githubusercontent.com/11237541/85574785-5c868e00-b637-11ea-8db7-e0f0bf972989.png)

Now let's try the other way around:

```
        let data64 = "CAM="
        let data = Data(base64Encoded: data64)!
        let text = try! Proto_Text(serializedData: data)
        
        print(text)
```

Works as expected in Debug configuration and prints
```
            ProtoBufTest.Proto_Text:
            number: 3
```

However, in Release configuration it again results in

```Thread 1: EXC_BAD_ACCESS (code=1, address=0x17966ddde)```

What am I doing wrong?

* iOS Simulator 13.2.2

* Xcode Version 11.2.1 (11B53)

* macOS Mojave 10.14.5 (18F132)

* Swift 4.2 as well as Swift 5

* swift-protobuf tag 1.7.0 as well as 1.9.0

Thank you!

I am not sure if that is a proper trace:

```
#0	0x00007fff5132eb9c in swift_getAssociatedConformanceWitnessSlow ()
#1	0x00007fff5132e680 in swift_getWitnessTable ()
#2	0x000000010ac831e3 in lazy protocol witness table accessor for type Proto_Text and conformance Proto_Text [inlined] ()
#3	0x000000010ac831c4 in protocol witness for CustomDebugStringConvertible.debugDescription.getter in conformance Proto_Text ()
#4	0x00007fff512c9c55 in specialized _print<A>(_:separator:terminator:to:) ()
#5	0x00007fff5118e4ff in print(_:separator:terminator:) ()
#6	0x000000010ac820c8 in ViewController.viewDidLoad() at /Users/RZ/Library/Autosave Information/ProtoBufTest/ProtoBufTest/ViewController.swift:21
```
With line 21 being `print(text)`

And

```
#0	0x00007fff5132eb9c in swift_getAssociatedConformanceWitnessSlow ()
#1	0x00007fff5132e680 in swift_getWitnessTable ()
#2	0x00000001031cd84a in lazy protocol witness table accessor for type Proto_Text and conformance Proto_Text [inlined] ()
#3	0x00000001031cd82b in specialized closure #1 in Message.merge<A>(contiguousBytes:extensions:partial:options:) [inlined] ()
#4	0x00000001031cd82b in thunk for @callee_guaranteed (@unowned UnsafeRawBufferPointer) -> (@error @owned Error) [inlined] ()
#5	0x00000001031cd82b in specialized closure #1 in Data.InlineData.withUnsafeBytes<A>(_:) [inlined] ()
#6	0x00000001031cd826 in specialized withUnsafeBytes<A, B>(of:_:) [inlined] ()
#7	0x00000001031cd826 in specialized Data.InlineData.withUnsafeBytes<A>(_:) [inlined] ()
#8	0x00000001031cd823 in specialized Data._Representation.withUnsafeBytes<A>(_:) [inlined] ()
#9	0x00000001031cd764 in specialized Data.withUnsafeBytes<A>(_:) [inlined] ()
#10	0x00000001031cd6b8 in specialized protocol witness for ContiguousBytes.withUnsafeBytes<A>(_:) in conformance Data [inlined] ()
#11	0x00000001031cd6b8 in specialized Message.merge<A>(contiguousBytes:extensions:partial:options:) ()
#12	0x00000001031cd132 in specialized Message.init(serializedData:extensions:partial:options:) [inlined] ()
#13	0x00000001031cd0f6 in ViewController.viewDidLoad() at /Users/RZ/Library/Autosave Information/ProtoBufTest/ProtoBufTest/ViewController.swift:31
```
With line 31 being `let text = try! Proto_Text(serializedData: data)`

**Comment by tbkka** [comment]
Thank you for reporting this!  Do you have a backtrace from the crash?  That would help a lot to better understand what's going wrong here.

**Comment by tbkka** [comment]
You should also definitely try upgrading Xcode.

**Comment by thomasvl** [comment]
Since the testing snippet seems pretty small, you might want to try isolating it from an iOS build and try just making an macOS command line binary with it so you can try using Xcode with the Package vs. making a SwiftPM package for your test binary to see if the failure is happening there also.  i.e. - is this general, or does it only happen with SwiftPM Xcode integration.

Failing that, if you can attach your sample or include the crash log, it might help provide us some other hints about what is happening.

Also, what macOS version are you running on?

**Comment by Reiszecke** [comment]
Thank you tbkka for the hints with the Xcode version and thank you thomas for the "isolating" instructions.

Following tbkka's advice I have now tried to run it on a macOS 10.15.4 (Catalina) machine running Xcode 11.4.1 with a 13.4.1 Simulator and it's working fine. 

I am still on Mojave on my main computer which is why I've stopped receiving Xcode updates. I am now downloading 11.3.1 (the last available Xcode version for Mojave) and try if that is enough to iron out this issue. 

I will keep you updated.

**Comment by thomasvl** [comment]
What version of Mojave are you on?  Are you fully up to date?  I think it was 10.14.4 that Apple changed around handing the the runtime (shipping it with the OS), so if you're in an odd state where the Xcode tooling expects it to be handled differently from what your OS version does, it could lead to odd crashes.

**Comment by Reiszecke** [comment]
The minimal example now works without issues in both ways. I haven't ran all tests yet but I don't wanna rob your of your sleep especially since another issue regarding that came up just a few hours ago. I am pretty sure everything is working for me now. Thank you for your availability.

### Working configuration for macOS Mojave 10.14.5 (18F132)

```
Xcode 			Version 11.3.1 (11C505)
iOS Simulator 	Version 13.3
Swift 			Version 5
SwiftProtobuf 	Version 1.9.0
```

**Comment by Reiszecke** [comment]
It appears to be working perfectly. Thank you two!

I have to admit, not updating to the latest version of Xcode is kinda dumb but given that 11.2.1 isn't even 9 months old maybe you want to address this somewhere in the readme. Or maybe the 3 people who will encounter this issue in the next 5 years will find this thread, who knows :p
