### ISSUE TITLE
Requesting XCode 12, iOS 14 Support 

### ISSUE THREAD

**Issue by nbhasin2** [apple/swift-protobuf#1016]
With the release of new iOS 14 (XCode 12 Beta) the current stable version 1.9.0 doesn't compile with carthage command. 

**v1.9.0 Commit:** 7f36441e3372665b1b414f8ac93b5905cc42a405
**Carthage Command:** carthage build --no-skip-current --platform ios

```
  var readBuffer = UnsafeMutablePointer<UInt8>.allocate(capacity: 1)
  ~~~ ^
  let

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(4 failures)
```

However the **master** branch compiles perfectly with above carthage command. 

Wondering what the timelines are for next release?

**Comment by thomasvl** [comment]
I'll look at cutting a release later this week/early next week.

**Comment by nbhasin2** [comment]
Thanks @thomasvl :) Will keep an eye out for new release.

**Comment by thomasvl** [comment]
1.10.0 released
