### ISSUE TITLE
Add API validation script to CI

### ISSUE THREAD

**Issue by Lukasa** [apple/swift-protobuf#1026]
SwiftNIO uses [a script](https://github.com/apple/swift-nio/blob/master/scripts/check_no_api_breakages.sh) built on top of the Swift API digester command line tool to validate that PRs do not cause semver major breaking changes. This script could be adapted for the use cases of protobuf as well, and help avoid ambiguity around whether a change is breaking or not.

Note that, while this script is helpful, it does encounter some false positives. In particular it tends to believe that adding a protocol customisation point with a default implementation is a semver major, when so far as we can tell it is not (it's ABI breaking, I think, but not a semver major).

**Comment by thomasvl** [comment]
Happened to find https://github.com/ltetzlaff/swift-api-diff today.  Don't suppose SwiftNIO is looking at make a standard github action out of this?

**Comment by thomasvl** [comment]
The script also needs `jq` installed, which isn't on macOS be default.

**Comment by Lukasa** [comment]
If the community has already done a standard GitHub action I'm more than happy to defer to that!

**Comment by thomasvl** [comment]
Since it seems to have a copy of the script, i wasn't sure how insync it is staying, etc.  Is there any coordination with them?

**Comment by thomasvl** [comment]
It also looks like it posts back to the comments, which means it needs a github token.  That likely means someone on Apple's side would need to sign off on it before we could use it here.

@tbkka I'm guessing the need for a secret to post back means it shouldn't be used here?

**Comment by thomasvl** [comment]
Also looks like despite the script having `xcrun` support, the Xcode toolchains don't include `swift-api-digester`, so it also requires a custom toolchain install for macOS.

**Comment by tbkka** [comment]
@thomasvl -- Yeah, we should avoid anything that needs a secret to post back.

**Comment by thomasvl** [comment]
@Lukasa should I open a nio issue asking for a standard action that doesn't require write access?

**Comment by Lukasa** [comment]
@thomasvl Sure, worst-case we can say we think it's out of scope. But I think an action is a nice approach.

**Comment by thomasvl** [comment]
Opened https://github.com/apple/swift-nio/issues/1600
