### ISSUE TITLE
Carthage build fails on Xcode 12 beta 4

### ISSUE THREAD

**Issue by plamenterziev** [apple/swift-protobuf#1038]
Running `carthage build` fails when starting `lipo`:

`/usr/bin/xcrun lipo -create /Users/plamen/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/swift-protobuf/1.11.0/Build/Intermediates.noindex/ArchiveIntermediates/SwiftProtobuf_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SwiftProtobuf.framework/SwiftProtobuf /Users/plamen/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/swift-protobuf/1.11.0/Build/Products/Release-iphonesimulator/SwiftProtobuf.framework/SwiftProtobuf -output /Users/plamen/Project/Carthage/Build/iOS/SwiftProtobuf.framework/SwiftProtobuf
`

The error is:

`
fatal error: /Users/plamen/Downloads/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/plamen/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/swift-protobuf/1.11.0/Build/Intermediates.noindex/ArchiveIntermediates/SwiftProtobuf_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/SwiftProtobuf.framework/SwiftProtobuf and /Users/plamen/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/swift-protobuf/1.11.0/Build/Products/Release-iphonesimulator/SwiftProtobuf.framework/SwiftProtobuf have the same architectures (arm64) and can't be in the same fat output file
` 

Seems the architecture of the simulator is arm64 somehow.

Should be related with https://github.com/Carthage/Carthage/issues/3019 but the workaround there is not working.

**Comment by thomasvl** [comment]
You're likely going to have to try carthage support areas since I don't think any of use here have much experience with it.  I'm guessing you are trying to lipo together an Apple Silicon build of along with at iPhone build, and thus getting two arm64 slices.  I don't think there is any way to do that since you can't have an architecture listed twice.  To make a _fat_ library that supports all those architectures, it will take using XCFrameworks instead of a single lipo binary; which is likely going to take changes on Carthage itself.

**Comment by plamenterziev** [comment]
Yes, this is a Carthage issue but just wanted to bring to your attention. I am not using Apple Silicon and all other frameworks in my projects build successfully - only SwiftProtobuf fails with the above error.

**Comment by 1oo7** [comment]
It's a Carthage-specific issue. There is a workaround posted on Carthage's forums to fix it. 

Of course, we'd prefer to use Swift Package Manager than Carthage, however SPM lacks two key features:

- ability to keep the build cache for all packages _outside of derived data_
- ability to cache build artifacts on a per-Xcode-version basis

**Comment by thomasvl** [comment]
Closing this since it sounds like there isn't something for us to do about this.
