### ISSUE TITLE
JSON serialization doesn't handle UInt64 correctly

### ISSUE THREAD

**Issue by soffes** [apple/swift-protobuf#106]
I'm seeing these be encoded as strings instead of ints in the serialized JSON

**Comment by thomasvl** [comment]
This is to spec for Protocol Buffers JSON serialization - https://developers.google.com/protocol-buffers/docs/proto3#json

Some languages/platforms don't deal with 64bit ints, so strings are used to ensure they came make it to all platforms.

**Comment by soffes** [comment]
Oh my bad. Thanks for the clarification!
