### ISSUE TITLE
Xcode12 build failure

### ISSUE THREAD

**Issue by iOSDevFin** [apple/swift-protobuf#1060]
We see some build errors on current Xcode beta 5. See screenshot attached. Any advice?

![Screenshot 2020-08-25 at 12 27 44](https://user-images.githubusercontent.com/5556361/91163831-79d6e780-e6ce-11ea-85bb-2e40bce708eb.png)

**Comment by thomasvl** [comment]
This appears to be for a different project, we don't have any sources named `CodedInputStream.swift` or `RingBuffer.swift`.

**Comment by thatsmerahul1** [comment]
Even I am facing the same issue in swift-protobuf while compiling in XCode 12.4 whereas it is working fine in 11.2
<img width="1267" alt="Screenshot 2021-05-03 at 1 19 45 AM" src="https://user-images.githubusercontent.com/16455638/116825754-33ffe680-abae-11eb-9956-35324aaa73d3.png">
<img width="1270" alt="Screenshot 2021-05-03 at 1 09 02 AM" src="https://user-images.githubusercontent.com/16455638/116825749-2f3b3280-abae-11eb-8240-3b32ec114007.png">

**Comment by thatsmerahul1** [comment]
> We see some build errors on current Xcode beta 5. See screenshot attached. Any advice?
> 
> ![Screenshot 2020-08-25 at 12 27 44](https://user-images.githubusercontent.com/5556361/91163831-79d6e780-e6ce-11ea-85bb-2e40bce708eb.png)

Did you find any solution to your problem?

**Comment by tbkka** [comment]
I suspect you are using https://github.com/alexeyxo/protobuf-swift  which is an entirely independent and unrelated project.

**Comment by thatsmerahul1** [comment]
> I suspect you are using https://github.com/alexeyxo/protobuf-swift which is an entirely independent and unrelated project.

Then I'll go for migration to your current library because I am new to my current project and I am not sure how tough it will be to migrate to your Swift-protobuf.
