### ISSUE TITLE
Clarify status of optimize_for

### ISSUE THREAD

**Issue by k0nserv** [apple/swift-protobuf#1065]
Hey 👋

I deleted the template because this isn't a bug report perse. I am trying to understand the status of the `optimize_for` option, it seems to not be mentioned in the source code and applying `optimize_for CODE_SIZE` causes no changes in the generate Swift code. 

Is my understanding that this isn't support correct and if so can that be clarified in the `README.md`?

**Comment by tbkka** [comment]
You are right that SwiftProtobuf currently does not recognize the `optimize_for` option.

The C++ protobuf community has had some problems with that option that has caused them to generally discourage its use.  For this reason, we're not likely to support it any time soon.

We have, however, considered splitting the generated code into multiple independent source files.  This would allow some of those files to be omitted by people who did not need those features.  Specifically, the textual field names used by JSON and TextFormat support might be segregated this way, which would allow you to reduce the code size somewhat by dropping support for those formats.

**Comment by k0nserv** [comment]
Alright thanks. I'll close the issue then given that I have an answer to my question.
