### ISSUE TITLE
Should we drop the leading_detached_comments

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#108]
Java, C#, and ObjC are the languages in the google/protobuf sources that pull over comments, but they only pull over the `leading_comments` and `trailing_comments`.  They all ignore the `leading_detached_comments`.

There is some value in the `leading_detached_comments`, but the catch is the proto file structure doesn't come through.  Detached comments are bound to the item that they appeared before; but proto files don't have a defined order, they mix enums/messages/extensions in the content of the file however the file's author chose.  About the only thing we know is they made some sense at the point they appeared in the proto file, but they could apply to the thing right after them or they could apply to everything after them.  But the generator sees a `FileDescriptor` where all the enums/messages/extensions have grouped into repeated fields, and the file order is lost.

Given a file like:

``` protobuf

// Foo and Bar are for…

message Foo { }

enum Bar {}

// Baz and Mumble are for…

message Baz {}

enum Mumble {}

message Blah {}
```

Common convention is to generate the Enums first, the source would end up like:

``` c++
enum Bar {}
enum Mumble {}

// Foo and Bar are for…

class Foo {}

// Baz and Mumble are for…

class Baz {}
class Blah {}
```

After the reordering, the comments don't make as much sense.

It is likely also worth mentioning that some languages don't bring the comments over at all.  Even for developers that work in the languages that support pulling over comments, I've seen several not realize this happens; so the proto file comments (even when attached to things) aren't that useful.

So we need to decide if we think it is worth bringing the leading comments over or not.

**Comment by tbkka** [comment]
If I remember correctly, the motivation for this was to preserve the copyright messages at the beginning of the file.

In particular, the Swift Protobuf runtime library directly includes Swift sources generated from Google-copyrighted protos.  Those protos include a copyright message that requires the copyright message itself to be preserved.  In the generated descriptor we get from protoc, that copyright message becomes a "leading detached comment" attached to the first syntactic element in the descriptor.   Unfortunately, there's no guarantee that the first syntactic element is a `syntax` element (legacy proto2 files lack this), so I opted to preserve leading detached comments everywhere.

We could do this in other ways, of course.  For example, the detached comments could be rendered with ```//``` instead of ```///``` which would leave them out of the docstring.

**Comment by thomasvl** [comment]
Detached comments already are left out of the docstring (they are `//`).

As far as picking up the copyrights, see some of what I added in #110. What happens to pull them out for the google/protobuf bundled proto won't always work, so if Apple wants to ensure the copyright comes over for those protos, we likely need to come up with something explicit instead of something that happens to work and might not do the same thing for other proto files.

In either case, I'd suggest we spin the copyright question out into a separate issue to leave this focused on the detached comments for all the other cases.

**Comment by tbkka** [comment]
Splitting out the copyright question sounds like a good idea, as long as we don't rip it out prematurely.  Preserving detached comments should result in preserving _all_ comments, which should preserve any copyright message.

I agree that the best answer for the copyright question would be for the protoc developers to introduce an explicit mechanism to pass copyright blocks in the descriptor.  (Which would presumably include some kind of marker in the proto file as well as a new field in FileDescriptorProto.)

**Comment by tbkka** [comment]
I'll also point out that comment preservation should not impact the API so is something that could be deferred until post-1.0.

**Comment by thomasvl** [comment]
Ignoring copyrights, and sticking to the issue here…

You mentioned "preserving _all_ comments", that's going to be just about impossible.  The hack to get the copyright is pulling the comments off the syntax line at the moment.  There could be comments on any file or field option.  There could be comments before the proto package. Before any/all imports.  There can be detached comments after the last type.  Even if protoc collects them all into the `FileDescriptor`, it isn't clear where they all would belong in the generated code.

For the language generators that do try to bring over comments, they only bring the attached comments for the messages/enums/extensions.  My understand (and my intent when I did it for ObjC), was this was help allow those directly attached comments show up in editors during code completion/etc.  With they current handling we have, they are just `//` comments, so they won't show up in any docs.  They appear to be be brought over to provide context in the file, but since the file is reordered, that context was what seemed debatable.

**Comment by thomasvl** [comment]
Oh, re post 1.0.  Yup, I was looking at #35 and looking at how some of our our proto files generated. That's where I saw some things that seemed strange in the comments, and got me looking at what and how things were coming over (especially compared to how the presented in ObjC).

**Comment by tbkka** [comment]
> They appear to be be brought over to provide context in the file,...

To be clear, my _only_ reason for preserving `leading_detached_comments` was to try to carry over copyright messages from the beginning of the file.

After talking with a lawyer about this, I now believe the code you updated in #110 (which preserves the `leading_detached_comments` from the `syntax` declaration) suffices for this, so I'm happy to drop `leading_detached_comments` from elsewhere if you think that's appropriate.

**Comment by thomasvl** [comment]
Ok, so keep the hack for the syntax ones (even though it doesn't always work), but drop them from other places?

**Comment by tbkka** [comment]
Yep, that's my proposal:  Keep the `leading_detached_comments` from the `syntax` declaration until the protoc folks can give us something better, and remove the rest.
