### ISSUE TITLE
CI: GitHub actions seems to have been paused?

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#1081]
Looking at https://github.com/apple/swift-protobuf/actions, it looks like the scheduled weekly tasks haven't run in 12 days.  And #1080 since showing any checks as being run.

Did the repos configuration get changed to have the support disabled?

**Comment by allevato** [comment]
Random guess, but that's around the time that many of the Swift repos switched from the `master` to `main` branch, which this one hasn't yet. Did something in the workflows get disabled for the `master` branch anyway?

**Comment by thomasvl** [comment]
Hm, the configs still say `master` (https://github.com/apple/swift-protobuf/tree/master/.github/workflows), but I've never really configured the support on github before (and don't have access on this repo), so I can't check if there is some other controls there around which branches can run actions.

**Comment by thomasvl** [comment]
#1085 should have been spotted if the CI was running.  ☹️

**Comment by tbkka** [comment]
I've asked around but no one seems to have any ideas what changed.  I'll poke some more.

**Comment by thomasvl** [comment]
I think I got an email from github on one of my person repos because the actions hadn't be triggered in N days they were disabled, any chance you all got something like that as owners of this repo?

**Comment by tbkka** [comment]
I've filed a request with GitHub support to look into this.

**Comment by tbkka** [comment]
I think we've managed to re-enable the actions for this repository.

**Comment by thomasvl** [comment]
Looks like things aren't fully back yet. Created #1091, which [shows zero check results](https://github.com/apple/swift-protobuf/pull/1091/checks), but if you [click on the one listed](https://github.com/apple/swift-protobuf/actions/runs/370660453), it shows a _Check failure_:

> _actions/checkout@v2, actions/cache@v1, and actions/checkout@v2 are not allowed to be used in apple/swift-protobuf. Actions in this workflow must be: within a repository owned by apple._

**Comment by tbkka** [comment]
Thanks for testing!  Please try one more time.

(Background:  There's a new control panel for setting this and we're trying to figure out which setting actually best matches the previous ad hoc setup.)

**Comment by thomasvl** [comment]
Looks like things started (and my recent commits don't work under Swift 4.2).

We likely want to keep this open until we confirm the scheduled tasks also run early next week.

**Comment by thomasvl** [comment]
Is there a new setting about emailing the check results?  I seem to be getting emails for the tests that I didn't used to get.

**Comment by thomasvl** [comment]
Closing as the scheduled actions also seem to have run the last few weeks.
