### ISSUE TITLE
Name collision in one_of

### ISSUE THREAD

**Issue by mpdifran** [apple/swift-protobuf#1084]
Please be sure to include:

* what OS you are developing on (Linux or macOS, including the version)
macOS 10.15.7

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
  for Linux, what version of Swift (`swift --version`)
Xcode 12.1
Build version 12A7403
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin19.6.0

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
Swift 5

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
1.13

```
message Item {
    oneof new_value {
      string first = 1;
      bool second = 2;
    }
}
```

When compiling, SwiftProtobuf generates the following code (Converting from my project's specific code):

```
public struct Item {
    public var newValue: Item.OneOf_NewValue? = nil

    public var first: String {
      get {
        if case .first(let v)? = newValue {return v}
        return String()
      }
      set {newValue = .first(newValue)} // Error: Cannot assign to value: 'newValue' is immutable
    }

    public var second: Bool {
      get {
        if case .second(let v)? = newValue {return v}
        return false
      }
      set {newValue = .second(newValue)}
    }
    ...
}
```

The problem is the generated property name for the `one_of` is the same as Swift's synthesized `newValue` property inside `set { ... }`. Switching the generated code to the following line fixes it:

```
      set {self.newValue = .first(newValue)}
```

**Comment by thomasvl** [comment]
Note to self - double check the non `oneof` fields also, since with Storage we relay things there.

**Comment by mpdifran** [comment]
Do you have an idea of when you can release this fix? 

We're currently fixing the compile issues in our code by hand. We're looking to automate our proto compilation, and this is the last thing preventing us from doing so!

**Comment by thomasvl** [comment]
Ha, I was just looking a few hours ago to see if we were due for a release.  I'll look at doing one tomorrow.

**Comment by mpdifran** [comment]
Great timing, thanks!

**Comment by mpdifran** [comment]
Thanks for the quick response! 

Is there a forthcoming homebrew release for the protoc plugin, or do you recommend I just build from source?

**Comment by thomasvl** [comment]
homebrew for SwiftProtobuf?  Didn't know there was such a thing, so not sure who has been doing that, it hasn't been us.

**Comment by mpdifran** [comment]
Ah it's in the README, I'm guessing it should be removed?

```
Alternatively install via Homebrew

If you prefer using Homebrew:

$ brew install swift-protobuf

This will install protoc compiler and Swift code generator plugin.
```
