### ISSUE TITLE
Some new upstream conformance tests are failing

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#1085]
```
Recommended.Proto3.TextFormatInput.StringLiteralLongUnicodeEscapesBytes.ProtobufOutput
Recommended.Proto3.TextFormatInput.StringLiteralLongUnicodeEscapesBytes.TextFormatOutput
Recommended.Proto3.TextFormatInput.StringLiteralLongUnicodeEscapesString.ProtobufOutput
Recommended.Proto3.TextFormatInput.StringLiteralLongUnicodeEscapesString.TextFormatOutput
Recommended.Proto3.TextFormatInput.StringLiteralShortUnicodeEscapeBytes.ProtobufOutput
Recommended.Proto3.TextFormatInput.StringLiteralShortUnicodeEscapeBytes.TextFormatOutput
Recommended.Proto3.TextFormatInput.StringLiteralShortUnicodeEscapeString.ProtobufOutput
Recommended.Proto3.TextFormatInput.StringLiteralShortUnicodeEscapeString.TextFormatOutput
Required.Proto3.TextFormatInput.StringLiteralIncludesLFBytes
Required.Proto3.TextFormatInput.StringLiteralIncludesLFString
```

**Comment by thomasvl** [comment]
#1086 adds the know failure entries.

**Comment by thomasvl** [comment]
@tbkka So I did a quick port of the JSON handling, and found something interesting:

https://github.com/protocolbuffers/protobuf/blob/fdc35840b95f56c3aef44a3fc6ae5991f21620a5/conformance/text_format_conformance_suite.cc#L293-L296

This explicitly tests that `\uXXXX\uYYYY` encoded surrogate pairs do not work.  But the code you put in for JSON directly allow this, was there a reason for that?

**Comment by tbkka** [comment]
Hmmm....  I guess I've had too much experience with botched unicode encoders that would encode UTF-16 to UTF-8 naively by separately encoding each surrogate.  But if the Powers That Be say this should be rejected, then we should reject it.

**Comment by thomasvl** [comment]
They also have these _long_ runs:

https://github.com/protocolbuffers/protobuf/blob/fdc35840b95f56c3aef44a3fc6ae5991f21620a5/conformance/text_format_conformance_suite.cc#L280-L282

I'm checking to see if I can found out anything more on this part, since there doesn't seem to be a JSON test with those.

**Comment by thomasvl** [comment]
Gathering some more breadcrumbs from the C++ code, will update again when I talk to folks for some answers:

`\uXXXX` == 4 bytes, `\UXXXXXXXX` == 8 bytes:

https://github.com/protocolbuffers/protobuf/blob/214c77e1b76e63e512bd675d1c300c80438642b6/src/google/protobuf/io/tokenizer.cc#L999-L1003

There is some support for surrogate decoding in the C++:

https://github.com/protocolbuffers/protobuf/blob/214c77e1b76e63e512bd675d1c300c80438642b6/src/google/protobuf/io/tokenizer.cc#L1005-L1032

But I don't see failures for the C++…

**Comment by thomasvl** [comment]
Anyway, looks like you matched some of the C++ code, but now there is a test saying that's wrong.  We'll see what I hear back.

**Comment by thomasvl** [comment]
Opened #1089 to track the potential issues in our JSON handling, we appear to match C++ and there isn't a conformance test around these specific cases.
