### ISSUE TITLE
Look at moving message metadata into a struct

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#109]
Spun out of https://github.com/apple/swift-protobuf/issues/104.

If we move the metadata for message into a struct then it helps namespace it away from the message's field names.

i.e. - 

``` swift
struct Foo: ProtobufMessage {
   struct Metadata: ProtobufMessageMetadata {
      static let protoPackageName = "bar.baz";
      static let jsonFieldNames: [String: ProtoFieldNumbers] = [ ... ];
   }
}
```

**Comment by allevato** [comment]
This looks like something we should do.

But, we'll need to exercise some extra care here if we want to move toward having the JSON and text names in separate extensions in separate files. For example, under the current design, I imagined having `jsonFieldNames` be a property in, say, a `ProtobufJSONSerializable` protocol that would be added to `Foo` via an extension. Redesigning this means we'd have to extend `Metadata` instead, and it might end up with us having two protocols: one for the message itself (which would provide the various JSON initializers and serializers), and one for the metadata struct (which would provide the field names).

This would also affect generic constraints that we might need to use when implementing the JSON/text serializers—we'd get into some situations where we might have to say `<M: ProtobufMessage where M: ProtobufJSONSerializable, M.Metadata == ProtobufMetadataJSONSerializable>`.

None of this stuff is blocking (at least not that I can tell, without diving into the actual implementation); I just want to leave my thoughts here for posterity so we know what we might be facing.

**Comment by tbkka** [comment]
Added "generator API" label since this would change the API between the generated code and the library.

**Comment by thomasvl** [comment]
If we can't do the struct, does some prefix on all the properties make sense?  Would help get them out of the message/enum namespace.

**Comment by tbkka** [comment]
I think we get some real benefits even if the JSON/Proto names aren't in the metadata object.  I suggest starting by moving other metadata (message name, proto namespace, typeURL, Swift class name, etc) into a separate object first (similar to what we did with the FieldNameMap).

**Comment by thomasvl** [comment]
Most of the methods for metadata exist to be provided by the generator and/or allow developers to replace them.  If they exist for the generated code only, then we could move them all into something like `protobuf_Metadata` readonly var that returns a named tuple.  But if the intent is for a developer to be able to provide an override via an `extension` on the `struct`, then nesting it within a struct would seem to mean we need a custom `struct` for each `Message`, and some way to get an instance of that thing created.

Looking at `protocol Message` –
```swift
  var protoMessageName: String { get }
  var protoPackageName: String { get }
  var anyTypePrefix: String { get }
  var anyTypeURL: String { get }
```
- `protoMessageName` and `protoPackageName` don't really seem like they should be swappable by a developer, so a tuple there might work?
- `anyTypePrefix` and `anyTypeURL` pick up defaults in `public extension Message`, so they seem like they are meant to be hooked.  The other languages don't expose these on message, and instead use defaults on the apis around encoding/decoding `Any`.  I haven't looked at our apis there, would that work?

Would it work to make any of these static functions instead?  Can we call them (`type(of: self).anyTypePrefix()`)?  If that did work, it would get them out of the field namespace of the message.

I didn't see any other real metadata that could be an issue on the other _Message_ protocols or on `Enum` or `OneofEnum`, did I miss anything?

**Comment by allevato** [comment]
As far as I can tell, all of those should be static. I did some cleanup of other non-static things in those protocols but never got around to those specifically.

I was trying to think if there were any places where making them static would mess up polymorphism through the `Message` protocol, but `type(of:)` returns the dynamic type of a value so even if the static type of a particular variable is the protocol `Message`, you'll still get the right thing writing `type(of: x).staticMember`.

Static vars should be fine—I don't see a reason to make them functions.

**Comment by thomasvl** [comment]
I'll make a run at that.

**Comment by tbkka** [comment]
At this point, the only metadata left are:
  * Proto package and message name.
  * Text field names
As discussed above, we want the text field names to be on the message struct proper (to simplify breaking them out into an extension later), so that leaves just two simple string fields, which is probably not worth introducing all the extra type machinery.

So I vote we close this.

We could also consider #367, which renames those properties to `_protobuf_` to reduce collisions (which was the original motivation for moving metadata into a separate struct).  Let me know what you think of that.

**Comment by tbkka** [comment]
Closing this.
