### ISSUE TITLE
proto3 optional fields support

### ISSUE THREAD

**Issue by igolaizola** [apple/swift-protobuf#1096]
I am planning to start using proto3 optional labels. This is an experimental feature available using `--experimental_allow_proto3_optional` on protoc invocations: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#protoc-invocation

Before changing all my protos I would like to know if this feature is already supported for swift. I have looked around in the repo but haven't been able to find if it is done or not.

Thank you!

**Comment by thomasvl** [comment]
https://github.com/apple/swift-protobuf/releases/tag/1.9.0

> Support for new Proto3 `optional` (this needs a `protoc` from protocolbuffers/protobuf v3.12.0 (or later)) #978
