### ISSUE TITLE
Google_Protobuf_Compiler_CodeGeneratorRequest(serializedData:data) is not parsing proto file 

### ISSUE THREAD

**Issue by chen0572054** [apple/swift-protobuf#1103]
Hello, I am trying to create a custom generator. So, I am trying to use 
Google_Protobuf_Compiler_CodeGeneratorRequest(serializedData:data) to parse and get the Message object based on a proto file. 
the data object is read from a simple proto file with content of 
```
syntax = "proto2";

message SearchRequest {
  required string query = 1;
  required int32 page_number = 2;
  required int32 result_per_page = 3;
}
```
However, it keeps failing with error: `unknownField`
data is read like this 
`let data = FileHandle.init(forReadingAtPath: proto_path)?.readDataToEndOfFile()`
I debugged a bit, and seems it is trying to parse the first letter ("s", in the first line) as a fieldNumber but failed. 
I wonder if I am missing anything? or how can I correctly create a Message or CodeGeneratorRequest object for a proto file. Thank you! 

Please be sure to include:

* what OS you are developing on (Linux or macOS, including the version)  
 **`macOS`**

* for macOS, what version of Xcode you are using (`xcodebuild -version`), 
**`Xcode 12.3
Build version 12C33`**

  for Linux, what version of Swift (`swift --version`)

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
**`Apple Swift version 5.3.2`**

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
**`the latest release 1.14.0`**

* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.
**`unknownField`**

* lastly, if it all possible, provide a snippet of `.proto` and/or source
  that shows the problem.

```
syntax = "proto2";

message SearchRequest {
  required string query = 1;
  required int32 page_number = 2;
  required int32 result_per_page = 3;
}
```

Thank you!

**Comment by thomasvl** [comment]
> I debugged a bit, and seems it is trying to parse the first letter ("s", in the first line) as a fieldNumber but failed.


Can you explain how you are trying to use your plugin?  If it is getting the _s_ in _ syntax = "proto2";_ then it sounds like you are trying to directly pass a proto plugin a raw .proto file.  That won't work.  Plugins are used via protoc. protoc does all the parsing of the .proto files and invokes plugins based on the arguments given to protoc.

**Comment by tbkka** [comment]
As Thomas mentioned, you cannot easily run a protobuf code generator directly.  Instead, you run it via `protoc`.  If your generator is called `protoc-gen-foo`, then you run it with the `--foo_out` argument to `protoc`.  The `protoc` program will parse the `.proto` file and then run your `protoc-gen-foo` program giving it a properly-constructed `CodeGeneratorRequest` object.

**Comment by chen0572054** [comment]
@thomasvl thank you for your reply. I see. The use case we have now is that we want to customize the generated code. We would like to add some features/generated-code that are particular to our use case. 
Do you know where/how I can get parsed Google_Protobuf_CodeGeneratorRequest object? and be able to customize the code-gen? or whether that's feasible at all. Thank you!

**Comment by chen0572054** [comment]
Thank you @tbkka for your explanation. That makes more sense now. I wonder how I can get hold of Google_Protobuf_Compiler_CodeGeneratorRequest? I see in the main.swift, looks like it's initialized by requestData
`request = try Google_Protobuf_Compiler_CodeGeneratorRequest(serializedData: requestData)` 
I wonder how does protoc inject the CodeGeneratorRequest? Thank yoU!

**Comment by thomasvl** [comment]
protoc parses the .proto files, and builds up the binary protobuf message.  It then swaps you plugin via the mentiond `--foo_out` directive, and passes the binary serialization of the message.  The code in `main` then reads it and parses it to then generate from it.

**Comment by chen0572054** [comment]
Hello @thomasvl, I wonder how do we typically debug during development? For example, we make some changes and then `swift build ` and `protoc ` against the new build? 
It seems too many steps for testing a change. Wonder if there is a way to debug in xcode, i.e. run in xcode? Thank you!

**Comment by thomasvl** [comment]
Since you are writing your own plugin, that's entirely up to you.

What you likely ran into when the raw proto files were being parse by the plugin was how we've choice to do this. You'll notice it has a back door to help with this, it uses `PROTOC_GEN_SWIFT_LOG_REQUEST` in the env to write out the request it got from protoc.  Then when looking at its command line arguments, if there are files, it assumes they were from one of those dumps and reads them, if there aren't any files, it is the _normal_ protoc invocation and it reads from stdin.

**Comment by tbkka** [comment]
For `protoc-gen-swift`, we added the ability for it to read the serialized `CodeGeneratorRequest` from a file.  You can see that in `main.swift`.  Then you need to capture a `CodeGeneratorRequest` into a file, and you can then debug by running `protoc-gen-swift saved_request` to run it with the captured request.

The easiest way I've found to capture the `CodeGeneratorRequest` from protoc is to create a shell script like the following:
```
#/usr/bin/sh
cat >saved_request
```
Save this script as `protoc-gen-capture` and then you can run `protoc --capture_out` to get protoc
