### ISSUE TITLE
how to debug during development 

### ISSUE THREAD

**Issue by chen0572054** [apple/swift-protobuf#1104]
Hello, just to follow up on another issue but got closed. I wonder how do we typically debug during development (custom generator)? For example, we make some changes and then `swift build` to get the new protoc-gen-swift version and `protoc` against the new build?
It seems many steps for testing a change. Wonder if there is a way to debug in xcode, i.e. run in xcode? Thank you!

Please be sure to include:

what OS you are developing on (Linux or macOS, including the version)
macOS

for macOS, what version of Xcode you are using (xcodebuild -version),
Xcode 12.3 Build version 12C33

for Linux, what version of Swift (swift --version)

what version of Swift is your code set to compile with (i.e. from project
settings, etc.)
Apple Swift version 5.3.2

what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
the latest release 1.14.0

if you are getting compile errors, please be sure include all errors/warnings,
sometimes the error before the one you are stuck on is important.
unknownField

lastly, if it all possible, provide a snippet of .proto and/or source
that shows the problem.

syntax = "proto2";

message SearchRequest {
  required string query = 1;
  required int32 page_number = 2;
  required int32 result_per_page = 3;
}

Thank you!

**Comment by thomasvl** [comment]
The main goal of issues is bugs/help/problems with this library.  This is more a question about writing your own protoc plugin (which happens to be in Swift); that's not really something we're setting out to support.  It is more of a general development question for writing a Swift executable that just happens to have to interface with the protoc plugin interface.
