### ISSUE TITLE
Multiline comments creating extra newline

### ISSUE THREAD

**Issue by batkov** [apple/swift-protobuf#1107]
Please be sure to include:

* macOS 10.15.7

* Xcode 12.3

* Swift 5.3

* what branch/tag of SwiftProtobuf you are using: 1.15.0

* no errors or warnings

Here is .proto file:
```
enum Events {
 /*
   * After attempts to do somethings, there are some things happening
   * that is too long to write in one line.
   */
  THINGS_HAPPENING = 1;
}
```

Here is .swift generated file:
```
enum Events {
  ///
  ///
  /// After attempts to do somethings, there are some things happening
  ///
  /// that is too long to write in one line.
  case thingsHappening // = 1
}
```

Expected result would be:
```
enum Events {
  /// After attempts to do somethings, there are some things happening
  /// that is too long to write in one line.
  case thingsHappening // = 1
}
```

Is it something I'm writing wrong in .proto file? Is there a way to set up comments parameters?

**Comment by thomasvl** [comment]
What encoding is your input file?  I'm guessing maybe it has CRLF and that's what is tripping things up?

**Comment by batkov** [comment]
@thomasvl yes, I found out that the file has CRLF. After using `dos2unix` script from `brew` it actually worked as expected.
So what would be the solution? Each time person using this .proto on windows he should convert it and I should convert it when I'm generating for swift?

It would be great if plugin would have "--ignore_crlf" parameter. What do you think of such feature?

**Comment by thomasvl** [comment]
Can't say I've heard anyone run into this problem before in other languages.  If you generate C++/Java/etc in the state where Swift was doing double returns, what happens?  Since protoc does some processing as it parses, I wonder if it should be doing anything to normalize things if other languages also have similar issues.

**Comment by batkov** [comment]
@thomasvl dart and java files was ok. Without "double newlines".

**Comment by thomasvl** [comment]
C++?

We can try looking at how they handling things and see if we can find a better solution.

**Comment by thomasvl** [comment]
Ugh, I think I see how the others _avoid_ it, they `split` specifically on `"\n"`, so they don't _normalize it_ instead the CRLF gets recreated in the comments sections, and the rest of the file only has the `"\n"` they add when generating; i.e. - they make a mix line ending file.

**Comment by batkov** [comment]
Thank you, @thomasvl
