### ISSUE TITLE
Investigate if we can validate the protoc version being used

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#111]
Opening this to capture it and think on it, but we may just be stuck without a real solution.  ☹️ 

PR #95 started using the protoc provided JSON names instead of trying to create them within the generator (plugin).  This was needed to ensure an explicit json_name is honored by Swift.  The catch is protoc sets these strings in all cases.  The logic being it could allow a single implementation to transform the names so all languages are consistent.

PR #105 was done because my clean build showed things as not up to date.  What @allevato and I finally realized is this was a side effect of my version of google/protobuf being newer, so it had commits that improved (fixed?) more of the json support in the C++ library.

So the net result of PR #95 is swift-protobuf depends on developers using a 3.1 (maybe even later) release of protoc to get valid JSON support from the generated Swift classes.

We might be able to suggest the proto interface between protoc and plugins get expanded to relay the version so a plugin can check it, but the question becomes what version is passed, and how does google/protobuf know when to revise it?  As we discovered with this case, any change to the JSON name generation could justify a change to that version interface if it is being exposed to allow plugins to ensure conformance.

**Comment by tbkka** [comment]
protoc 3.0 shipped with known-broken JSON support.   So we know that using the protoc-generated JSON names with protoc 3.0 will not work correctly.  But there's nothing we can do about it.

Yes, protoc should advertise its version when it writes out the plugin data.

**Comment by thomasvl** [comment]
fyi - https://github.com/google/protobuf/pull/2437

**Comment by tbkka** [comment]
Huzzah!  Among other things, I'd like to include the protoc and plugin versions in the template we put at the top of each generated output file.  I suspect that will help when trying to diagnose issues reported by users.  So that boilerplate might look like:
```
/*
 * DO NOT EDIT.
 *
 * Generated by protoc 3.1.2 and protoc-gen-swift 0.9.36
 * Source: unittest_swift_all_required_types.proto
 */
```

**Comment by thomasvl** [comment]
While I think of it…

Having a line like:

> ` * Generated by protoc 3.1.2 and protoc-gen-swift 0.9.36`

Would mean every release of google/protobuf and every release of this project would cause generated sources and reference files to be stale and need to regenerate.  Or we look at filtering these lines just for the files within this repo.

**Comment by tbkka** [comment]
It probably makes sense to strip those lines from the sources in this repo to avoid the self-churn.

**Comment by thomasvl** [comment]
Closing this out, the plugin validates and issues warnings, but for now we're not going to do the version stamp in the files to avoid churn and because #234 added a compile time check that we can also use.
