### ISSUE TITLE
Of Interest:  SwiftPM support for code generation

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#1115]
SwiftPM has proposed a way to support code generators such as SwiftProtobuf.  If you're interested in such support, please take a look and let the SwiftPM team know what you think!

https://forums.swift.org/t/se-0303-package-manager-extensible-build-tools/45106

(Posting this as an issue so that people watching this project will be aware.  We can close this issue soon.)

**Comment by thomasvl** [comment]
Closing as I believe we now have this.
