### ISSUE TITLE
Generic parameter 'Element' could not be inferred - RingBuffer

### ISSUE THREAD

**Issue by thatsmerahul1** [apple/swift-protobuf#1146]
Before<img width="1270" alt="Screenshot 2021-05-03 at 1 09 02 AM" src="https://user-images.githubusercontent.com/16455638/116825443-08c8c780-abad-11eb-84e9-66f2cbb52246.png">opening a new issue, please double check the past issues (both open and
closed ones) to see if your problem has been discussed before<img width="1270" alt="Screenshot 2021-05-03 at 1 09 02 AM" src="https://user-images.githubusercontent.com/16455638/116825443-08c8c780-abad-11eb-84e9-66f2cbb52246.png">and already
contains an answer/solution. Likewise, check the FAQ in the Documentation folder
for some common things -
  https://github.com/apple/swift-protobuf/blob/master/Documentation/FAQ.md

Please be sure to include:

* what OS you are developing on - 11.2.3 (Big Sur)

* XCode Version - 12.4

* Swift Version - 4 & 5 both tried

* Latest branch of SwiftProtoBuf

* I am facing this error ("Generic parameter 'Element' could not be inferred") while compiling in below two files.
* CodedInputStream & RingBuffer

<img width="1270" alt="Screenshot 2021-05-03 at 1 09 02 AM" src="https://user-images.githubusercontent.com/16455638/116825628-b76d0800-abad-11eb-9aeb-071a7f7f9582.png">
<img width="1267" alt="Screenshot 2021-05-03 at 1 19 45 AM" src="https://user-images.githubusercontent.com/16455638/116825633-bcca5280-abad-11eb-8408-72d5e1d45d3f.png">

* Attaching screenshots

Thank you!

**Comment by tbkka** [comment]
You should file this bug against https://github.com/alexeyxo/protobuf-swift which is a completely independent and unrelated project.

**Comment by thatsmerahul1** [comment]
> You should file this bug against https://github.com/alexeyxo/protobuf-swift which is a completely independent and unrelated project.

I had filed but no response, I am trying to migrate from that library to the apple's swift-protobuf but facing a lot of issues.

**Comment by tbkka** [comment]
Are you using protoc-gen-swift from swift-protobuf  to generate your code?
