### ISSUE TITLE
Factor out JSON/text support

### ISSUE THREAD

**Issue by rowungiles** [apple/swift-protobuf#1150]
Hello,

In reference to https://github.com/apple/swift-protobuf/issues/18 I see the extension from this work, the `_ProtoNameProviding` which has the comment:

```
/// Messages conform to this protocol to provide the proto/text and JSON field
/// names for their fields. This allows these names to be pulled out into
/// extensions in separate files so that users can omit them in release builds
/// (reducing bloat and minimizing leaks of field names).
```

It isn't clear to me after having an initial look through the source and docs how to generate these extensions into separate files to achieve the described. Unless I have a custom generator.

Please could you point me in the right direction? 

Thank you

**Comment by thomasvl** [comment]
There isn't support for it yet, the issue is an enhancement to investigate how to add such support.

**Comment by rowungiles** [comment]
Thanks for the speedy response @thomasvl .
