### ISSUE TITLE
Use a Swift code generation library in protoc-gen-swift?

### ISSUE THREAD

**Issue by makleso6** [apple/swift-protobuf#1153]
Hi! Is it possible to generate code using https://github.com/SwiftGen/StencilSwiftKit.git?
What plugin should I write? I didn't find any documentation for writing plugins

**Comment by ktoso** [comment]
It would be exciting to change the source gen to use swift-syntax builders that have been slowly growing over here: https://github.com/apple/swift-syntax/tree/main/Sources/SwiftSyntaxBuilder

But that'd require Swift 5.5+ and also is not quite fully complete yet I think (not sure)?

**Comment by Lukasa** [comment]
I think it's highly unlikely that the primary method of protobuf code generation will change anytime soon, due to protobuf's substantial support for older Swift versions.

**Comment by ktoso** [comment]
Yeah, should have prefaced my reply with that.

That _if_ one were to invest into some alternative, swift-syntax would be the future-looking tool of choice.

**Comment by thomasvl** [comment]
There's also a question of what the return on the effort would be.  Since it either would add atleast one dependency, it would make building slight more complex also.

**Comment by tbkka** [comment]
Documentation on writing protoc plugins: https://developers.google.com/protocol-buffers/docs/reference/other

**Comment by tbkka** [comment]
As Thomas pointed out, there are active drawbacks to this idea.  I'm not opposed to this, but it would be a lot of code churn for very little gain.
