### ISSUE TITLE
swift 5.5 async await

### ISSUE THREAD

**Issue by bordunosp** [apple/swift-protobuf#1155]
are you planning to move to the "async-await" paradigm?
mb there is already some branch for tests?

**Comment by thomasvl** [comment]
Since this project doesn't have any apis that work via completion, what were you think would make sense to support via async-await?

**Comment by bordunosp** [comment]
rm "EventLoopFuture" and add "async" into the generated *.grpc.swift files

**Comment by thomasvl** [comment]
That would be the GRPC project, and not this one.

**Comment by bordunosp** [comment]
new project and new repository?

**Comment by bordunosp** [comment]
oh u about "grpc-swift_opt", my mistake, wrote in the wrong place)

**Comment by thomasvl** [comment]
> new project and new repository?

Sorry, I'm not sure I follow the question.

I'm assuming you are using some GRPC project to generate *.grpc.swift files.  This project has never generated those.  My guess would be maybe you are talking about https://github.com/grpc/grpc-swift, but I wasn't sure if there was another project that you might be using.
