### ISSUE TITLE
Swift Package Manager 5.3 cannot found package

### ISSUE THREAD

**Issue by zlrs** [apple/swift-protobuf#1156]
I was on a project using Swift Package Manager 5.1 and 'swift-protobuf' 1.16.0 and everything worked. For some reason I need to set minimum macOS version to `.v11` and to do that I have to upgrade the `swift-tools-version` of `Package.swift` to 5.3. However after setting it, the project cannot compile. 

Error saying:
```
unknown package 'SwiftProtobuf' in dependencies of target '....'; valid packages are: 'swift-log', 'swift-nio', 'swift-protobuf'
```

## my Env
OS: macOS BigSur
XCode: 12.5
swift-protobuf 1.16.0
SPM version: 5.3

## project `Package.swift`
```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "....",
    platforms: [.macOS(.v11)],
    products: [
        .executable(name: "....", targets: ["...."]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-log", .exact("1.4.2")),
        .package(url: "https://github.com/apple/swift-nio", .exact("2.30.0")),
        .package(url: "https://github.com/apple/swift-protobuf.git", .exact("1.16.0")),
    ],
    targets: [
        .target(
            name: "....",
            dependencies: [
                .product(name: "Logging", package: "swift-log"),
                .product(name: "NIO", package: "swift-nio"),
                .product(name: "SwiftProtobuf", package: "SwiftProtobuf"),
            ],
            path: "Sources"
        )
    ]
)
```

To my eye, it has something to do with the difference between the folder name(`swift-protobuf`) and the package name(`SwiftProtobuf`).

**Comment by Lukasa** [comment]
Yup, that's correct. You need to tell Swift Package Manager what the name of this package is. You can see [grpc-swift doing this here](https://github.com/grpc/grpc-swift/blob/f219c2ead0509ba76007c242b7c45beff7fbaaae/Package.swift#L40-L44). In your case, change `.package(url: "https://github.com/apple/swift-protobuf.git", .exact("1.16.0")),` to:

```
    .package(
      name: "SwiftProtobuf",
      url: "https://github.com/apple/swift-protobuf.git",
      .exact("1.16.0")
    ),
```

and this should work nicely.

**Comment by zlrs** [comment]
> Yup, that's correct. You need to tell Swift Package Manager what the name of this package is. You can see [grpc-swift doing this here](https://github.com/grpc/grpc-swift/blob/f219c2ead0509ba76007c242b7c45beff7fbaaae/Package.swift#L40-L44). In your case, change `.package(url: "https://github.com/apple/swift-protobuf.git", .exact("1.16.0")),` to:
> 
> ```
>     .package(
>       name: "SwiftProtobuf",
>       url: "https://github.com/apple/swift-protobuf.git",
>       .exact("1.16.0")
>     ),
> ```
> 
> and this should work nicely.

This solves the problem. Thanks! 
In fact, XCode shows code auto-completion just after I type part of the code. :D
