### ISSUE TITLE
Add an option to use `@_implementationOnly import SwiftProtobuf`

### ISSUE THREAD

**Issue by wangjiejacques** [apple/swift-protobuf#1157]
Currently the generated `xxx.pb.swift` always use `import SwiftProtobuf`, but sometimes we want to use `@_implementationOnly import SwiftProtobuf`, it would be nice to have an option to do so.

**Comment by teogeos** [comment]
For context: we make a library, an XCFramework used by our client's apps. Without `@_implementationOnly` we get a warning and lose ABI stability warranty.

**Comment by thomasvl** [comment]
If a proto file imports another one, it is likely because of the types (message/enums) are used as fields.  So it wouldn't really be implementation only as the types are exposed by the types in the generate file.

I'm guessing you want the protos to be an implementation details of your types and you don't expose them?  i.e. - they should be implementation imports of your code?

If that's what you are after, what's the error?  Sounds like maybe this should be an issue agains Swift for the transitive imports of `@_implementationOnly` imports?

**Comment by teogeos** [comment]
We're not talking about protos importing other proto files. We're talking about importing the core `SwiftProtobuf` lib.

We're writing a framework that deals with protobufs. We call `protoc` to generate swift classes for our protos, then put the generated files in our project. But these generated files have `import SwiftProtobuf`, without `@_implementationOnly`, which means our framework loses ABI stability. As of now we have to add `@_implementationOnly` to the generated files ourselves.

We don't want to expose any type coming from `SwiftProtobuf`.

**Comment by wangjiejacques** [comment]
Following this [discussion](https://github.com/apple/swift-protobuf/issues/1101#issuecomment-752030103), `@_implementationOnly import SwiftProtobuf` probably should be the default behavior.

**Comment by thomasvl** [comment]
Ah, ok, I'm following now.  I was mistakenly thinking you wanted all imports as impl only and that's what confused me.

**Comment by teogeos** [comment]
Makes sense to me not to make it default.

But do you think it could be a good idea to make it a code generation option?

**Comment by paynerc** [comment]
> But do you think it could be a good idea to make it a code generation option?

It would be nice if there was an option for this... Ended up having a script do this after generating the .swift files.

**Comment by daniellfalcao** [comment]
@teogeos I'm trying to create a XCFramework with SwiftProtobuf dependency too but I got some erros describers [here](https://github.com/grpc/grpc-swift/issues/1391), can you give some tips? From what you said i think you obtained success to generate the framework

**Comment by Lukasa** [comment]
At this time there is not.

**Comment by tbkka** [comment]
The standard Unix `sed` command can replace text in groups of files.
