### ISSUE TITLE
Support for Swift Concurrency

### ISSUE THREAD

**Issue by florentmorin** [apple/swift-protobuf#1158]
In current version, which is today `1.0.17`, `Dispatch` is used in [Google_Protobuf_Any+Registry.swift](https://github.com/apple/swift-protobuf/blob/4b11fbc4f2fea757d15fb6d392c7155f1e598bdd/Sources/SwiftProtobuf/Google_Protobuf_Any+Registry.swift) for a queue with label `org.swift.protobuf.typeRegistry`.

But, since Swift 5.5, concurrency is managed at [language level](https://docs.swift.org/swift-book/LanguageGuide/Concurrency.html). And, with Swift Concurrency, there is a [runtime contract with the system](https://developer.apple.com/videos/play/wwdc2021/10254/) to avoid thread explosion.

As a developer, I want to benefit from the opportunities offered by Swift Concurrency. 

Any plan for Swift Concurrency support? Thank you! 😀

**Comment by Lukasa** [comment]
The use of Dispatch in this module is only as a lock: all dispatches are `sync`, so no concurrency is invoked and there is no risk of thread explosion. No change to this module is required for you to benefit from Swift Concurrency when using Swift Protobuf.
