### ISSUE TITLE
How to get the rawValue when it unknown in Enum?

### ISSUE THREAD

**Issue by Corotata** [apple/swift-protobuf#1161]
* macOS 11.5

* Xcode 13.0

* swift-protobuf: stable 1.17.0 (bottled), HEAD

* SwiftProtobuf (1.17.0)

Order Proto:

```
enum LHContentType {
    TEXT = 0;                   
    IMAGE = 1;                  
}

message CommonChat {
    optional string msg_id = 1;
    optional LHContentType type = 2;
    optional string from = 3;
    optional string from_name = 4;     
    optional string to = 5;
    optional string content = 6;
    optional int64 time = 7;
    optional int64 clt_time = 8;       
    optional LHChatType chat_type = 9;    
}
```

In new Proto, I add enum case Voice
```
enum LHContentType {
    TEXT = 0;                   
    IMAGE = 1;       
    VOICE = 2;                      
}

```

When new Client use new Proto to send CommonChat to order Client(use the older Proto),it can receive like this:
```
Content:Optional(
Common_chat {
  msg_id: "5F962D48-AA9A-4C87-8B81-8A0F3200727B"
  from: "60c814d09b7968357dc117ca"
  from_name:"sir"
  to: "60c804dc5251de55c07c2753"
  content: "hello"
  time: 1628228926425
  chat_type: USERTOUSER
  2: 2
}
)
```

LHContentType type is (2:2),but it can not be parser, I need the get the value and store it , is there any way to get the rawValue?

**Comment by thomasvl** [comment]
The library currently just puts all the unknown fields into the unknown storage - https://github.com/apple/swift-protobuf/blob/main/Sources/SwiftProtobuf/Message.swift#L53.  There currently isn't a higher level api on that.

But I'm a little confused by the question, for old clients, they won't know about the field, but if you are going to update clients, why aren't you just using the updated proto file with the new field/enum definitions?  Then it won't be unknown and you can directly access it?

**Comment by thomasvl** [comment]
ps - your proto file is likely proto2 syntax, proto3 syntax defines some different behaviors around enums, specifically the way new enum values are parsed/exposed.  But you'll need be sure you understand *all* the differences that happen before considering changing the syntax on the file.  See the protobuf documentation in general for the two syntax definitions and differences.

**Comment by Corotata** [comment]
For example, in app version **1.0.0**, currently I only support **TEXT** and **IMAGE** messages. The Proto I use is as follows:

```
//msg.proto  -> Version 1.0.0
enum LHContentType {
    TEXT = 0;                   
    IMAGE = 1;                  
}

message CommonChat {
    optional string msg_id = 1;
    optional LHContentType type = 2;
    optional string from = 3;
    optional string from_name = 4;     
    optional string to = 5;
    optional string content = 6;
    optional int64 time = 7;
    optional int64 clt_time = 8;       
    optional LHChatType chat_type = 9;    
}
```


In app version **2.0.0** to support sending voice messages. However, in app **1.0.0**, I didn't think I would add voice message. It's unknown.So The Proto in app **2.0.0** use as follows:

```
//msg.proto  -> Version 2.0.0
enum LHContentType {
    TEXT = 0;                   
    IMAGE = 1;       
    VOICE = 2;                      
}

message CommonChat {
    optional string msg_id = 1;
    optional LHContentType type = 2;
    optional string from = 3;
    optional string from_name = 4;     
    optional string to = 5;
    optional string content = 6;
    optional int64 time = 7;
    optional int64 clt_time = 8;       
    optional LHChatType chat_type = 9;    
}
```


Now, **UserA** use app version **1.0.0**, **UserB** update app to version **2.0.0**. 

When they only chat through **Text** Or **Image** messages, there will be no problem. 

Now **UserB** sends a **Voice**(new Type) message to **UserA**, **UserA** will not be able to parse the filed Type(Enum **LHContentType** type = 2) the rawValue, 
Theoretically, the value is（ **type: 2**）, Because it cannot be parsed, it becomes (**2:2**), 
the first **2** is the field(type-> the enum **LHContentType**), the second **2** is the rawvalue of **LHContentType.Voice**. 


So I want to know how to get the filed and rawValue, so that I can store it.
When UserA upgrades the app from version **1.0.0** to **2.0.0**, he can read voice messages normally.

**Comment by Corotata** [comment]
> ps - your proto file is likely proto2 syntax, proto3 syntax defines some different behaviors around enums, specifically the way new enum values are parsed/exposed. But you'll need be sure you understand _all_ the differences that happen before considering changing the syntax on the file. See the protobuf documentation in general for the two syntax definitions and differences.

I use proto3,it has case UNRECOGNIZED,now I can get the rawValue,thank you.

**Comment by thomasvl** [comment]
So while you might be able to special case your enum right now, if you are really worried about upgrades, the safest bet would be to store the raw protobuf binary so a future client can re-parse it.  i.e. - a future update could add new fields, etc. so the only safe way if you are worried would be to store the whole thing.

Another option I've seen folks do when using their own storage is store a version number of the app, then when the app updates, they know to re-download things to allow updated parsing for any schema changes specific to the new apps.

Anyway, closing this since there doesn't seem to be an issue with the library here.
