### ISSUE TITLE
Module 'SwiftProtobuf' was created for incompatible target x86_64-apple-macos11.0: 

### ISSUE THREAD

**Issue by williamhqs** [apple/swift-protobuf#1162]
I'm trying to build `SwiftProtobuf.framework` for using on my Xcode project which support both iOS and MacOS. But the framework isn't correct version when running on Mac.

MacOS version: **Big Sur 11.5.1**
Xcode **12.5.1**
Swift **5**
SwiftProtobuf **1.17.0** (`github "apple/swift-protobuf" == 1.17.0`)

The error is:
![Screen Shot 2021-08-24 at 10 55 21 AM](https://user-images.githubusercontent.com/354829/130548437-763a56ab-e120-47c1-91b4-baaa099c5d03.png)

I generate the framework file by building the `SwiftProtobuf_macOS` target:
![WeChatWorkScreenshot_dec015d9-ce2e-4b1a-b29a-d57d33985bf0](https://user-images.githubusercontent.com/354829/130548586-0c35ab05-1091-49eb-9eb3-f3bdf76ca295.png)

Then copy the file into my project.

For my project settings:
![Screen Shot 2021-08-24 at 10 58 18 AM](https://user-images.githubusercontent.com/354829/130548663-a7b7ad2f-420e-49df-8e80-7a8e967980ca.png)

![Screen Shot 2021-08-24 at 10 59 13 AM](https://user-images.githubusercontent.com/354829/130548732-2b7d7698-4dac-4471-96ed-23863d863702.png)

I also tried to set the deployment target to my Mac OS version but the latest one is 11.3, my Mac OS is 11.5
![Screen Shot 2021-08-24 at 10 59 58 AM](https://user-images.githubusercontent.com/354829/130548797-8a2871f0-1777-4476-8ef7-20fede875114.png)

Any help what should I do? Thanks!

**Comment by thomasvl** [comment]
It almost looks like you might be trying to build for catalysts and not for macOS.  The project likely needs some tweaks to support catalysts correctly.

**Comment by thomasvl** [comment]
Closing this out as we've dropped the local Xcode project in favor of the SwiftPM support within Xcode (and still have the CocoaPods support also).
