### ISSUE TITLE
JSON Decoding : casting `google.protobuf.Any` to a certain type?

### ISSUE THREAD

**Issue by PopFlamingo** [apple/swift-protobuf#1193]
I am decoding JSON data where I don't know the type of one of the fields upfront, I know I could use `Value` but my issue is that AFAICT you cannot simply convert `Value` to another existing type (ie: no `MyOtherType(fromValue: myValue)`) so I thought I would use `google.protobuf.Any`, and then, depending on the context, decode to the type I wish but I can't find the API to do this (`MyOtherType(unpackingAny:)` doesn't work, which I believe is expected), am I missing it or is this not possible today?

**Comment by PopFlamingo** [comment]
Looking at the source code, I found this way to decode the object:
```swift
Google_Protobuf_Any.register(messageType: MyType.self)
var any = try someObject.anAnyProperty
any.typeURL = MyType.protoMessageName
let decoded = try MyType(unpackingAny: any)
```

Is this the correct way to do this or is there a simpler one? Thank you

**Comment by PopFlamingo** [comment]
@thomasvl 

I want to decode objects that can have variations in the types of some of their properties for instance:
```json
{ "a": 0, "b": "hello", "c": { "x": 0, "y": 0 }}
```

Or 
```json
{ "a": 0, "b": "hello", "c": { "abc": true, "x": 10.4 }}
```

So currently my corresponding `message` is written this way:
```proto
message MyMessage {
  int64 a = 1;
  string b = 2;
  google.protobuf.Any c = 3;
}
```

I indeed like to be able to use `init(jsonSting:)` and related functions, but my issue is that I only have a string/data for the top level object. Is there a way to get the data of the JSON specifically for the `c` property value?

**Comment by PopFlamingo** [comment]
> Protobuf is pretty opinionated about how Any and Value are used; they have specific encodings and aren't for generic JSON. If you are getting an Any over the wire, it should already have the type set, so you shouldn't have to set it.

Are you suggesting my current approach may break in the future? Currently it seems to be working properly but I would like to make sure it is safe to do it this way (provided there isn't a better alternative).

**Comment by thomasvl** [comment]
That sorta sounds like you are using your own JSON encoding conventions, so no, there isn't anything in the library to support that since the JSON support is built to the protobuf specs for JSON encoding.

**Comment by tbkka** [comment]
If you can't change this design, then the best you can do with SwiftProtobuf is either to declare `c` as a `Value` and then re-encode that one field back to JSON, or do as you have done here.
But I would encourage you if you can to change this so that you have different fields for different types.  Protobuf handles that very well via `oneof` fields.

**Comment by thomasvl** [comment]
@tbkka, I was thinking the same about the `oneof` also, but the repeat of `x` with different types would be an issue.

@PopFlamingo `Value` would work for `c`, but you'd end up with a `Struct` for the contents, which might not be what you want, but as @tbkka mentions, you could re-serialize that and then parse it again into your correct subtype.  That's basically what you are doing via the `Any`, it just takes mutating the object.  You could do your own `extension` on Struct to make a helper for it similar to what there is for `Any`.

**Comment by PopFlamingo** [comment]
I am unfortunately decoding a JSON format I don't have any control over.

@tbkka @thomasvl  Do you see any issue with my current approach ? Using `Value` does seem somewhat cleaner as it is designed specifically for this use case but I am worried about the performance impact of re-encoding/re-decoding? From quickly looking at the implementation it seemed like the `MyType(unpackingAny:)` approach just takes the existing JSON data and decodes it, am I right?

**Comment by tbkka** [comment]
Yes, the current implementation of `Any` does just store the JSON internally and then decode in for `unpackingAny`.  However, you might experiment a bit:  SwiftProtobuf's JSON implementation is pretty fast, so you might find the cleaner approach works just as well in practice.

**Comment by PopFlamingo** [comment]
Thank you! In this case I'll make some speed tests to compare the two approaches and I'll post the results here.

**Comment by PopFlamingo** [comment]
I made some tests, from what I can see the approach using `Value` gets slower pretty quickly as the object has more and more content, even a rather small JSON object was around 3x slower using `Value`.

Thank you again for your help!

**Comment by thomasvl** [comment]
Just confirming: You did your timing with in a release build, not a debug one?

We'll go ahead and close this issue then since there never really was an issue with the library itself.

**Comment by PopFlamingo** [comment]
@thomasvl Yes it was in release indeed.
