### ISSUE TITLE
Cannot pass immutable value as inout argument

### ISSUE THREAD

**Issue by gmosx** [apple/swift-protobuf#120]
I try to compile a simple Protocol Buffer:

```
message ProtoMessage {
    required uint32 payloadType = 1;
    ...
}
```

The `protoc` compiler generates the Swift files but when I try to build the project I get the following error:

````
/.../Sources/Messages.pb.swift:93:93: error: cannot pass immutable value of type 'inout UInt32?' (aka 'inout Optional<UInt32>') as inout argument
    case 1: handled = try setter.decodeSingularField(fieldType: ProtobufUInt32.self, value: &_payloadType)
```

Any ideas?

**Comment by thomasvl** [comment]
Are you using `master` or are you using a labeled tag?  There was a recent change around how fields are modeled in general that might have made this go away if you were on a tag.

**Comment by gmosx** [comment]
I just followed the instructions here:

https://github.com/apple/swift-protobuf/

So, I guess, I am using master. Any other ideas?

**Comment by gmosx** [comment]
I am using:

$ protoc-gen-swift --version
protoc-gen-swift 0.9.24

**Comment by thomasvl** [comment]
There's a few directions there; `swift build` (using a tag), CocoaPods (uses `master`), a clone a build (uses `master`).

**Comment by thomasvl** [comment]
Re:

>  ```swift
>  dependencies: [
>      .Package(url: "https://github.com/apple/swift-protobuf.git", majorVersion:0)
>  ]
>  ```

I believe that just says use the newest 0.x, so you are using an older tag where things might not have been working.

**Comment by thomasvl** [comment]
There also is a testing file that covers this:

https://github.com/apple/swift-protobuf/blob/master/Protos/unittest_swift_all_required_types.proto#L57

```protobuf
  required   uint32 required_uint32   =  3;
```

Generated:

https://github.com/apple/swift-protobuf/blob/master/Tests/SwiftProtobufTests/unittest_swift_all_required_types.pb.swift

So it is built into the tests.

**Comment by thomasvl** [comment]
Actually, I think what is happening is you are mixing versions.

`protoc-gen-swift` is likely from trunk, so it is generating for the current version of the runtime, but the Package file is pulling a tagged version.  So the sources you are generating don't work with it.

You need to build `protoc-gen-swift` from the same 0.9.24 tag that the package manager is including in your app.

**Comment by gmosx** [comment]
Indeed, I built from the 0.9.24 tag and it worked. 
Maybe the documentation should be updated to make this point more explicit.

In any case, thanks for your help :)

**Comment by thomasvl** [comment]
np.  Yea, the docs have a [small nod](https://github.com/apple/swift-protobuf#building-your-project-with-swift-build) to it, but the problem is our master reports the same things as our last branch.  ☹️

**Comment by gmosx** [comment]
yeah, the version on the master should be updated or something.

**Comment by thomasvl** [comment]
> yeah, the version on the master should be updated or something.

Yup, bumped it in PR #122 right after closing this yesterday.
