### ISSUE TITLE
jsonString lost origin type?

### ISSUE THREAD

**Issue by cdoky** [apple/swift-protobuf#1203]
```swift
message User {
    int64 id = 1;
    string name = 2;
}
```
```swift
var user = User()
user.id = 100
user.name = "123"
let json = try? user.jsonString()
// output: {"id": "100", "name": "123"}
// but I need: {"id": 100, "name": "123"}
```

**Comment by thomasvl** [comment]
There are multiple ways to encode/decode an object into JSON.  The Protocol Buffers spec spells how it should be done for messages: https://developers.google.com/protocol-buffers/docs/proto3#json.  That includes the 64bit integer types always being encoded as strings (but accepted as either).

I believe this goes back to ensuring if the payload is received via Javascript it can be received without data loss do to that spec.

**Comment by cdoky** [comment]
@thomasvl OK, Thank you!

**Comment by tbkka** [comment]
If you're working with a non-Protobuf JSON implementation, you should use `int32`, `uint32`, `float`, or `double` types for numbers; Protobuf JSON does not encode those as strings.
