### ISSUE TITLE
Proto file imports

### ISSUE THREAD

**Issue by dulataldazharov** [apple/swift-protobuf#1205]
I am developing on Ubuntu 20.04.2 LTS with Swift version 5.3.
I am using 1.8.0 tag of the project.
I created two .proto files.
One is located at /home/me/project/testing/test.proto
```
syntax = "proto3";

import "google/protobuf/any.proto";
import "testing/second.proto";

message Test {

  int32 id = 1;

  string name = 2;

  google.protobuf.Any detail = 3;

  Second sec = 4;
}
```
Second is at /home/me/project/testing/second.proto
```
syntax = "proto3";

package testing;

message Second {

  int32 id = 1;

  string name = 2;
  
}
```
As you can see, test.proto imports second.proto. When I try running:
```
protoc -I=/home/me/project --swift_out=swiftout /home/me/project/test.proto
```
I get an error message:
```
testing/second.proto: File not found.
```
How to properly import one proto file in another?

**Comment by tbkka** [comment]
First, you need to refer to the `Second` message as `testing.Second` since it is in the `testing` package:
```
message Test {
  ...
  testing.Second sec = 4;
}
```

Then you should double-check the files and paths:  Above, you first said that the file was in `home/me/project/testing/test.proto` but your command line example doesn't include the `testing` directory.

**Comment by thomasvl** [comment]
slight aside: _1.8.0_ is also a pretty old release, any reason you need to use that old of a release?

**Comment by dulataldazharov** [comment]
I solved the problem finally.
I didn't know that the file paths indicated in imports in proto files (e.g. import "testing/second.proto") have to be a direct continuation of the proto_path argument which is by default the current directory.
