### ISSUE TITLE
Warning from SwiftLint

### ISSUE THREAD

**Issue by AlainHsu** [apple/swift-protobuf#1226]
* what OS you are developing on (Linux or macOS, including the version)
> macOS  Monterey v12.2.1

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
  for Linux, what version of Swift (`swift --version`)
> Xcode 13.3 Build version 13E113

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
> Swift 5

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
> 1.19.0

* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.
> As below

```swift
// Warning: Private over fileprivate Violation: Prefer `private` over `fileprivate` declarations. (private_over_fileprivate)
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
// Error: Type Name Violation: Type name should only contain alphanumeric characters: '_2' (type_name)
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}
```

There are more SwiftLint warnings that i didn't list them all.

**Comment by tbkka** [comment]
As a rule, you should not waste your time running SwiftLint over generated sources.  These issues are stylistic issues that do not affect the functionality in any way.  If any of the SwiftLint warnings you're seeing are functional, please let us know.

If you really think it's essential to fix the stylistic issues, please send us PRs to do so.  Keep in mind that we may not accept them.  For example, `_2` is a perfectly valid (if unusual) spelling for a type name in Swift and changing it would in this case cause a compatibility problem.
