### ISSUE TITLE
Allow opting-out of CustomDebugStringConvertible to reduce binary size

### ISSUE THREAD

**Issue by bubski** [apple/swift-protobuf#1245]
This observation comes from researching https://github.com/apple/swift-protobuf/issues/1204.

It appears that `CustomDebugStringConvertible`'s contribution to the binary size adds up and is not insignificant.
A quick check shows that removing it from [`Message`](https://github.com/apple/swift-protobuf/blob/1.17.0/Sources/SwiftProtobuf/Message.swift#L34), [`SimpleExtensionMap`](https://github.com/apple/swift-protobuf/blob/1.17.0/Sources/SwiftProtobuf/SimpleExtensionMap.swift#L17), [`AnyExtensionField`](https://github.com/apple/swift-protobuf/blob/1.17.0/Sources/SwiftProtobuf/ExtensionFields.swift#L30) would save us `~800kB`.

For context, our project has around 1000 message definitions.
This was a modified version **1.17.0**,
compiled with `-Osize`,
Xcode 13.2.1 13C100, Swift 5.5.2, Big Sur

Since conforming to `CustomDebugStringConvertible` does not seem essential, perhaps it could could be tied to a compilation flag?
I'd like to hear some initial feedback @thomasvl before getting into details.

**Comment by thomasvl** [comment]
This sounds sorta like another take on #1240.

With respect to compilation flags - those seems like they never work in practice with build systems - i.e. - how does one make that work (at scale) with SwiftPM/CocoaPods/etc.

TVL

**Comment by dflems** [comment]
@thomasvl: The `DEBUG` compilation condition seems fairly universal among build systems:

- CocoaPods adds `DEBUG` to swift compilation conditions under debug in the generated Xcode project ([link](https://github.com/CocoaPods/CocoaPods/blob/e83d3264d4960d53dcb0cc921b0468f768dd3ed4/lib/cocoapods/project.rb#L388-L390))
- SwiftPM adds `-DDEBUG` to all compiles in the debug configuration ([link](https://github.com/apple/swift-package-manager/blob/0481abf8de3b21ce8481e81291c3df1b430cb225/Sources/XCBuildSupport/PIFBuilder.swift#L313))
- `rules_swift` adds it for `dbg` and `fastbuild` configs ([link](https://github.com/bazelbuild/rules_swift/blob/36b915411f53a42f4f6b3ac7b15f4a40ffec619c/swift/internal/compiling.bzl#L373-L383))

**Comment by thomasvl** [comment]
Yes, `DEBUG` would be less of an issue, I was taking the initial comment to be something developers directly controlled.

**Comment by dflems** [comment]
@thomasvl Took a crack at it here: https://github.com/apple/swift-protobuf/pull/1246
