### ISSUE TITLE
A dependency of swift-protobuf also builds the (unwanted) protoc-gen-swift CLI utility

### ISSUE THREAD

**Issue by gmosx** [apple/swift-protobuf#125]
I have a project where I would like to use some Swift code generated from .proto files, using the `protoc-gen-swift` plugin. As described in the documentation, I added the following dependency to my project:

```
dependencies: [
        .Package(url: "https://github.com/apple/swift-protobuf.git", Version(0,9,23))
]
```

However, whenever I try to build my project (using `swift build`) the `protoc-gen-swift` program is also built, further delaying the already longish build process.

Any idea how to avoid building the `protoc-gen-swift` command on projects that only need to use the generated files?

**Comment by thomasvl** [comment]
Looks like SwiftPM can't do this.  The [docs for manifest](https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#package) say:

> ... There should only be one package declared per manifest.

I think we might be able to hack/work around this if we moved `Sources/PluginLibrary/` and `Sources/protoc-gen-swift/` into a top level `protoc-gen-swift` directory.  i.e. - make the root of the project (and Package.swift) just the runtime support, and have a directory inside with plugin itself (that can reference the parent project to get the runtime).  External stuff might not be able to depend on the plugin, but that might be a better state in that everyone wanting to use the runtime doesn't have to end up depending on the plugin also.

@tbkka @allevato thoughts?

**Comment by thomasvl** [comment]
@tbkka should we also bump this up on the list as something to sort out before release?

**Comment by tbkka** [comment]
This isn't something we'll be able to fix without changes to Swift PM.  We should file an issue on Swift PM (if there isn't one already) and track that so we can update when it's possible to do better.

**Comment by thomasvl** [comment]
So the code shuffle suggested wouldn't work?

**Comment by jcanizales** [comment]
> External stuff might not be able to depend on the plugin

I expect that https://github.com/grpc/grpc-swift will eventually need to depend on this plugin, same as with the ObjC versions.

**Comment by thomasvl** [comment]
> I expect that https://github.com/grpc/grpc-swift will eventually need to depend on this plugin, same as with the ObjC versions.

So it will be written in Swift?  I figured you'd be in C++ for any common support between the different grpc impls.

**Comment by jcanizales** [comment]
Yeah, Swift. For this one we're prioritizing lowering the barriers to form
a community. It might even turn out to be easier, despite not having the
resolved Descriptor class to reuse, on account of having string
interpolation for the generation.

**Comment by thomasvl** [comment]
I couldn't find an existing SwiftPM bug for this, so I went ahead and created [SR-3346](https://bugs.swift.org/browse/SR-3346) for it.

**Comment by allevato** [comment]
I recently started taking a look at the conformance test runner and it would be extremely convenient if that was in the main project as well. It's already stale because of naming changes that we've made; that project is still tied to an old version of the runtime in its `Package.swift`.

If we put those things in separate top-level folders with their own `Package.swift`, does SwiftPM still insist on *cloning* that repo within the subdirectory or does it just reference it directly? That behavior makes iteration a bit more annoying—that is, if I want to make changes to the runtime and see them reflected in the conformance tests right away. We could use the Makefile to maybe clean this up a bit, but it's frustrating that SwiftPM makes local dependencies during development so awkward, unless I'm missing something.

**Comment by allevato** [comment]
Follow-up: Looking at the accepted proposal in SR-3346, I would be in favor of moving the conformance test runner into this repo as well and adding it as a top-level target. Yes, that will increase build times for people depending on this package, but hopefully we can address that once SE-0146 is implemented; in the meantime, it will make it much easier to iterate on conformance tests and keep them up-to-date. Thoughts?

**Comment by tbkka** [comment]
Yes.  Let's do this.

**Comment by thomasvl** [comment]
fyi - SE-0146 got accepted, so hopefully we'll see something on a release soon.

**Comment by thomasvl** [comment]
Hm, so looking at https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md, it doesn't seem like anything got added to the `dependencies` support to call out just needing a specific `product` from the package to a subset can be built.  Anyone see something I'm missing?

**Comment by thomasvl** [comment]
Closing this out now the SwiftPM has multiple product support, so hopefully things are working better compared to when it was opened.
