### ISSUE TITLE
Some new conformance tests don't pass

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#1257]
As of protobuf 316a97bfea2de479787908b9fe9f2bd9e7949d52, these tests fail:

>  Required.Proto3.JsonInput.DurationNegativeNanos.JsonOutput
>  Required.Proto3.JsonInput.DurationNegativeNanos.ProtobufOutput

**Comment by thomasvl** [comment]
I've got some fixes for these already

**Comment by thomasvl** [comment]
@tbkka is this worth making a 1.x branch and doing a release there?  I guess part of the question is when do we think we'll want to cut a 2.0 (and thus stop breaking changes).

**Comment by tbkka** [comment]
We'll probably have to make a 1.x branch eventually anyway to support folks who can't adopt 2.0 right away.  So I guess so...

**Comment by thomasvl** [comment]
> We'll probably have to make a 1.x branch eventually anyway to support folks who can't adopt 2.0 right away. So I guess so...

ok attempting that…
