### ISSUE TITLE
Proto2 syntax, packed repeated enum fields are lossy for unknown values

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#127]
Proto2 syntax enum fields (singular or repeated), should move any unknown values into the unknown fields support so the data isn't lost and will reflect back if the message is serialized back out.  Currently the data is lost:

https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/ProtobufBinaryTypes.swift#L735

```swift
 public static func setFromProtobufBuffer(buffer: UnsafeBufferPointer<UInt8>, value: inout [Self]) throws -> Bool {
        var decoder = ProtobufBinaryDecoder(protobufPointer: buffer)
        while let t = try decoder.decodeInt32() {
            if let e = Self(rawValue:Int(t)) {
                value.append(e)
            }
        }
        return true
    }
```

From @tbkka:

> The inner ‘if’ here needs an ‘else’ where it does something with the unrecognized enum value.
> I think the best approach is going to be to encode a new field and push that constructed field
> onto the unknown storage via the decoder object.  That requires the decoder object to have a
> reference to the unknown field storage.  That should be a small shift.

**Comment by tbkka** [comment]
Fixed in #134
