### ISSUE TITLE
Warning in new version

### ISSUE THREAD

**Issue by akhakimzyanov** [apple/swift-protobuf#1280]
Hi, update your library to new version (1.19.1 -> 1.20.0) and see new warning. We are using SPM.
<img width="477" alt="Swift-protobuf" src="https://user-images.githubusercontent.com/5399592/186945231-24c2d9dd-9917-4c99-9888-9ebf381a9113.png">

**Comment by thomasvl** [comment]
What's your host platform, toolchain version, etc.?

**Comment by akhakimzyanov** [comment]
MacOS - 12.5
Xcode - 13.4.1
App only for iOS

<img width="831" alt="Version" src="https://user-images.githubusercontent.com/5399592/186946283-4ca70155-86fb-46e4-ac17-c4ef7f0ef618.png"> - Swift Version default for this Xcode version

**Comment by FranzBusch** [comment]
Ah this is because we adopted a new tools version. Let me open a PR to fix that up.

**Comment by FranzBusch** [comment]
Should be fixed via: https://github.com/apple/swift-protobuf/pull/1281

**Comment by akhakimzyanov** [comment]
Thank you for fast reply and fix!

**Comment by thomasvl** [comment]
1.20.1 should be live for SwiftPM, CocoaPods push happening now.
