### ISSUE TITLE
Data vs. [Uint8] consistency?

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#129]
Unknown fields uses the arrays internally, but we've changed most of the binary serialization apis over to use Data.  Should we be a little more consistent on what we use where?

Data seems to be slightly better in that there could be cases where `func enumerateBytes(_ block: (UnsafeRawPointer, NSRange, UnsafeMutablePointer<ObjCBool>) -> Void)` could be used to avoid forcing the information into a continuous block.

**Comment by tbkka** [comment]
As part of #134, I changed the unknown handling path to use `Data` instead of `[UInt8]`
