### ISSUE TITLE
Use protoc as an artifactbundle with new SPM plugin

### ISSUE THREAD

**Issue by nicolascabaret** [apple/swift-protobuf#1290]
Hi, the latest release exposes a new SPM plugin. After reading documentation, I wonder if it's possible to specify a path to a protoc    artifactbundle in json configuration file ?

**Comment by thomasvl** [comment]
@FranzBusch should this get closed?

**Comment by FranzBusch** [comment]
We can close this I would say.

On a slightly related note, SPM is currently adding support to vend binary artifacts as products in https://github.com/apple/swift-package-manager/pull/5810 which could allow us to create a central package that vends protoc. This could solve this problem for us in the ecosystem.
