### ISSUE TITLE
Determine if the hand-written well-known types are necessary

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#13]
SwiftProtobuf has three hand-written implementations of the types in three of Google's well-known type files: Any, Struct, and Wrappers. These pose difficulties for future maintenance if they must be kept in sync by hand instead of generated.

We need to determine if there are advantages to keeping these hand-written, and if the advantages are significant enough to keep doing it compared to generating them. For example, can any custom behavior just be added via extensions instead?

**Comment by tbkka** [comment]
Wrappers could easily be implemented as a generated base + extensions for the custom JSON behaviors.  Someone recently asked me about "easy starter projects" -- I think that would be one.

I suspect Struct and even Any could also be done that way, though Any might require some adjustments to the rest of the library to expose the right customization points.

**Comment by allevato** [comment]
The `NullValue` enum in `struct.proto` is going to make this a little trickier. Since it's an enum and the `json` property is generated directly on the type, there's no way to have an extension replace it. (Aside: Even if we extract JSON support into separate extensions, we can't introduce our own hand-written extension on the same type without it causing an ambiguity.)

I haven't thought *too* deeply about how to solve this yet, but the options that come to mind feel like hacks:

1. Add a method to `ProtoEnum` like `remapJSONName(_ value: Self, _ name: String)` and have the generated code call it, passing it the JSON string for the case. The default implementation in the protocol extension would just return the string verbatim. A hand-written extension on concrete enum types could then override it and return something else (in this case, `"null"`).
2. Just add a special case for `Google_Protobuf_NullValue` in the JSON serialization code.
3. Other options...?

Any option will pick will likely have a small cost in terms of runtime library size, generated code size, and execution speed. Hopefully they're negligible; in terms of execution speed at least, surely the rest of the string processing will dominate whatever we add.

**Comment by tbkka** [comment]
> Since it's an enum and the json property is generated directly on the type, there's no way to have an extension replace it.

The technique I used to allow overriding generated methods on messages could work here.  In the library, define:
```
extension ProtobufEnum {
   var json: String {return _protoc_generated_json}
}
```

The generator then emits a definition for `_protoc_generated_json` instead of defining `json` directly.  Then we can override `json` in an extension (struct/enum extensions can override protocol extensions).

**Comment by thomasvl** [comment]
@allevato is working on this for Struct.  Once that lands, I've got an idea for how we might be able to do this for Any.

**Comment by thomasvl** [comment]
#387 removed the Any version.  This is now done.

**Comment by allevato** [comment]
🎉 🎉 🎉

**Comment by tbkka** [comment]
Good work!
