### ISSUE TITLE
Relative paths in protoFiles

### ISSUE THREAD

**Issue by Jerry-Carter** [apple/swift-protobuf#1306]
According to [issue 1251](https://github.com/apple/swift-protobuf/pull/1251), "For each invocation you have to pass the relative path from the target source to the proto file."  Relative path appear to only partially work.

Consider the following directory structure.  The proto files will be referenced into three different locations.
- Package.swift
- Sources
- __ Model
- ____ CM1.proto
- __ Client
- ____ CM2.proto
- ____ swift-protobuf-config.json
- ____ Model
- ______ CM3.proto

Protocol files in the target source directory work as expected.
"protoFiles" : ["CM2.proto"]

Protocol files in child directories underneath the target source directory also work.
"protoFiles" : ["Model/CM3.proto"]

Protocol files in parent or sibling locations, however, will fail.
"protoFiles" : ["../Model/CM1.proto"]
Could not make proto path relative: ../Model/CM.proto: No such file or directory

**Comment by FranzBusch** [comment]
Yes this is expected, backtracking is not supported in these file paths. However, I am curious to find out more about your setup here and what we can do to help you. Are `Model` and `Client` different SPM targets in your manifest? If so the right way would be to actually declare the plugin usage for both targets and adding another `swift-protobuf-config.json` in the `Model` directory.

Let me know if that works!

**Comment by Jerry-Carter** [comment]
Thanks of the quick reply.  The plugin is an improvement over manually running protoc.  Previously, we ran a command line program to execute protoc before building the rest of the project.  Now, we only have to 'swift build' once.  I changed the structure of the project to work around this restriction on relative paths.  Easy fix; just unexpected.

From [issue 1251](https://github.com/apple/swift-protobuf/pull/1251), it looks like documentation for the SPM plugin is forthcoming.  Perhaps a one line comment about the types of relative paths would prevent confusion by anyone else.

As you feel appropriate, feel free to close this now or after the SPM plugin documentation is complete.

**Comment by FranzBusch** [comment]
Fixed this up in https://github.com/apple/swift-protobuf/pull/1307 to align the docs of both swift-protobuf and grpc-swift. Thanks for reporting this!

**Comment by thomasvl** [comment]
Should we close this now?

**Comment by FranzBusch** [comment]
Yeah, we can close this
