### ISSUE TITLE
Request for binary encoding/decoding of arrays of Protobuf messages

### ISSUE THREAD

**Issue by cassianomonteiro** [apple/swift-protobuf#1309]
Context:

There is an extension on `Message+JSONArrayAdditions.swift` exposing functions that allow encoding/decoding arrays of Protobuf messages from/to JSON data. That leverages the `decodeRepeatedMessageField` function from the `JSONDecoder`.

Request:

We should have the same support for encoding/decoding arrays to/from binary data. I see that we already have a similar `decodeRepeatedMessageField` in the `BinaryDecoder`

Thanks for the support!

**Comment by thomasvl** [comment]
The binary format for messages doesn't wrap the message in any way, so if you wrote out a list of them, it would end up appears as one message merged together. So if you want to write a series in binary form, you have to use your own framing, like the LengthDelimited format.

**Comment by cassianomonteiro** [comment]
@thomasvl Thanks for the response!

So how should I proceed to decode a network response that represents an array of proto messages? We currently are using JSON serialization, so we decode a response like that using the function `Message.array(fromJSONUTF8Data:options:)`. I was hoping to have something similar when using binary encoding.

**Comment by FranzBusch** [comment]
> So how should I proceed to decode a network response that represents an array of proto messages? We currently are using JSON serialization, so we decode a response like that using the function `Message.array(fromJSONUTF8Data:options:)`. I was hoping to have something similar when using binary encoding.

If you just get a binary blob that is a couple of messages concatenated to each other, then I don't think there really is a way to pull them apart. You can take look [here](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) how gRPC is doing this. It basically boils down to the length prefixed framing that @thomasvl suggested.

**Comment by thomasvl** [comment]
To expand a little, you'll need to go back to the spec to your server, there's no way it can be a binary stream of message without some sorta framing, so you'll need to know what that is to figure out how to parse it.

**Comment by cassianomonteiro** [comment]
@FranzBusch @thomasvl @tbkka Great, thanks for the clarification and ideas!
