### ISSUE TITLE
Generated code for protobuf 2 optionals, becomes non-optional fields in Swift

### ISSUE THREAD

**Issue by erikt** [apple/swift-protobuf#131]
Protobuf 2 optionals generates Swift structs with non-optional fields.

Given this protobuf definition:

    syntax = "proto2";
    message Foo {
        optional int32 field1 = 1;
        optional string field2 = 2;
    }

The generated code is (abbreviated):

    private var _field1: Int32? = nil
    public var field1: Int32 {
        get {return _field1 ?? 0}
        set {_field1 = newValue}
    }
    
    private var _field2: String? = nil
    public var field2: String {
        get {return _field2 ?? ""}
        set {_field2 = newValue}
    }

According to the documentation ([GENERATED_CODE.md](https://github.com/apple/swift-protobuf/blob/master/Documentation/GENERATED_CODE.md)) the generated structure should be:

    struct Foo {
       public var field1: Int32? = nil
       public var field2: String? = nil
    }

**Comment by tbkka** [comment]
The documentation is out-of-date.  I've changed the title of this issue to reflect what we need to fix.

Thanks for pointing that out.

**Comment by erikt** [comment]
After having gone through the commits for the last 14 or so days, I found [Generate non-optional properties for all fields. #102](https://github.com/apple/swift-protobuf/pull/102) and understand this issue much better. 

Is the current solution that I am responsible for checking with `has` and setting the Swift optional? It feels quite weird, having `optional` and `Optional` on both sides, but it is what it is I guess.

**Comment by thomasvl** [comment]
Yup, protos has an optional keyword and Swift has optionals, but the reality is they are different beasts, so they don't really line up.  Protos always have a default value, and in the case of a file that is proto2 syntax, the default doesn't have to be zero.  So the proto defined behavior is that you are always able to fetch the value, and you get the value if it hasn't been explicitly set.  If you really need to check if it it was set, then for proto2 you would check the has* method; but having to check if it is set should not end up being common; most code ends up being happy with the default.

The foot note is stuff like strings and bytes, but even there, it is pretty common to want to treat a zero length explicit value the same as an unset value, so an empty check ends up being more common.

**Comment by tbkka** [comment]
I just updated the documentation you referenced.  Please let us know if this clarifies things.

Of course, if you find any other discrepancies between the documentation and the implementation, please let us know.

**Comment by tbkka** [comment]
I believe the documentation update fixes this.  Closing.
