### ISSUE TITLE
SwiftPM plugin: solve "filename X.pb.swift used twice"

### ISSUE THREAD

**Issue by klundberg** [apple/swift-protobuf#1310]
I'm trying to integrate the swift pm plugin into our setup. We use submodules to easily keep the protobufs up to date with the other teams that use them. When I add the paths to the protobufs in the plugin config and build, I get a "Filename x.pb.swift used twice" error, because some of the proto files in the submodule have the same filenames, even though they're in different directory structures.

Could the plugin either by default or by a config option, use the `--swift_opt=FileNaming=PathToUnderscores`  option when generating code? That would resolve this issue for our use case. I'd prefer to not manually copy/rename files if I can help it as that'll make things more complex than we're willing to allow.

* MacOS 12.6
* Xcode 14.0.1
* Swift 5.7
* Swift Protobuf 1.20.2

**Comment by FranzBusch** [comment]
Just opened https://github.com/apple/swift-protobuf/pull/1312 to provide this option

**Comment by swarupdonepudi** [comment]
thanks a lot for fixing this. is it possible to release a new version to get this fix?
