### ISSUE TITLE
Protobuf blocking xCode indexing with weird error

### ISSUE THREAD

**Issue by vx8** [apple/swift-protobuf#1340]
I'm using xCode 14.1 on macbook pro silicon M1 with Ventura 13.0 (22A380).

I'm using Protobuf 1.20.2 via SPM

I receive the following error in the xcode console while indexing.

```
`Showing All Errors Only

Indexing

/Applications/Xcode-14.1.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -swift-version 5 -I /Applications/Xcode-14.1.0.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI -sdk /Applications/Xcode-14.1.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -package-description-version 5.6.0 -parse-as-library -I /Applications/Xcode-14.1.0.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/PluginAPI /Users/me/Library/Developer/Xcode/DerivedData/MyProject-etyfxtttxpmavldwvibjxmvtbbhn/SourcePackages/checkouts/swift-protobuf/Plugins/SwiftProtobufPlugin/plugin.swift -index-file -index-file-path /Users/me/Library/Developer/Xcode/DerivedData/MyProject-etyfxtttxpmavldwvibjxmvtbbhn/SourcePackages/checkouts/swift-protobuf/Plugins/SwiftProtobufPlugin/plugin.swift -disable-batch-mode -o /Users/me/Library/Developer/Xcode/DerivedData/MyProject-etyfxtttxpmavldwvibjxmvtbbhn/SourcePackages/checkouts/swift-protobuf/Plugins/SwiftProtobufPlugin/plugin.swift.o -index-store-path /Users/me/Library/Developer/Xcode/DerivedData/MyProject-etyfxtttxpmavldwvibjxmvtbbhn/Index.noindex/DataStore

error: module name "plugin.swift" is not a valid identifier; use -module-name flag to specify an alternate name
error: Command failed with exit code 1`
```

This leads to xCode not linting code, jump to definition not working and other minor indexing issues.

Any help?

Thank you

**Comment by tbkka** [comment]
@FranzBusch @gjcairo Any ideas what's going on here?

**Comment by FranzBusch** [comment]
@vx8 can you expand a bit more about your local setup. How does your `Package.swift` file look like, how does your json config file look like? Are you able to create a smaller reproducer package that you can maybe share?

**Comment by vx8** [comment]
Hi @FranzBusch . The project itself is a b2b application with several SPM dependencies. SwiftProtoBuf gets imported as dependency from Firebase. Here a quick look at how my resolved packages look like. I'll try to replicate the issue in a smaller demo setup but to be honest I'm not sure it will happen on a fresh created project.

![Screenshot 2022-11-09 at 9 15 51 AM](https://user-images.githubusercontent.com/23518520/200775882-8b6b27b3-0798-4474-841b-ad3ff7fe26bb.jpg)

**Comment by djs-code** [comment]
This seems to be an Xcode-proper issue.  We have a custom SPM plugin that we use for our own codegen in Xcode 14.2, and get the same error messages when the `com.apple.dt.Xcode IDEIndexShowLog` is set to `YES`.

@FranzBusch Do you happen to know if this is a known issue within Apple?

**Comment by tbkka** [comment]
If you are still seeing this issue with the newest Xcode 15 Beta 1, please file a Feedback report with Apple at https://feedbackassistant.apple.com 

Although some of the folks here do work for Apple, Apple is a very big company and you can't assume that anyone here has any connection with the Xcode product.
