### ISSUE TITLE
The 1.x branch can't build protobuf on the image for 4.2.4 Swift

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#1355]
As seen on the Checks for #1354, upstream protobuf now needs a newer compiler than what we have on the CI images. So either we need to find a way to update CI on the 1_x_release_branch or we shut off the tests there that require building protobuf.

**Comment by Lukasa** [comment]
TBH I'd stop trying to build protobuf. Bringing in newer compilers is certainly possible but it's a real pain in the neck. IMO there's little point CI-ing a flow we don't think our users will do.

**Comment by thomasvl** [comment]
Looks like the 5.0 & 5.1 swift images also have too old of a gcc - https://github.com/apple/swift-protobuf/actions/runs/3942305760/jobs/6745793533

**Comment by thomasvl** [comment]
> TBH I'd stop trying to build protobuf. Bringing in newer compilers is certainly possible but it's a real pain in the neck. IMO there's little point CI-ing a flow we don't think our users will do.

I guess the "catch" is we need a `protoc` binary and a `conformance-test-runner` binary for some of you testing.  We could switch to released versions of `protoc` for some of the tests, but I don't think we want to give up on the conformance tests in general.

Even if the `conformance-test-runner` were included in releases, I sorta like the fact that we also run those again their `main` to catch new tests before a release is cut.

**Comment by tbkka** [comment]
I agree with Thomas that building the conformance tests from source (at a minimum) is helpful.

I'm fine dropping 5.0 and 5.1 tests:  We've always said "one full major version", but I think we should really amend that to "at least one full year back."  Those used to be approximately the same when Swift had a new major version every year, but that pattern has shifted.

**Comment by thomasvl** [comment]
> I'm fine dropping 5.0 and 5.1 tests: We've always said "one full major version", but I think we should really amend that to "at least one full year back." Those used to be approximately the same when Swift had a new major version every year, but that pattern has shifted.

@tbkka do you want to send out a PR for tweaking the wording on the relevant pages?

I'll look at changing up the workflows to split out things the conformance tests don't have to exist at every swift version tested.

**Comment by thomasvl** [comment]
And the _protobuf-compiler_ package seems to be [pretty old](https://packages.ubuntu.com/focal/protobuf-compiler)…, so `apt-get -y protobuf-compiler` likely isn't something we want.
