### ISSUE TITLE
cant compile "$ protoc --swift_out=. myFileName.proto"

### ISSUE THREAD

**Issue by avaan** [apple/swift-protobuf#136]
I followed all the steps but facing below problem when I compile "$ protoc --swift_out=. myFileName.proto" on my mac

protoc-gen-swift: program not found or is not executable
--swift_out: protoc-gen-swift: Plugin failed with status code 1.

my swift version is as follows,

swift build --version
Apple Swift Package Manager - Swift 3.0.1 (swiftpm-11504)
swift --version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)

**Comment by thomasvl** [comment]
I'd suggest going back and double checking your setup.  The error output you quote appears to be the problem:

> protoc-gen-swift: program not found or is not executable

So that would imply you didn't install the plugin on your path.  If you try to just run it `protoc-gen-swift --version`, what happens?

**Comment by avaan** [comment]
@thomasvl thanks for your reply 

After coping the file protoc-gen-swift to my path I run  protoc-gen-swift --version  
I got below error
-bash: protoc-gen-swift: command not found

when I double click protoc-gen-swift file it opened in terminal and I run protoc-gen-swift --version
i got below logs,


!Internal Error: malformedProtobuflogout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I am not sure what i am doing wrong here.

**Comment by thomasvl** [comment]
It sounds like it isn't really copied on to your path.  Where did you copy it?  And what does `echo $PATH` report?

**Comment by avaan** [comment]
I have created new folder with my *.proto file in it. And then I copied protoc-gen-swift file into this new folder. 

echo $PATH
/Applications/XAMPP/xamppfiles/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

**Comment by thomasvl** [comment]
Is that folder listed on your $PATH?

**Comment by avaan** [comment]
@thomasvl i realized what mistake i was doing. Thanks for your help.
