### ISSUE TITLE
While building for tvOS, no library for this platform was found

### ISSUE THREAD

**Issue by akshayiosdeveloper** [apple/swift-protobuf#1363]
I have integrated two third party libraries into the tvOS project. I have no clue why I am getting this error.

My Xcode version is 14.0.1.
![1](https://user-images.githubusercontent.com/7240581/213104622-0d92e6c4-74e6-42fb-b74e-558fa7c13412.jpg)
![2](https://user-images.githubusercontent.com/7240581/213104637-89f8340f-0521-455f-a157-a567907077cb.jpg)

**Comment by Lukasa** [comment]
This seems like a Carthage issue: I recommend asking the developers of Carthage to assist you.
