### ISSUE TITLE
 swift protobuf is not working with Carthage 

### ISSUE THREAD

**Issue by akshayiosdeveloper** [apple/swift-protobuf#1372]
I am facing issue while downloading swift protobuff through Carthage 

Xcode 12.4
Build version 12D4e
swift-protobuf at "1.6.0"

**Comment by thomasvl** [comment]
1.6.0 is a pretty old release.

The screen show doesn't actually show anything about what failed, but since it seems specific to Carthage, you might want to see if there are general Carthage places for help.

**Comment by tbkka** [comment]
You should also look at the xcodebuild log as described in the last line of your screen shot.  That may have more details about what went wrong.

**Comment by akshayiosdeveloper** [comment]
I have investigated the log file .

<img width="1370" alt="Screenshot 2023-01-27 at 1 24 31 PM" src="https://user-images.githubusercontent.com/7240581/215051830-1388fc61-76bd-4bdb-ac32-d4a9d590f40b.png">

**Comment by thomasvl** [comment]
That's likely because you are using such and old release.  https://github.com/apple/swift-protobuf/commit/03c8bef37f91f52fcba3b6e5d8df1f027397b779 shows a changed to the setting back to 1.8.0, but I'd strongly suggest you move up much further to get bug fixes, etc.
