### ISSUE TITLE
Binary decoding likely has 32bit issues with large data sizes

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#1377]
Like what #1375 fixed, it looks like we've got a few cases (`getFieldBodyBytes(count:)`, `consume(length:)`, ...) where because the internals of the BinaryDecoder use `Int` we could have failures in a 32bit build.

**Comment by thomasvl** [comment]
fyi - The C++ upstream code seem to use `INT_MAX` in some cased to catch limits, but it seems like that value will change depending on a build being for a 64 or 32 bit platform.  And the new https://protobuf.dev/programming-guides/encoding/#cheat-sheet section calls out some _2GB_ limits on specific things.

**Comment by thomasvl** [comment]
Correction on that comment - `int` (and `INT_MAX`) is still 32bit on most 64bit systems: https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models

**Comment by tbkka** [comment]
If there's a 2GB limit, we should still write it out as `0xffffffff` or similar.

**Comment by thomasvl** [comment]
I'm going to go ahead and close this, I doing another pass, and don't immediately see issues, so at this point I'd suggest we treat them as bugs if found instead of keeping this open longer term without any clear next steps.
