### ISSUE TITLE
Enum case stemming can result in invalid Swift

### ISSUE THREAD

**Issue by dpassage** [apple/swift-protobuf#138]
I like how `protoc-gen-swift` generates enum cases which are "stemmed", meaning that you remove the first word if the case name if it's the same as the enum name.

However, if I have a proto file which looks like this:

```
enum Clock {
    CLOCK_24_HOUR = 1;
    CLOCK_12_HOUR = 2;
}
```

(which I in fact do in my project), then I get an output file which looks like this:

```swift
public enum Clock: ProtobufEnum {
  public typealias RawValue = Int
  case 24Hour // = 1
  case 12Hour // = 2
  //...
```

...which is not valid Swift.

I think the right answer is to see if any of the stemmed case names are invalid Swift, and then not stem any of them. Working on a PR but wanted to file this to get it on your radar.

**Comment by allevato** [comment]
I think your proposed solution is correct; if the stemming causes *any* of the cases to be an invalid case name, keep the stem on *all* of them for consistency.

We're happy to review a PR for the fix! Please make sure to add some unit tests to the suite that demonstrate the problem; a small enum like the one you posted above and test case that references the generated cases should be sufficient.

**Comment by dpassage** [comment]
Great, I'll likely get to it by this weekend.

On the topic - is there any information on what constitutes a valid identifier in a `.proto` file? I couldn't find anything in Google's documentation, but haven't dived into the source yet.

**Comment by tbkka** [comment]
The precise syntax is defined at:
  https://developers.google.com/protocol-buffers/docs/reference/proto2-spec
and
  https://developers.google.com/protocol-buffers/docs/reference/proto3-spec

In particular:
```
 ident =  letter { letter | decimalDigit | "_" }
```

**Comment by dpassage** [comment]
Wow, don't know how I missed that. :) Thanks!

**Comment by tbkka** [comment]
I suggest adding a function to the String utilities called something like `IsValidSwiftIdentifier` that checks the obvious (valid symbols, starts with a valid symbol, etc) and also returns `false` for reserved words, special symbols like `_` (single underscore), etc.  Then the logic would be something like "select a prefix but only strip it if the results are all valid Swift identifiers".
