### ISSUE TITLE
Move Any support out of ProtobufMessage

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#14]
A minor nit, but the support for parsing/serializing `Any` (that is, `google.protobuf.Any`, not Swift `Any`) messages ought to be moved out of the core `ProtobufMessage` protocol and into a separate extension that contains that and other `Any`-related functionality.

**Comment by thomasvl** [comment]
@allevato - Should this get rolled in with #13? Does it need to happy by the 1.0 release?

**Comment by allevato** [comment]
This was originally just about code organization, but I'd need to take a closer look to see if moving `Any` support into an extension of `ProtobufMessage` would cause problems (the implementations become non-overridable, so if any of the specific message types customize them, that wouldn't work anymore).

It's probably fine to leave out of 1.0, given the priorities of everything else.

**Comment by thomasvl** [comment]
Oops, we had another bug for this also, but ti seems to be done now.
