### ISSUE TITLE
The generated code uses 2 spaces for indentation instead of the standard 4

### ISSUE THREAD

**Issue by gmosx** [apple/swift-protobuf#141]
AFAIK, the standard indentation size for Swift source code is **4** spaces.
The code-generator should honour this convention.

**Comment by allevato** [comment]
There is no "standard" indentation size for Swift, in the sense that there is no single official style guide for formatting conventions.

In the absence of that, Swift's own [standard library](https://github.com/apple/swift/tree/master/stdlib/public/core) serves as a good source of truth/inspiration. Two space indentation with 80 character line limits are the convention there, so we've adopted that for this project.

More information about the style we use in this project (excepting the older source, which will eventually be reformatted) can be found [here](https://github.com/apple/swift-protobuf/blob/master/Documentation/STYLE_GUIDELINES.md).

**Comment by gmosx** [comment]
On the other hand, The Swift Programming Language book uses 4 spaces for indentation. 
4 spaces are also the default setting for Xcode.

What about providing an option to choose the indentation size of the generated code? That would please everyone.

**Comment by allevato** [comment]
Why does the indentation of generated code matter? It should never be edited so it doesn't need to be consistent with the rest of the IDE's settings, and generated code should be excluded from any pre-commit linting that would produce false warnings compared to the rest of the project.

I'd be against adding more options for something that doesn't *need* to be controlled.

**Comment by gmosx** [comment]
I often Cmd-click into the generated code (e.g. to see the fields of the class) and it's annoying to see code formatted differently. Anyway, it's not a big deal, I guess.

**Comment by tbkka** [comment]
I'm pretty strongly opposed to an option.  That's just more stuff to test with no real gain in functionality.

But I'm also a big believer in following code style.  I would personally be happy to consider a Pull Request that brought our indentation more into line with emerging conventions.  I suspect this is a very minor change...

**Comment by thomasvl** [comment]
I'm confused, you've got on standard within the Swift standard library and another in the Swift book.  Do we really bounce back and forth between standard?  Why not just stick with what the Swift standard library is doing since that would appear to be closer to the canonical that the Swift team does/wants?

**Comment by allevato** [comment]
I disagree with changing this for a few reasons.

* Generated code does not need to conform to the same style as other code in the same project. Doing that across the board would be an impossibility, anyway.
* Trying to track "emerging conventions" would be a challenge. Who defines which ones win out? Why should we take exhibit A (the book) over exhibit B (real Swift code in the language's own project)?
* Given the size of our generated files, adding two spaces for every indentation level is wasting disk space for no benefit.

**Comment by gmosx** [comment]
I was really amazed to see the standard library using 2 spaces. I don't think I have seen any other Swift code that uses 2 spaces before. 

Like @tbkka I also believe in following code style, I guess I should also follow the SL conventions.

**Comment by gmosx** [comment]
Interestingly, many files in stdlib use 4 spaces, e.g.

https://github.com/apple/swift/blob/master/stdlib/public/SDK/Foundation/Data.swift
https://github.com/apple/swift/blob/master/stdlib/public/SDK/Foundation/Decimal.swift

etc..

**Comment by tbkka** [comment]
According to folks I've talked to within Apple, the Swift Standard Library sources should _not_ be considered typical in this regard.  The library sources inherited the two-space indent and the 80-column limit from the LLVM project (on which the Swift compiler code is based).

Apple has standardized on four-space indents for Swift in Xcode, sample code, documentation, etc.

**Comment by allevato** [comment]
That's a fair point.

At the same time, with generated code being potentially so large, 4 spaces instead of 2 is more or less just wasting disk space when 2 spaces is just as legible as 4.

**Comment by thomasvl** [comment]
For the moment, we're following the projects [STYLE_GUIDELINES.md](https://github.com/apple/swift-protobuf/blob/master/Documentation/STYLE_GUIDELINES.md).  I personally think it makes very little sense to say generated code should be one style and the code within this library should be another.  If there's something to point to to revisit what we says in the STYLE_GUIDELINES, then that's fine; lets do that instead of this limited scope.
