### ISSUE TITLE
Module 'SwiftProtobuf' was not compiled with library evolution support; using it means binary compatibility for '(my framework)' can't be guaranteed

### ISSUE THREAD

**Issue by tkafka** [apple/swift-protobuf#1416]
I get the following error during build on Xcode 15 - I am using SwiftProtobuf in my custom framework (with shared app code). Is it possible to build SwiftProtobuf in a binary compatible way?

Please be sure to include:
* what OS you are developing on (Linux or macOS, including the version): 13.4.1
* for macOS, what version of Xcode you are using (`xcodebuild -version`): 15.0 beta 2
* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.): 5.9
* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.): 1.22.0 release
* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.:
```
Module 'SwiftProtobuf' was not compiled with library evolution support; using it means binary compatibility for '(my framework)' can't be guaranteed
```

**Comment by Lukasa** [comment]
Please see #1101 for discussion of library evolution mode.

**Comment by Lukasa** [comment]
The TL;DR here is that Protobuf does not support a stable ABI today. To use it in this way, you can use it with `@_implementationOnly` and statically link it.
