### ISSUE TITLE
Markdown shell commands copy usability in docs

### ISSUE THREAD

**Issue by kriswuollett** [apple/swift-protobuf#1435]
The markdown shell code command blocks should not include the shell `$` prompt prefix when they are meant to be run by the developer and not showing an example shell session. This is a really minor issue, but can be one of those DevEx irritations because GitHub's copy button will also copy the `$` which needs to be manually removed when pasting into a terminal.

Example here in `swift-protobuf`:

https://github.com/apple/swift-protobuf/blob/37a0e0b9672ec18057ae7f4674752e2a9898b0eb/README.md?plain=1#L144-L148

Which gets rendered like:

These blocks get rendered like:

<img width="400" alt="image" src="https://github.com/apple/swift-protobuf/assets/1834192/4d417b40-656d-4c40-b74b-3fdbd35e765d">

Easier to use example in [`protocolbuffers/protobuf`](https://github.com/protocolbuffers/protobuf/blob/161989080b77a601e040a33ade3570c9bc85cada/src/README.md?plain=1#L24-L27) which could be used as the suggested way to update the blocks:

```
On Ubuntu/Debian, for example, you can install them with:

    sudo apt-get install g++ git bazel
```

Which looks like:

<img width="491" alt="image" src="https://github.com/apple/swift-protobuf/assets/1834192/5a920cea-0156-4b59-a5a4-dcbc05fec406">

**Comment by tbkka** [comment]
Please take a look at #1436 and let me know if this seems right.

**Comment by kriswuollett** [comment]
> Please take a look at #1436 and let me know if this seems right.

Cool, thanks! Yeah, when examining a sample through a link like https://github.com/apple/swift-protobuf/blob/db717738b444ecc28899c4350f2f51379ae8d62d/Documentation/CONFORMANCE_TESTS.md it looks good.
