### ISSUE TITLE
Handling of length delimiters

### ISSUE THREAD

**Issue by emanuele-em** [apple/swift-protobuf#1441]
It would be useful to have functions to handle length delimiters, I am trying to read a buffer via unix pipe (without EOF) and I would like to be able to read the fixed length prefix that contains the length of the rest of the buffer

Protobuf docs:
[Length-Delimited Records](https://protobuf.dev/programming-guides/encoding/#length-types)

For example on Rust there are the following function to handle with it:
[decode_length_delimiter](https://docs.rs/prost/latest/prost/fn.decode_length_delimiter.html)
[encode_length_delimiter](https://docs.rs/prost/latest/prost/fn.encode_length_delimiter.html)
[length_delimiter_len](https://docs.rs/prost/latest/prost/fn.length_delimiter_len.html)

Info:

* MacOS sonoma

* Xcode 15

* Swift 5

* SwiftProtobuf 1.22.0

Thank you!

**Comment by thomasvl** [comment]
The 1.x release already have something via `InputStream` - https://github.com/apple/swift-protobuf/blob/1.22.1/Sources/SwiftProtobuf/BinaryDelimited.swift

Sadly, `InputStream` likes to lie about available bytes/eof, so it isn't as smooth as one would hope, but it's something.

There's also a [PR in flight for `main`](https://github.com/apple/swift-protobuf/pull/1434) to async sequence support, but that won't appear in a release until we make a 2.0.
