### ISSUE TITLE
SwiftData @Model annotation support

### ISSUE THREAD

**Issue by tmc** [apple/swift-protobuf#1458]
Thoughts on some optional SwiftData support?

**Comment by tbkka** [comment]
I have no idea what that would entail.  Care to elaborate?  What exactly are you trying to achieve?

I think the biggest concern is that SwiftProtobuf is intended to be cross-platform and currently SwiftData is only available on Apple platforms.  That doesn't rule out the idea, but does constrain what approaches we can consider.
