### ISSUE TITLE
See about removing unneeded JSON support from Extensions

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#146]
Spun out of comments on https://github.com/apple/swift-protobuf/pull/145 -

The Extensions vars created include information for JSON support.  But the spec for [JSON](https://developers.google.com/protocol-buffers/docs/proto3#json) doesn't seem to include extensions.  So the extra support for JSON on extensions like should get removed.

_Note:_ a message in a proto3 syntax file can have a field defined in a proto2 syntax file, so JSON support is needed for proto2, it just seems like extensions aren't expected to survive.

**Comment by tbkka** [comment]
@thomasvl:  Is this done?

I see no JSON specifics in the generated code (so at a minimum, I think `generator API` is no longer relevant).

I don't see any JSON support for Extensions in the library, either, but maybe I missed something?

**Comment by thomasvl** [comment]
I honestly don't know.  I opened this purely on your comment on #145 -

> I implemented full JSON support for all of proto2 (including extensions, groups, etc) just to see what it would require. Turns out to be pretty straightforward, actually. We should probably rip that back out again to avoid confusion.

But I didn't go dig to see what it actually was.

**Comment by tbkka** [comment]
Okay.  Looks like the last part of this was finished in d1dd91e5, so I'll close it.
