### ISSUE TITLE
Replace debugDescription with text format

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#148]
Once we have text format implemented, the custom `debugDescription` implementation (that uses Swift field names instead of proto field names) feels redundant. If it's solely for debugging purposes, text format would suit that just as well, which would let us strip out a number of strings (all `swiftFieldName`s) entirely from our code.

The only other place where `swiftFieldName` is used I believe is for the custom mirror. Since we're already customizing the mirror representation, I don't think there would be any harm in using the text names for the fields there either instead of the Swift names. Users will see the proto names in the debugger instead of the Swift names, but I don't think that would be a major source of confusion. Certainly not worth having to either (1) keep storing the Swift names, or (2) reïmplement in the runtime the transformation done by the generator (which would have to include all the reserved word checking, too).

So, we can do this in two stages:
(1) Get rid of `swiftFieldName` and replace its uses with `protoFieldName`
(2) Once text format is implemented, update the `debugDescription` property to just do a text format serialization and delete the custom `ProtobufDebugDescriptionVisitor`.

**Comment by tbkka** [comment]
In another thread, we discussed simply removing the custom mirror entirely.  I would rather do that than change the mirror to use proto names (I think it would actually be quite confusing to users to have the names they see in their source editor be different from those showing in the debugger).

Text serialization/deserialization is in the works, but still has a ways to go.

**Comment by thomasvl** [comment]
@tbkka should we open an issue to drop mirror then and revisit it later?  Just so it isn't in the initial release locking us into it?

**Comment by tbkka** [comment]
Done.  Although I think we're locked in either way:  If we don't have a custom mirror, then people will be relying on the behavior of the generic mirror.

**Comment by thomasvl** [comment]
Done and all supporting bits gone.
