### ISSUE TITLE
CircleCI failed to build due to "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"

### ISSUE THREAD

**Issue by abdallahnh** [apple/swift-protobuf#1481]
I'm using CircleCi for our CI/CD process 
I'm using Xcode 14.2.0

The error is: 
[MT] IDEFileReferenceDebug: [Load] <IDESwiftPackageCore.IDESwiftPackageSpecialFolderFileReference, 0x600005462000: name:Docs.docc path:group:Docs.docc> Failed to load container at path: /Users/distiller/Library/Developer/Xcode/DerivedData/ttt-hemyuicdhohkzffyarqsgccgekwu/SourcePackages/checkouts/swift-protobuf/Sources/protoc-gen-swift/Docs.docc, Error: Error Domain=com.apple.dt.IDEContainerErrorDomain Code=6 "Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder"." UserInfo={NSLocalizedDescription=Cannot open "Docs.docc" as a "Swift Package Folder" because it is already open as a "Folder".}

**Comment by spassky1** [comment]
I have been researching the exact same problem and no solution has worked. we have the same problem since updated to xcode 14 on the azure cicd

**Comment by thomasvl** [comment]
I'm not sure that anyone working on this project has much experience with CircleCi.  If there is something we can accepts as a PR to help with this, we're probably open to it, but you'll likely need to do some more investigation and/or asking for help in locations where folks might have more understanding of CircleCi.

**Comment by abdallahnh** [comment]
@thomasvl This was happening too with different libraries 
There is an issue with xcodebuild and .docc folders in package Sources/. It is the Apple-recommended way to set up DocC for Swift packages. To fix you should temporarily remove .docc folders from Swift packages.

**Comment by tbkka** [comment]
I believe that error message may be misleading.  Is there another error somewhere else in your log?  (Is it possible to upgrade to Xcode 15?  That misleading message might be fixed there.)

**Comment by thomasvl** [comment]
@abdallahnh do you have a reference to those other issues and the suggested fix?  Sounds like there isn't something for this project to do, but having a reference on this issues might make the "solution" easier to find.

**Comment by abdallahnh** [comment]
I'll close this ticket because Circle-ci fixed the problem from there side.
