### ISSUE TITLE
BinaryEncodingOptions.swift is not included in all targets

### ISSUE THREAD

**Issue by wangjiejacques** [apple/swift-protobuf#1493]
Please be sure to include:

* what OS you are developing on (Linux or macOS, including the version)
macOS

* for macOS, what version of Xcode you are using (`xcodebuild -version`)
Xcode 15.0

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
1.25.0

* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.
<img width="371" alt="image" src="https://github.com/apple/swift-protobuf/assets/2981971/6e472a70-af96-4a55-a860-5dc1ce9b7ca9">

When we open the project with `SwiftProtobuf.xcodeproj`, the file `BinaryEncodingOptions.swift` is not included in the project.

**Comment by thomasvl** [comment]
Sorry about that, just pushed out 1.25.1 with the fixed up Xcode project.

You might want to consider moving to Xcode's native SwiftPM integration instead.
