### ISSUE TITLE
Explore different binary encoding/decoding designs

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#15]
At the time of this writing, binary encoding/decoding of test messages with different numbers/types of fields is quite a bit slower than bridging to messages generated in Objective-C—about 10–25x slower under some tests.

The use of the visitor pattern in binary coding may be a significant bottleneck here; the Swift compiler may have difficulty optimizing it due to the large amount of indirection through various protocols.

Since binary coding ought to be as fast as possible, it would be prudent to explore other techniques that perhaps use more imperative/sequential operations with less generality, even if it means generating larger methods to read from/write to binary data. The visitor pattern could still be used for things like text/JSON serialization, where the string processing is likely to dominate the cost of the visitor indirection anyway.

**Comment by jcanizales** [comment]
I wonder if making the specific visitor type in `ProtobufTraversable` a generic would led the compiler to generate specializations of the traversal for that specific visitor. That would be the ideal solution in C++, but I'm not so familiar with Swift generics to tell for sure.

I do notice that `ProtobufVisitor` already defines the specific visited message as a generic (in `visitSingularMessageField<M: ProtobufMessage>(value: M, ...)`, which would be the other half of the solution.

**Comment by jcanizales** [comment]
@allevato do you happen to have automated benchmarks against ObjC protos that could be added to this repo? They would make for a good test of changes in the codec.

**Comment by allevato** [comment]
@jcanizales I'm hoping to port the harness that I merged in here to Objective-C so that we have a way to easily get comparative metrics, and check it into a personal fork of google/protobuf (so that it doesn't clutter up the official repo, but it's still publicly accessible).

On the broader topic, #43 adds some significant performance improvements that should bring the Swift implementation a lot closer to Objective-C. How much closer still hasn't been measured yet, but it makes me a bit more hopeful than I was originally that we could keep the visitor pattern for binary serialization too. This would be nice because it's less code to generate, and has some nice benefits w.r.t. keeping runtime implementation details internal.

**Comment by thomasvl** [comment]
@tbkka are you taking this as part of your perf work?

@allevato was there more we're wanting to do here?

Just wondering if we're close to closing this out and doing more detailed issues for future work.

**Comment by allevato** [comment]
This is probably obsolete now. It was borne out of my fear that the indirection of the visitor pattern would be a performance bottleneck for the binary case, but it sounds like @tbkka has been getting some good numbers out of his recent PRs.

**Comment by thomasvl** [comment]
Ok, closing out.

**Comment by tbkka** [comment]
Actually... this is the perfect explanation for my current WIP, which is exploring a couple of (conceptually) small tweaks to the decoder design.

**Comment by tbkka** [comment]
PR #243 should cover this for the decoder side.

I plan to start digging into the encoder/visitor performance next.

**Comment by tbkka** [comment]
Recent PRs overhauled the encoder/visitor architecture to address API-level performance issues.
