### ISSUE TITLE
"error: no such module 'SwiftProtobuf'" when using xcodebuild (but not Build in Xcode itself)

### ISSUE THREAD

**Issue by keynmol** [apple/swift-protobuf#1502]
First thing's first - I've never done any MacOS development and never used Xcode or SwiftPM. So if you think I'm missing something obvious - please spell it out, my current attempt is held together entirely by silly mistakes and I could make more.

Situation in brief:

- I added SwiftProtobuf dependency in my Xcode MacOS project 
- Not using the plugin, but using the runtime types (see below)
- The **Build** from Xcode itself succeeds, but running `xcodebuild` complains that it can't find SwiftProtobuf module
- The app is working at runtime as intended, so it seems that the compilation configuration is incorrect, but linking is okay

Exact error:

```
.../Interop.swift:10:8: error: no such module 'SwiftProtobuf'
import SwiftProtobuf
       ^

** BUILD FAILED **
```

When running `xcodebuild -project Scala-Native-SwiftUI.xcodeproj/ -arch arm64`

`Interop.swift` just works with SwiftProtobuf messages generically:

```swift
    static func writeToWire<T: SwiftProtobuf.Message, R: SwiftProtobuf.Message>(msg: T) throws -> R? {
        let contents = try msg.serializedData()
        
        return   try contents.withUnsafeBytes { (bytes: UnsafePointer<CChar>) in
            let ba = ByteArray(size: Int32(contents.count), bytes: bytes);
            return try withUnsafePointer(to: ba, { bap in
...
```

I have the package dependency added: 
![CleanShot 2023-11-11 at 17 46 20@2x](https://github.com/apple/swift-protobuf/assets/1052965/aa80f57b-428e-4fb8-94b8-a9208c79bdf5)

I have it in the "Link binary": 
![CleanShot 2023-11-11 at 17 46 52@2x](https://github.com/apple/swift-protobuf/assets/1052965/77d637ea-8cb9-49be-9e78-dc824ce2371a)

I even added it to Target dependencies (no idea what these are) 
![CleanShot 2023-11-11 at 17 47 06@2x](https://github.com/apple/swift-protobuf/assets/1052965/e990f7ef-aea8-4e99-bff1-acc2168c2e4e)

I can see it in Frameworks, Libraries, and Embedded content: 
![CleanShot 2023-11-11 at 17 47 28@2x](https://github.com/apple/swift-protobuf/assets/1052965/6fd863e9-8108-4e54-bb2f-d1cbc01517a1)

Please let me know if I can provide any more information

- MacOS Ventura 13.6
- Xcode 15.0.1
- SwiftProtobuf 1.25.1

**Comment by natikgadzhi** [comment]
> The Build from Xcode itself succeeds, but running xcodebuild complains that it can't find SwiftProtobuf module

You _could_ also try building with Swift Package Manager in CLI, i.e. `swift build` — but you'd need to make a `Package.swift` and explicitly define binary target for Scala's xcframework and use that as a dependency.

I haven't personally tinkered with using xcframeworks in `Package.swift`, or with debugging the flags / differences between `xcodebuild` and building in Xcode GUI, but I'm happy to help, if you're open to sharing the example project.

**Comment by thomasvl** [comment]
I'm not really sure there is enough for folks to help out; you best bet might be to include a sample project so anyone could see the real setup.

One thing I do notice in the screen shots is you might be things to like protoc-gen-swift and SwiftProtobufPluginLibrary, there should be no need to link those, only SwiftProtobuf is needed for runtime support.
