### ISSUE TITLE
Insecure methods `malloc` and `memcpy`  used

### ISSUE THREAD

**Issue by patrickdunsheecubic** [apple/swift-protobuf#1516]
In a recent audit, testers flagged use of insecure function memcpy and malloc. We were recommended to use `memcpy_s` and `calloc` as alternatives, and wanted to pass that recommendation to you all to improve security of the library.

* what OS you are developing on (Linux or macOS, including the version)
iOS

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
  for Linux, what version of Swift (`swift --version`)
15.0.1

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
5

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
1.24.0

* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.

* lastly, if it all possible, provide a snippet of `.proto` and/or source
  that shows the problem.

Thank you for the consideration!

**Comment by tbkka** [comment]
I found two stray remaining `memcpy` for copying bits of a UInt32/64 to a Float/Double.   #1517 replaces those with Float/Double(bitPattern:), which is more explicit and likely even faster.

**Comment by patrickdunsheecubic** [comment]
Apologies, I erroneously flagged the `malloc` function that is actually in a separate dependency, and the `nanopb` dependency doesn't actually use the `malloc` function as it first appeared. Thanks for your quick turnaround on `memcpy` though!
