### ISSUE TITLE
How to convert to Google_Protobuf_Any  to normal json in Swift

### ISSUE THREAD

**Issue by shinedlc** [apple/swift-protobuf#1528]
I tried to import or export an any structure into or out of json, which is not in the expected format, something like @type in it，Maybe I don't understand. I hope help. Some people may say that it would be nice to replace the json content, but the problem will also lie in serializData(). It is too inconvenient to replace it.I'm just trying to figure out how to transfer json or data in and out to the proto model. thx!!!
1、proto file

```
syntax = "proto3";
message Contract {
    enum ContractType {
        AccountCreateContract = 0;
        TransferContract = 1;
        TransferAssetContract = 2;
    }
    ContractType type = 1;
    google.protobuf.Any parameter = 2;
}
```

2、my json(There are some @type fields generated by Google_Protobuf_Any, but I don‘t need.)

```
"contract": [
    {
      "type": "TransferContract",
      "parameter": {
        "@type": "type.googleapis.com/TW.Tron.Proto.TransferContract",
        "ownerAddress": "TJRyWwFs9wTFGZg3JbrVriFbNfCug5tDeC",
        "toAddress": "THTR75o8xXAgCTQqpiot2AFRAjvW1tSbVV",
        "amount": "2000000"
      }
    }
}
```

3、expected json(I want the type_url and value, Because that's the universal format.)

```
"contract": [
        {
            "type": "TransferContract",
            "parameter": {
                "type_url": "type.googleapis.com/protocol.TransferContract",
                "value": {
                    "amount": "2000000",
                    "ownerAddress": "415cd0fb0ab3ce40f3051414c604b27756e69e43dQ==",
                    "toAddress": "41521ea197907927725ef36d70f25f850d1659c7cw=="
                }
            }
        }
```

**Comment by thomasvl** [comment]
The protobuf spec spell out specific JSON encoding: https://protobuf.dev/programming-guides/proto3/#json, so that's what the library does.  So you might actually need something other than protobuf if you want different JSON encodings.

**Comment by tbkka** [comment]
As Thomas pointed out, this is not a system for producing a specific JSON format.  You can get closer to what you want with a schema like this:
```
syntax = "proto3";
message Contract {
    enum ContractType {
        AccountCreateContract = 0;
        TransferContract = 1;
        TransferAssetContract = 2;
    }
    ContractType type = 1;
    Parameter parameter = 2;
}

message Parameter {
    string type_url = 1;
    google.protobuf.any value = 2;
}
```

You'll have to set `type_url` yourself, but you can then get this JSON output:
```
"contract": [
    {
      "type": "TransferContract",
      "parameter": {
        "type_url": "type.googleapis.com/TW.Tron.Proto.TransferContract",
        "value": {
          "@type": "type.googleapis.com/TW.Tron.Proto.TransferContract",
          "ownerAddress": "TJRyWwFs9wTFGZg3JbrVriFbNfCug5tDeC",
          "toAddress": "THTR75o8xXAgCTQqpiot2AFRAjvW1tSbVV",
          "amount": "2000000"
        }
      }
    }
}
```
There's no way in SwiftProtobuf to suppress the `@type` parameter on an `Any` field.  If that's a problem, you can use the [JSONSerialization type from Foundation](https://developer.apple.com/swift/blog/?id=37) to decode the JSON, modify it, and then re-encode it.
