### ISSUE TITLE
xcprivacy file for this package

### ISSUE THREAD

**Issue by makrand-moneyone** [apple/swift-protobuf#1529]
As per the new guidelines Third-party SDKs need to provide their own privacy manifest files. If this package doesn't have. Please let me know why it is not there and if the app review fails how can we justify this.

**Comment by tbkka** [comment]
SwiftProtobuf does not collect any data on its own.   I suppose we could add an empty .xcprivacy file somewhere.  Hmmm...

**Comment by tbkka** [comment]
Here's another project that uses SwiftPM and has added a empty privacy info file:
https://github.com/SnapKit/SnapKit/blob/develop/Sources/PrivacyInfo.xcprivacy

**Comment by makrand-moneyone** [comment]
So Can you add it to this package?

**Comment by tbkka** [comment]
I've filed a question with Apple's privacy experts to find out the right thing for us to do.

**Comment by corentios** [comment]
Following this

**Comment by tbkka** [comment]
This should not be an issue for app review:  SwiftProtobuf does not collect any data nor call any privacy-sensitive APIs.

We are looking into how to add an .xcprivacy file to avoid confusion.  That file will just re-state that SwiftProtobuf does not collect any data nor call any privacy-sensitive APIs.

**Comment by zddhub** [comment]
Following this

**Comment by nabs-m** [comment]
Any update on this? The Spring 2024 deadline is coming up soon, and having this will be needed to avoid potential app rejections for missing privacy manifests.

**Comment by tbkka** [comment]
Please take a look at #1565 and let me know if that looks sufficient.

**Comment by nabs-m** [comment]
Hey @tbkka, do you think we can get a new release that incorporates this change soon? Just trying to be wary about making sure we're fully compliant by spring.
