### ISSUE TITLE
JSON decoding is very slow

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#154]
After updating the perf harness to measure JSON encoding and decoding, I found some troubling results. Run 100 times for a message with 100 `int32` fields:

```
"Encode JSON" took 0.025 sec
"Populate message fields" took 0.000 sec
"Encode binary" took 0.004 sec
"Decode JSON" took 12.800 sec
"Test equality" took 0.000 sec
"Decode binary" took 0.009 sec
----
Total execution time: 12.840 sec
```

A glance at the call trace shows that we're spending most of that time in `ProtobufJSONScanner.next()`, with much of *that* time being charged to `Character.init(_builtinExtendedGraphemeCluster:utf8CodeUnit:isASCII)`.

I spent the past couple hours digging into the scanner and came up with the following results:

* Initializing `Character` values seems to be *expensive*, especially in tight loops. There are probably penalties there from all the details of Unicode correctness that that type provides. By working with the string's `unicodeScalars` view instead, I was able to get rid of a significant amount of overhead, without sacrificing correctness.
* Building up strings character-by-character (or even scalar-by-scalar) is also expensive. Instead of using iterators and appending, I maintain indices that I advance and take slices, which can be converted back to strings as a contiguous unit much more cheaply.

The result: JSON decoding of 100 messages with 100 `int32` fields went down from 12.8 sec to 0.023 sec—a roughly **550x** improvement.

I finessed some of the edge cases that weren't being exercised by the perf harness (I didn't worry about Unicode escape sequences, surrogates, and such) so that I could focus on speeding up the common cases, but putting those edge cases back shouldn't penalize those common cases too much. I also focused solely on the scanner side of things; there may be gains within the parser itself that I haven't explored yet, as well.

I'll keep working on this and get a PR out in the next few days, hopefully.

**Comment by thomasvl** [comment]
We should probably double check the string processing within the plugin also to see if there are easy speed up there also.

**Comment by tbkka** [comment]
Great!  I have been meaning to dig into this myself.  I had also thought about working directly with the UTF8 bytes and doing a conversion to/from String at the boundaries.
