### ISSUE TITLE
unknownFields prevents messages from being copied by memcpy

### ISSUE THREAD

**Issue by nocchijiang** [apple/swift-protobuf#1542]
Currently the `unknownFields` is stored inline. Since it is not a POD, the compiler generates field-by-field copy/destroy helpers for messages, which is inefficient in terms of both performance and code size. Proof (just a reproducing demo illustrating the idea, not strictly swift-protobuf-related):

- [With non-POD](https://godbolt.org/z/Mb7bb513P)
- [Without non-POD](https://godbolt.org/z/Ee953Prq4)

See the differences of "value witness table for output.Substructure" and "initializeWithCopy value witness for output.Substructure". 

Also I think it is fair to call it an optimization opportunity for Swift compiler (like generating memcpy for the POD fields and field-by-field for non-POD ones, even reordering the fields to allow the least amount of field-by-field copy).

**Comment by thomasvl** [comment]
Just for clarity sake, what's the issue you are reporting with SwiftProtobuf itself?

**Comment by nocchijiang** [comment]
> Just for clarity sake, what's the issue you are reporting with SwiftProtobuf itself?

The `protoc-gen-swift` generates `unknownFields` for each message. `unknownFields` is a `Data` which is not trivially destroyable (it holds a reference to a memory buffer which is managed by ARC). This prohibits the Swift compiler from generating a more efficient version of value witness functions (init with copy, assign with copy, etc.) for message `struct`s in terms of both performance and code size (field-by-field). I posted 2 godbolt demos illustrating this. By removing all the `unknownFields` we have observed a nearly 3% code size reduction on 1 of our iOS apps. I was wondering if there is a way to optimize this while also keeping the functionality of unknown fields, hence I chose to report the issue here (SwiftProtobuf). I also noticed that there are Apple compiler guys here so I mentioned the idea of optimizing it at compiler level.

**Comment by thomasvl** [comment]
`_protobuf_extensionFieldValues` for `ExtensibleMessage` could have similar impact.

It might make sense to move these extra things into `_Storage` for the generation that uses that, but for the smaller cases that don't use it, I'm not sure what can be done on this project for those.

As far as opportunities for the Swift compiler to do better, that probably would get more attention if you opened this as issues for the Swift compiler instead of on this projects.

**Comment by thomasvl** [comment]
@tbkka @Lukasa @FranzBusch thoughts?

**Comment by tbkka** [comment]
Please discuss this on the Swift compiler project:  https://gitHub.com/apple/swift
