### ISSUE TITLE
Need to Add a Privacy Manifest for Apple Validation store for sprint 2024

### ISSUE THREAD

**Issue by TrabelsiAchraf** [apple/swift-protobuf#1582]
We need to add a privacy manifest to comply with Apple's App Store guidelines for our sprint 2024. Could you please assist with integrating this into your library?

[Source Link](https://developer.apple.com/support/third-party-SDK-requirements)

Thanks

**Comment by thomasvl** [comment]
Duplicate #1529 

Just hasn't been a release with it yet, likely to happen soon.
