### ISSUE TITLE
Move conformance test runner into this project

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#160]
Forking off from #125.

Having the conformance test runner in a separate project makes it difficult to iteratively develop and ensure that both the runner stays up to date and that changes we make to the runtime/codegen don't break conformance tests. We should add it as a top-level target in `swift-protobuf`'s package description, then delete the `swift-protobuf-test-conformance` project.

Although it will increase build times currently, keeping our code health up is (IMO) a higher priority right now.

Eventually, the accepted Swift Evolution proposal [SE-0146](https://github.com/apple/swift-evolution/blob/master/proposals/0146-package-manager-product-definitions.md) will be implemented that lets us define individual products, and clients can depend on just the runtime product to avoid building the entire project.

I'll prepare a PR that moves over the necessary files, then updates them to compile with the latest version of the runtime.

**Comment by thomasvl** [comment]
@tbkka now that this is moved, what's the store with `Tests/SwiftProtobufTests/Test_Conformance.swift` and `Tests/SwiftProtobufTests/Test_JSON_Conformance.swift`.  Does the conformance test cover those?  Should we drop them?

**Comment by tbkka** [comment]
I don't see any particularly compelling reason to drop those, no.   Those were initially put in to help regress conformance failures (hence the names), but aren't necessarily identical.

It's much, much easier to debug/diagnose failures in the test suite than the conformance test.
