### ISSUE TITLE
PR approved back in July 2022 and changes still not included in a release

### ISSUE THREAD

**Issue by Zedenem** [apple/swift-protobuf#1603]
Hello team,

I have made this proposal which was approved and merged back in July 2022 and I am still eagerly waiting for it to be included in any official release of SwiftProtobuf: https://github.com/apple/swift-protobuf/pull/1249

I don't really understand what your process is to include changes that have been available on `main` for more than a year into a release.

Is there something I would need to do for this to happen? Is this the right place to discuss this?

Thanks for your help,

Zouhair.

**Comment by Lukasa** [comment]
The plan had been for `main` to be correlated with a v2 breaking release, which we've now slightly walked back. @thomasvl , any reason you can think of that we shouldn't backport this?

**Comment by thomasvl** [comment]
Yea, that looks like it could be pulled back to the branch in the mean time without being an api break (we've generally allowed option additions).

**Comment by Zedenem** [comment]
This is great news @Lukasa , @thomasvl.
Is there something I should do next to make sure it gets pulled back?

Also, for my understanding, does that mean if I make other (non-breaking) contributions I should expect them not to get released until v2? If so, do you have a public roadmap / release schedule I could look at?

Thanks again, looking forward to seeing this released.

**Comment by thomasvl** [comment]
> Is there something I should do next to make sure it gets pulled back?

Someone just has to put together a PR and put it up for review.

**Comment by Zedenem** [comment]
Ok I'll cherry-pick those changes and put a PR up targeting https://github.com/apple/swift-protobuf/tree/1_x_release_branch
Thank you.

**Comment by gjcairo** [comment]
FYI we've removed all breaking changes from `main` now, so we are getting ready to tag the next release from `main`.
This means this and several other bug fixes/new features that had not yet been released will make it into a release soon.

**Comment by thomasvl** [comment]
1.27 was release the other day, so this should be out now.
