### ISSUE TITLE
Unable to verify code signature when installing app to iOS from XCode

### ISSUE THREAD

**Issue by realh** [apple/swift-protobuf#1607]
I'm developing an iOS app with:

* MacOS 14.3.1 (M1 Pro)
* XCode 15.3 (15E204a)
* iOS 17.4.1 on an iPhone 12
* SwiftProtobuf 1.25.2 and 1.26.0 both tested (via Swift Package)

When I try to run it on my phone, straight from XCode, I get this error (reported by XCode):

### Unable to Install “Group”
Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.yP1jk8/extracted/GCiosApp.app/Frameworks/SwiftProtobuf.framework : 0xe8008001 (An unknown error has occurred.)

I've Googled for similar errors and tried just about every "solution" from [Apple Develor Forum](https://developer.apple.com/forums/thread/737156) and [SO](https://stackoverflow.com/questions/77215716/installation-error-on-ipados-17-and-ios-17-failed-to-verify-code-signature). None of them work. I can install the app via TestFlight, but that doesn't fix the problem whether I uninstall the TestFlight version first or not.

It was working as recently as 24 March and I'm not sure what has changed since then, except for an iOS update which was definitely today. I also performed a git bisect which might have confused XCode? I only tested the checkouts on a simulator instance though. The current version also installs on the simulator OK, just not on my phone.

I noticed my error message is missing the bogus advice to check the phone's App Developer certificates. My error message has additional details (see below) and seems to be singling out SwiftProtobuf instead of the whole app for some reason. 

### Details:
Unable to Install “Group”
Domain: IXUserPresentableErrorDomain
Code: 14
Recovery Suggestion: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.yP1jk8/extracted/GCiosApp.app/Frameworks/SwiftProtobuf.framework : 0xe8008001 (An unknown error has occurred.)
User Info: {
    DVTErrorCreationDateKey = "2024-04-01 18:39:27 +0000";
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
}

Unable to Install “Group”
Domain: IXUserPresentableErrorDomain
Code: 14
Recovery Suggestion: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.yP1jk8/extracted/GCiosApp.app/Frameworks/SwiftProtobuf.framework : 0xe8008001 (An unknown error has occurred.)
User Info: {
    IDERunOperationFailingWorker = IDEInstallCoreDeviceWorker;
}

Failed to install the app on the device.
Domain: com.apple.dt.CoreDeviceError
Code: 3002
User Info: {
    NSURL = "file:///Users/tony/Library/Developer/Xcode/DerivedData/GCiosApp-caesltabwlltiwgdsytbghwsxekm/Build/Products/Debug-iphoneos/GCiosApp.app/";
}

Unable to Install “Group”
Domain: IXUserPresentableErrorDomain
Code: 14
Failure Reason: This app cannot be installed because its integrity could not be verified.
Recovery Suggestion: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.yP1jk8/extracted/GCiosApp.app/Frameworks/SwiftProtobuf.framework : 0xe8008001 (An unknown error has occurred.)

Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.yP1jk8/extracted/GCiosApp.app/Frameworks/SwiftProtobuf.framework : 0xe8008001 (An unknown error has occurred.)
Domain: MIInstallerErrorDomain
Code: 13
User Info: {
    FunctionName = "+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]";
    LegacyErrorString = ApplicationVerificationFailed;
    LibMISErrorNumber = "-402620415";
    SourceFileLine = 79;
}

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_model" = "iPhone13,2";
    "device_osBuild" = "17.4.1 (21E236)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "355.24";
    "dvt_mobiledevice_version" = "1643.100.58";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 1877;
    "operation_errorCode" = 14;
    "operation_errorDomain" = IXUserPresentableErrorDomain;
    "operation_errorWorker" = IDEInstallCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 3;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 2;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 99;
    "param_launcher_substyle" = 8192;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 1;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.4";
    "sdk_osVersion" = "17.4";
    "sdk_variant" = iphoneos;
}

System Information

macOS Version 14.3.1 (Build 23D60)
Xcode 15.3 (22618) (Build 15E204a)
Timestamp: 2024-04-01T19:39:27+01:00

**Comment by thomasvl** [comment]
When you say things were working on March 24th, is that also with the 1.25.2 release? Assuming it was, then this is going to be specific to your project setup. If you weren't on 1.25.2 at that point, what release were you on? I can't think of what this project could have changed that would cause any packaging issues, but if we know your old version we can double check the delta to make sure there wasn't something we didn't realize.

**Comment by realh** [comment]
Yes, I've gone back to that commit and it was using SwiftProtobuf 1.25.2. Now that version won't install either. The name of the temporary directory has changed slightly. There is no /var/installd on my Mac, but I suspect the problem is more likely to be caused by XCode than my phone and SwiftProtobuf has been chosen at random to be the fall guy. I have not only cleaned the build folder, but also `rm -rf /Library/Developer/Xcode/DerivedData/<my_app>`. Is there anything else I can delete to completely eradicate the mess XCode has made of itself and do a clean install?

**Comment by thomasvl** [comment]
That's more an Xcode support question than specific to this package, so you'll probably get more suggestions from the developer forums.

**Comment by realh** [comment]
OK, thanks.
