### ISSUE TITLE
Install via homebrew

### ISSUE THREAD

**Issue by jacobjennings** [apple/swift-protobuf#161]
A homebrew formula would be a nice addition, especially if it plays nicely with protobuf-swift formula i.e.

brew unlink protobuf-swift
brew link swift-protobuf
protoc ... --swift_out ... ...

**Comment by azr** [comment]
👍

**Comment by anderscarling** [comment]
Just submitted a pull request: Homebrew/homebrew-core#17232

**Comment by anderscarling** [comment]
@tbkka - I just tagged you in the comments in the aforementioned pull req to get this into homebrew. Mentioning you here too, as I have no idea if you will get a notification about a mention in a repo/discussion you are not participating in.

Would appreciate it if you could check it out and maybe help me explain/understand the current release status of swift-protobuf, as I'm trying to championing getting it into the homebrew repo for easy install and usage.

**Comment by tbkka** [comment]
I just tagged SwiftProtobuf 1.0.  That is now an official stable release version.

**Comment by anderscarling** [comment]
That's awesome! Congratulations on getting the release out! :)

**Comment by tbkka** [comment]
Homebrew/homebrew-core#17232  has been merged.
