### ISSUE TITLE
Support for Protobuf Editions

### ISSUE THREAD

**Issue by jhump** [apple/swift-protobuf#1655]
I was just reviewing the latest release as well as recent commits in the repo. I can see some activity that appears to be adding support for Protobuf Editions, to use resolved features to control semantics instead of file syntax. But there was nothing noted in the recent release (which was about six weeks ago).

Is there any ETA for when Editions support will be ready and released?

**Comment by thomasvl** [comment]
Closing this out as 1.27 has the editions support.
