### ISSUE TITLE
SwiftProtobuf.xcodeproj cannot be opened because it is missing its project.pbxproj file.

### ISSUE THREAD

**Issue by aleksandranavruzova** [apple/swift-protobuf#1676]
We are using Carthage as a dependency manager. After running:
`carthage update --platform ios,tvos --use-xcframeworks`
we are getting version 1.27.0:
`*** Checking out swift-protobuf at "1.27.0"`
The project is not building with this version. The error is the following:
```
Unable to read project 'SwiftProtobuf.xcodeproj' from folder '/Users/.../Carthage/Checkouts/swift-protobuf'.
	Reason: Project /Users/.../Carthage/Checkouts/swift-protobuf/SwiftProtobuf.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

Xcode: Version 15.4 
Swift: swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)

**Comment by thomasvl** [comment]
Looks like it didn't make it into the release notes, but the Xcode project got retired on `main` and we never brought it back.  So it's only there as an empty folder for folks that have the user data directories/files keeping the empty shell around.

@tbkka should it come back?

@gjcairo @FranzBusch fyi.

**Comment by tbkka** [comment]
Maintaining multiple build systems is tedious work.  `swift package generate-xcodeproj` was deprecated long ago; without that, we would have to manually update an Xcode project in sync with swift package updates.  I'm not fond of the idea.  Maybe @Lukasa has a better idea?

I think the more practical approach here is to ask the Carthage people how to handle Swift packages that do not have Xcode projects.  I found a thread where some Carthage folks were looking into better integration with SwiftPM, but don't know how far that's progressed.

**Comment by FranzBusch** [comment]
I agree. I think we should just remove the Xcode project completely. The vast majority of the ecosystem has transitioned over to Swift PM. Other are free to fork this repository and maintain an Xcode project or pod spec in their fork for community use.
