### ISSUE TITLE
xCode shell script doesn't run

### ISSUE THREAD

**Issue by msemrl** [apple/swift-protobuf#1688]
Hello, I searched everywhere for informations but without success. 

I have a project in xCode with SwiftProtobuf (1.27.1) pod installed and would like to run a build phase script:

```
    cd MyProject/Resources/
    protoc --swift_out=../../MyProject/Models/ Models.proto
```

so that model would be created. But protoc is not found or for some reason can't be run from this script. Does anyone know why this would not work?

if I run the command from terminal it works as it should.

I am using xCode 15.4 on macOs 14.5

**Comment by thomasvl** [comment]
It's mentioned in the [Getting Started](https://github.com/apple/swift-protobuf?tab=readme-ov-file#getting-started) you need to installed it from the protobuf repo or if you use homebrew to install the plugin for this library that will also install protoc.

**Comment by msemrl** [comment]
@thomasvl I have installed it with homebrew, like I said, I can run it in my terminal, I just can't run it from xCode shell script

**Comment by thomasvl** [comment]
Then odds are it isn't on your `PATH` when Xcode is spawning the action.

However you've configured your environment, you probably are modifying your `PATH` such that it is there for the _Terminal.app_, but not things spawned from Gui apps.

**Comment by msemrl** [comment]
@thomasvl could you explain a bit more please, since this is my PATH
```
 "${PATH//:/\n}"
/opt/homebrew/bin
/opt/homebrew/sbin
/usr/local/bin
```

and this si where to protoc is
`/opt/homebrew/bin/protoc`

**Comment by thomasvl** [comment]
When you dumped `PATH`, was that from the same Xcode build phase that tries to invoke protoc? Or something you did in _Terminal.app_?  You need to examine the environment Xcode is provided/providing when invoking your custom build phase.

Note: This isn't really a problem specific to this library; it's something about your setup and install/usage of homebrew. So you might be better off looking for help on a forum specific to homebrew. I think you'd want to ask there about how to ensure what you've installed via homebrew is available to Xcode build phases. I personally don't use homebrew, so don't have any experience with it.

**Comment by msemrl** [comment]
@thomasvl got my answer or should I say, found the source to my problem 😓 , thank you
