### ISSUE TITLE
Support for XCFrameworks

### ISSUE THREAD

**Issue by LakshmiChidambaranathan** [apple/swift-protobuf#1715]
I am encountering a crash when creating an XCFramework for my SDK, which has `SwiftProtobuf` as a dependency via CocoaPods. By default, the `BUILD_LIBRARIES_FOR_DISTRIBUTION` setting is set to `No` when integrating through CocoaPods, but this needs to be overridden to `Yes` to properly use the XCFramework. Without this override, the crash occurs. It would be greatly beneficial if SwiftProtobuf could be provided as an `XCFramework` to avoid this issue.

Kindly find the other details as follows:

* Developing on Mac OS 14.6.1 (23G93) (Apple M1 Pro)

* for macOS, version of Xcode Version 15.4 (15F31d)

* Swift_version - 5.0

* tag of SwiftProtobuf - 1.26.0

* Crash - dyld[50182]: Symbol not found: _$s13SwiftProtobuf19_ProtoNameProvidingP17_protobuf_nameMapAA01_dH0VvgZTq
  Referenced from: <B6F31D19-7452-34A2-A02C-F3422627E3BA> /<userpath>/Library/Developer/CoreSimulator/Devices/6F58CF1E-7076-43C2-8CD3-75AA7BCA9827/data/Containers/Bundle/Application/6E33CC84-F7C0-4675-B04F-824EA2EB82E5/ProtobufBuildAnalysis.app/Frameworks/ZohoDeskPlatformUIKit.framework/ZohoDeskPlatformUIKit
  Expected in:     <2B86F3DE-BBD4-3979-AEA5-8F626BC0BEB4> /<userpath>/Library/Developer/CoreSimulator/Devices/6F58CF1E-7076-43C2-8CD3-75AA7BCA9827/data/Containers/Bundle/Application/6E33CC84-F7C0-4675-B04F-824EA2EB82E5/ProtobufBuildAnalysis.app/Frameworks/SwiftProtobuf.framework/SwiftProtobuf

**Comment by Lukasa** [comment]
Thus far, the Swift Protobuf team have been reluctant to define a stable ABI for Protobuf (see #1101). For now we'd recommend that you use protobuf as a purely internal dependency of your framework (using `internal import` in Swift 6, or `@_implementationOnly` earlier). This will allow you to statically link it as you see fit.

**Comment by allevato** [comment]
In addition to using `internal import` or `@_implementationOnly`, you should also use `-module-alias` to rename `SwiftProtobuf` to something else when it's embedded in your framework. That way, if one of your clients is also using `SwiftProtobuf`, the symbols in their copy and your framework don't collide.

**Comment by LakshmiChidambaranathan** [comment]
@allevato , Could you kindly explain how to use `-module-alias` to rename `SwiftProtobuf` to something else when it's embedded in your framework. I actually have this case, where one of my client is also using `SwiftProtobuf`
