### ISSUE TITLE
Add unknown field support to Text encoder/decoder

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#176]
As pointed out by @thomasvl :  "If we do swap debugDescription to use text format (#148), we likely will want them so the info is complete."

**Comment by thomasvl** [comment]
It would be nice to pull this into the Version 1 milestone, but at this point we aren't saying it has to make it.

**Comment by tbkka** [comment]
@thomasvl: I have a first sketch of writing unknown field data into the TextFormat output.  Based on 
   https://github.com/google/protobuf/blob/master/src/google/protobuf/text_format.cc
it looks like Google's C++ code does not make any attempt to parse unknown fields back out of the TextFormat data.  Does that sound right?  If so, then I hope to finish this pretty soon...

**Comment by thomasvl** [comment]
I believe that is correct, the problem on the parsing side is when you see a number, you don't know if it should be a varint, 32bit int, or 64bit int (wire types 0, 1, or 5).  From the TextFormat pov, there is no indicator.  JSON unknown support would have the same issue.

**Comment by tbkka** [comment]
Yep.  On further reading, it looks like this does work, though:
* Parse a binary proto into the empty (proto2) message
* Write to text format; unknown fields get written with field numbers
* Parse text format into a real message

In the last stage here, any field numbers known to the type will be recognized and parsed.  That is, the text parser needs to be able to recognize both field names and numbers and handle either one.  Unrecognized fields get discarded either way, of course.

**Comment by thomasvl** [comment]
Yes, sorry, I thought you meant unknown numbers specific.  If the number is a known field, they the parsing does work because the info can be looked up.

**Comment by tbkka** [comment]
PR #315 adds unknown field support to the text encoder.

The text decoder does skip unknown fields (correctly) but does not yet parse fields that uses numbers for field names.
