### ISSUE TITLE
Revisit Text format field and enum naming

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#177]
The Protobuf Text format encoder/decoder currently relies on some awkward sources of name information:
* Field names are expected to be stored by the generator in full format (in particular, extensions get stored as "[package.scope.field]").  We should be able to economize here.
* Enum names are generated by stripping quotes off the JSON serialization.  I need to double-check whether enum names are always the same between JSON and Protobuf Text.  If so, it would make more sense to have the JSON serialization add the quotes than to have the Protobuf Text serializer remove them.

**Comment by thomasvl** [comment]
Where does this one stand, is it done or getting finished out with your other PRs?

**Comment by tbkka** [comment]
Yes, I'll be cleaning this up along with my other decoder work...

**Comment by thomasvl** [comment]
Ok, tagged with the milestone so we track them all.

**Comment by tbkka** [comment]
This was actually finished a while back.

**Comment by thomasvl** [comment]
@tbkka did you want to do anything about your first bullet?  I did the second (enums), but I didn't look at the first.

**Comment by tbkka** [comment]
Yes, I had hoped to look at that.  Thanks for the reminder; re-opening.

**Comment by tbkka** [comment]
PRs #383 and #384 made some progress here.  The field name for an extension is now a simple StaticString.  If I can push that to be a String, then it can be computed using the same approach as `protoMessageName`.

**Comment by tbkka** [comment]
PR #400 explored sharing the package name, but that turned out to actually make the generated and compiled code larger.

Closing this.
