### ISSUE TITLE
Visitor and related API improvements

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#181]
* Should the `Visitor` protocol be `class`-constrained? This would let us get rid of the awkward `withAbstractVisitor` dance that's required because they would no longer have to be passed as `inout`, and polymorphism on the protocol type will just work cleanly when visitors recurse on nested messages.

* A small enhancement, but the concrete visitors currently do everything as a side effect of initialization: for example, calling `ProtobufEncodingVisitor(message: foo, pointer: bar)` causes `foo` to be serialized into `bar`, and the actual visitor afterwards is unneeded (hence the need for `_ = ProtobufEncodingVisitor(...)` at the call site). We should separate these concerns by having the call sites initialize visitors and pass them to `traverse` as separate operations. (This also becomes much easier if we get rid of `withAbstractVisitor` above.)

* We have metatypes like `ProtobufInt32`, `ProtobufFloat`, etc., which conform to `FieldType` (among others) and contain static vars/funcs to provide visitors and decoders with various information (wire format, corresponding Swift type) and encoding/decoding logic. For messages, however, the message type itself conforms to `FieldType`. This adds a large number of static methods that are implementation details to the public API of messages. What if we create a `ProtobufMessageType<M: Message>` metatype instead for these? Separating out the low-level encoding/decoding will clear up some noise from the public API of actual messages. (The same might be true for enums, as well.)

**Comment by tbkka** [comment]
> Should the `Visitor` protocol be `class`-constrained?

Probably so.

> ... side effect of initialization ...

I'm generally not a fan of side effects in initializers, so I'd be happy to see this change.

> For messages, however, the message type itself conforms to `FieldType`. ... What if we create a `ProtobufMessageType<M: Message>` metatype instead for these?

Today, that's done to allow overriding the parsing and encoding for specific message types.  JSON in particular has special coding requirements for almost every WKT.  (Even the `null` JSON token is not handled consistently by all WKT types.)  Related:  I'm experimenting with a redesign of the JSON logic that would significantly reduce the number of methods on `FieldType` for JSON fields.

Another approach would have the `FieldType` be an associated type for the message.  That would allow specific message types to override encoding/decoding details while greatly reducing the namespace pollution on the message itself.

**Comment by allevato** [comment]
> Another approach would have the FieldType be an associated type for the message. That would allow specific message types to override encoding/decoding details while greatly reducing the namespace pollution on the message itself.

That's an interesting idea, but the big catch there is that you wanted to keep associated types off of `Message` so that it can be used as a standalone type, right?

If we put the associated type on `_MessageImplementationBase`, we'd have to change the visitor APIs to take generic arguments of type `<M: _MessageImplementationBase>`, which would be pretty rough. Otherwise, those methods would have to check at runtime if the metatype `M` also conforms to that protocol and cast it; not ideal either.

It looks like the only reason we need to allow this kind of overriding is to customize the JSON encoding/decoding for WKTs, so maybe we ought to just do this:

* Generate the WKTs as any other proto.
* Write a `CustomProtobufJSONRepresentable` protocol that provides hooks for encoding/decoding.
* Write extensions in the runtime library to conform the WKTs that need custom JSON representation to that protocol, and implement the customized logic there.
* Update the JSON encoder/decoder to look for conformance to `CustomProtobufJSONRepresentable` at runtime and call it if present; otherwise, use the standard logic.

It doesn't seem like a runtime check can be avoided if we restrict ourselves to no associated types on `Message`. Other languages have to do similar special case checks for the JSON WKTs—many just encode it as a table in the encoder/decoder classes. We have a slightly better advantage design-wise in Swift at least, because we can use extensions to associate the representation with the types themselves.

Am I missing anything? If that sounds good I can loop it back into #13 and work on it.

**Comment by allevato** [comment]
On an unrelated note to the comment above, the `class`-constrained change to `Visitor` probably ought to apply to `FieldDecoder` as well?

**Comment by tbkka** [comment]
> ... `class`-constrained change to ... `FieldDecoder` as well?

I'm exploring that right now, as a matter of fact.  It looks promising.

**Comment by tbkka** [comment]
> It looks like the only reason we need to allow this kind of overriding is to customize the JSON encoding/decoding for WKTs, so maybe we ought to ...

As part of my experimenting with the JSON decoder structure, I'm also looking at using selective run-time checks to avoid some of the customization hooks.
