### ISSUE TITLE
Issue when running protoc

### ISSUE THREAD

**Issue by acoroian** [apple/swift-protobuf#189]
I am getting these errors when i try to do protoc. Is it something i am doing wrong or are these issues?

`dyld: lazy symbol binding failed: Symbol not found: __TFSP17withMemoryReboundu0_rfzT2toMqd__8capacitySiFzGSpqd___qd_0__qd_0_
  Referenced from: /usr/local/bin/protoc-gen-swift
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib

dyld: Symbol not found: __TFSP17withMemoryReboundu0_rfzT2toMqd__8capacitySiFzGSpqd___qd_0__qd_0_
  Referenced from: /usr/local/bin/protoc-gen-swift
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
`

**Comment by tbkka** [comment]
I've seen this when I upgraded my Swift compiler and rebuilt protoc-gen-swift without cleaning first.  Try deleting the `.build` directory entirely, then rebuilding.
