### ISSUE TITLE
Ability to remove package namespacing

### ISSUE THREAD

**Issue by NachoSoto** [apple/swift-protobuf#197]
Given the following example proto:
```proto
syntax = "proto3";

package model;

message UserAccount {
    string email = 1;
    string password = 2;
}
```

`swift-protobuf` currently generates a struct named `Model_UserAccount`. It would be nice to be able to change this. For example, one way in that the Java version deals with extra namespacing is via the `java_multiple_files` `option`, which separates each type into a different file.

So I can imagine a similar `swift_multiple_files` `option`, or `swift_package` (similar to `java_package`) that allows to change or remove the type prefixes.

**Comment by tbkka** [comment]
I think you're looking for this:
```
option swift_prefix=""
```
Note:  This requires you to be using an up-to-date copy of protoc.

**Comment by NachoSoto** [comment]
Cool thanks! Looks like 3.1.0 still doesn't support it, so I'll wait for the next release.

**Comment by tbkka** [comment]
In the interim, you can also work around this by adding your own type aliases, e.g.:
```
public typealias UserAccount = Model_UserAccount
```
