### ISSUE TITLE
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required

### ISSUE THREAD

**Issue by CosynPa** [apple/swift-protobuf#198]
SWIFT_VERSION is set to 3.0.1 in 0.9.26. According to rballard's reply in this thread

[XCode 8.2, does not detect that my project already is migrated to Swift 3](https://forums.developer.apple.com/thread/69340)

setting to 3.0.1 is a bug in Xcode 8.1, Xcode 8.2 will always set it to 3.0. And setting it to 3.0.1 will cause Xcode 8.2 reporting build error

> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift.

when compiling SwiftProtobuf.

**Comment by kitasuke** [comment]
I guess it's fixed in Xcode 8.2.1.

**Comment by CosynPa** [comment]
I tried Xcode 8.2.1 today, yes, it never report this error. But if you toggle "Use Legacy Swift Language Version" to YES and then back to No again, Xcode 8.2.1 will also set SWIFT_VERSION to 3.0 instead of 3.0.1. So I think the correct value is 3.0.

**Comment by thomasvl** [comment]
Where did this end up, what do we need to do, drop it back to just 3.0 to keep Xcode happy?

**Comment by tbkka** [comment]
3.0 is the correct value.  The 3.0.1 setting was a bug in Xcode.
