### ISSUE TITLE
Nested message anyTypeURL is wrong

### ISSUE THREAD

**Issue by cyrusdaboo** [apple/swift-protobuf#202]
Given the following:

`
message Outer {
  message Nested {
  }
}
`

When compiled for Swift, the value of Test.Nested.anyTypeURL is "type.googleapis.com/Nested", which is wrong. It should be the fully scoped name, i.e. "type.googleapis.com/Outer.Nested".

As a result, serialization/deserialization of the google.protobuf.Any type does not work when interoperating between Swift and another language implementation.

In other languages I looked at (Python, C++) the Google protobuf code uses a Descriptor object to capture information about a message. The Descriptor class includes .name and .full_name attributes. The later is the fully scoped name (I.e. "Outer.Nested" from the example above). When serializing an Any() type, the full_name is used for the type URL.

Unfortunately, the Swift Message.anyTypeURL implementation only uses the unscoped name of a nested message.

One solution would be for the Message class to have a protoMessageFullName property that generated code would initialize to the fully scoped message name. Then the Message.anyTypeURL implementation could be changed to use protoMessageFullName instead of protoMessageName.

**Comment by tbkka** [comment]
Good catch.

**Comment by tbkka** [comment]
Fixed by PR #377
