### ISSUE TITLE
Remaining tasks to move out of "prerelease" state?

### ISSUE THREAD

**Issue by dpassage** [apple/swift-protobuf#208]
Hey everyone,

Now that google/protobuf has released an RC of 3.2, what do you view as the necessary tasks to getting this project to a 'released' state?

@jacobjennings and I have been using this in our project and been really pleased with the results so far. We'd be happy to help however we can getting this across the finish line.

**Comment by thomasvl** [comment]
There already are tags on issues for "API Change" and "generator API", those all need to be resolved as they changing them is likely to be a source breaking change.

**Comment by dpassage** [comment]
Great, we'll look through those and see if there are things we can do.

What about things like #99 (documentation) and #38 (CI)? We could probably help get a job going on travis-ci pretty quickly for instance.

**Comment by thomasvl** [comment]
Docs - Mainly waiting for code changes to be done to avoid revising the docs multiple times.  If you want to start to send in PRs, I don't think anyone would turn them down.  😄 

CI - That likely requires one of the Apple folks to do it, as they have to enable a hook on github to kick off builds.  So what ever process Apple has to audit/decide/etc. what is trustable would be the initially gating factor.

**Comment by dpassage** [comment]
We'll look at the docs stuff.

Re CI - it looks like there's already one project under the app org on travis: https://travis-ci.org/apple/ccs-calendarserve. So it appears that gate may already have been passed.

**Comment by thomasvl** [comment]
Maybe, still need someone from Apple to set up the hook, etc.

**Comment by tbkka** [comment]
CI is being looked into and should get resolved fairly soon.

Docs:  Google's done a good job structuring their documentation, and I'd love to rework our docs to follow the same outline:

* Tutorial, similar to https://developers.google.com/protocol-buffers/docs/csharptutorial
* Generated code, similar to https://developers.google.com/protocol-buffers/docs/reference/cpp-generated (this is different from our current generated code guide which discusses the structure of the code emitted by the generator, which is distinct from how you use the generated code)
* Most of the API docs on developers.google.com are generated from javadoc, etc; I'm not sure how well that approach would work for us, but it would be worth trying.

**Comment by jacobjennings** [comment]
Apple's documentation format might be something to consider, this article was helpful for me: http://nshipster.com/swift-documentation/

**Comment by thomasvl** [comment]
Once we cut a release/push the cocoapod, http://cocoadocs.org/ will auto generate that also.

**Comment by dpassage** [comment]
@tbkka thanks for the update on CI!

**Comment by jcanizales** [comment]
This is how the Cocoadocs documentation looks like at the moment: http://cocoadocs.org/docsets/SwiftProtobuf/0.9.24/ That was pre @tbkka's big renaming.

The list of classes / enums / functions / ... at the left is pretty miserable in that it lacks any structure or logical order. But I don't think much can be done about it?

**Comment by tbkka** [comment]
Visibility would be another great task for someone to work through:  Assuming the auto-generated docs ignore anything that's private or internal (which they should), then it would be a useful tool for checking that everything public is either be intended for end users or prefixed with `_protobuf_` to indicate that it's reserved for the generated code to use.

**Comment by thomasvl** [comment]
Closing this out, just created a Version 1 milestone (https://github.com/apple/swift-protobuf/milestone/1) that we can use to track this process.

**Comment by dpassage** [comment]
👍
