### ISSUE TITLE
Fetching a oneof doesn't return the default value (when not set)

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#22]
The fields in a oneof are just fields.  So fetching it should still return the default value even when the oneof was set to a different element.

This also allows proto authors to modify a proto by moving a field into a oneof in the future.  From a wire format pov, nothing changes.

**Comment by tbkka** [comment]
I think your comment only applies to proto3?

In proto2, oneof fields are optionals, and we map proto2 optionals to Swift optionals, so the default value in that case is nil.

Oh.  I suppose proto2 optionals can have explicit default values?  I don't think I've seen that case, but that would make sense as well.

**Comment by thomasvl** [comment]
You can also have a message in the oneof, so returning the default there to dot into the default fields also is useful.

**Comment by tbkka** [comment]
> You can also have a message in the oneof, so returning the default there to dot into the default fields also is useful.

Yes, good point.  Are there examples of this in the `google/protobuf/unittest_*` protos?  If so, then it should be easy to fill in some tests for these cases.

**Comment by thomasvl** [comment]
Yup - https://github.com/google/protobuf/blob/master/src/google/protobuf/unittest.proto#L177

**Comment by thomasvl** [comment]
PR #119 added tests to confirm this got fixed in PR #102
