### ISSUE TITLE
Encoding to text format can't throw; remove spurious `throws`

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#229]
Encoding to text format shouldn't throw—the only places where it currently throws are because of protocol requirements in the `FieldType` methods or when a field name fails to resolve (in which case we should be returning the field number as a string instead).

We can't clean up the API 100% because `TextEncodingVisitor` conforms to a protocol with throwing methods and even though the concrete implementations of those methods can be made non-throwing, since `traverse` operates on `Visitor` polymorphically, it can't know that the concrete visitor it's given doesn't throw. However, we can clean up as much as we can and then swallow the never-thrown errors at key points. For example,

* `serializeTextValue` in the `FieldType` protocol should be made non-throwing, because none of its concrete implementations except for `Message` are declared as throwing
* `Message.serializeTextValue` can be made non-throwing by wrapping its implementation in a swallowing `do/catch`
* Update `TextEncodingVisitor.protoFieldName` to return the field number instead of throwing if the field name is not found
* Now, none of the calls inside `TextEncodingVisitor.visit*` methods can throw; those `try`s can be removed and the methods can be made non-throwing
* Finally, make `Message.serializeText` non-throwing by wrapping its implementation in a swallowing `do/catch`

**Comment by tbkka** [comment]
I think it probably makes sense to rework Text encode to not throw -- on the argument that Text is primarily for debugging and any output is better than nothing -- but there is one odd corner case:  If the message was decoded from JSON and contains an Any field, the JSON parser defers the Any by storing the JSON text.

If you then re-encode the object to Text, what happens with that JSON?  Today, at the point where we try to encode the Any to Text format, we try to complete the parse of the deferred JSON, which can fail.  Note:  The initial JSON parse does verify that the JSON is lexically correct, but cannot verify schema.

**Comment by thomasvl** [comment]
Isn't that sorta deferred encoding a general problem?  What happens if a developer later access the `type_url` or `value` from the Any?  Suddenly field access can fail?

**Comment by tbkka** [comment]
> Suddenly field access can fail?

Of course not.  `type_url` is provided by all the formats, so if the Any came from decoded data, then that will be populated.  `value` may be nil, though, if the binary protobuf form could not be reconstructed.  But reading an Any should normally be done through `unpack`, which requires you to have the type for that particular field anyway.

Deferred decoding allows you to read large messages that happen to have Any fields without needing to have a registry of every type stored in those fields (possibly recursively).  You only need the types for fields you are actually going to read.

**Comment by tbkka** [comment]
#390 fixed the Text encoder so it correctly emits numbered fields if it can't lookup names.  With that change, `TextEncodingError` is now empty (and I should remove it).

So I think the Any JSON issue is the only remaining possible problem.  Keeping in mind that Text format is primarily for debugging, I think it would be fine to just invent something here:  The Any could serialize to a form that just dumped the raw JSON in this case, for example.  (Which is the same in spirit as how binary values get handled:  If they can't be converted to a verbose message, the binary gets written out directly.)

**Comment by thomasvl** [comment]
Yea, we could dump the JSON as a TextFormat comment so the output is still to "spec" even if it doesn't capture everything.

**Comment by tbkka** [comment]
> Yea, we could dump the JSON as a TextFormat comment so the output is still to "spec" even if it doesn't capture everything.

👏 Of course!  (Why didn't I think of that?)
