### ISSUE TITLE
Unknown flag: --swift_opt

### ISSUE THREAD

**Issue by chmod007** [apple/swift-protobuf#245]
I am getting Unknown flag: --swift_opt error for some reason. Any idea what could cause this?

```
% protoc-gen-swift --version
protoc-gen-swift 0.9.27
% protoc --version
libprotoc 3.2.0
% protoc --swift_opt=Visibility=Public --swift_out=. X.proto
Unknown flag: --swift_opt
% protoc --swift_out=. X.proto
```
This works

**Comment by thomasvl** [comment]
Does flipping the order work?

```shell
% protoc --swift_out=. X.proto --swift_opt=Visibility=Public file.proto
```

**Comment by chmod007** [comment]
No, same error.

**Comment by thomasvl** [comment]
Shoot, this is gonna be an issue with protoc's support for _opt args, I'm guessing our current build process works because we use `--plugin`.  Add `--plugin=protoc-gen-swift=[path_to_protoc-gen-swift]` before the other args, and it should work.  We'll need to update the docs and file a bug against protoc.

**Comment by chmod007** [comment]
Thanks, that works!

**Comment by thomasvl** [comment]
I've upstreamed the issue in https://github.com/google/protobuf/issues/2712

**Comment by thomasvl** [comment]
Quick update for the workaround, looks like things can be shortened to `--plugin=[path_to_protoc-gen-swift]`.  Which also means the plugin doesn't actually have to be on your path.

**Comment by thomasvl** [comment]
Fix merged upstream, working on getting it to the 3.2.x branch.

**Comment by thomasvl** [comment]
And it's on the 3.2.x branch there, so when a 3.2.1 gets cut it will be more easily used.

I'll update docs before closing this out.

**Comment by johndpope** [comment]
brew upgrade seems to have fixed this for me (despite having latest xcode)
