### ISSUE TITLE
Use `FieldNameMap` on `Enum` for textual names

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#247]
As discussed in PR #243:

https://github.com/apple/swift-protobuf/pull/243/files/e397b41fa359a4aa7f6fec465b4a2d357b661d65#diff-7ed1330a33d576e5f9e1354cfb77e795L23

we should be able to reuse `FieldNameMap` with `Enum` to provide number ⇔ name mapping.  A few notes:
* Maybe rename `FieldNameMap` to just `NameMap`?
* Can we use the exact same `ProtoNameProviding` protocol here?

Among other things, this would work well with a future generator option to omit the textual names.

**Comment by thomasvl** [comment]
@tbkka should this be in the milestone also?
