### ISSUE TITLE
OneofEnum protocol is unnecessary

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#267]
The `OneofEnum` protocol captures the API of the enum that represents which case of a `oneof` is set. It contains the decoding (`init?` after #263) and traversal methods.

It's not necessary. Unlike regular enums, `oneof`s are entirely coupled to their containing message, and there's no reason for a user (or the runtime library) to try to work with one in a generic sense. In fact, the enum itself is *never used in the runtime library*, except for the one conformance for the `kind` in `Google_Protobuf_Struct`.

All parsing/traversal happens within the context of the containing message, which is generated in the same file, so if we get rid of the protocol we can make those functions `fileprivate` and lock them down. Let's remove it so people don't start depending on it.

**Comment by tbkka** [comment]
Nice find!
