### ISSUE TITLE
TimeUtils.swift and MathUtils.swift not compiled by iOS, tvOS and watchOS targets

### ISSUE THREAD

**Issue by erikt** [apple/swift-protobuf#285]
Not sure if this is by design and I'm doing something wrong, but the iOS (and tvOS and watchOS) target doesn't compile due to it is unable to find functions and constants defined in `TimeUtils.swift` and `MathUtils.swift`.

These files are not included in the target's list of files to compile.

Code compiles if I add `TimeUtils.swift` and `MathUtils.swift` to the target.

**Comment by thomasvl** [comment]
It was just an oversight when adding those files.
