### ISSUE TITLE
swift ios 8 using carthage dependency manager

### ISSUE THREAD

**Issue by sheshnathiicmr** [apple/swift-protobuf#292]
i am not able to use it for iOS 8 target, using proto3, SwiftProtobuf.framework version is 0.9.24, i tried with 0.9.22 also, but again same issue, SwiftProtobuf minimum support target is iOS 9. when i added framework using cocoapods, it's working fine with iOS 8 , but when i use carthage it's say min deploy target iOS9

**Comment by thomasvl** [comment]
Just checking, which Xcode version are you trying to use?  We do require Swift 3.  But the checked in project file might have a min set up at iOS 9 at the moment, which likely can be changed.

**Comment by thomasvl** [comment]
Actually is there a reason you are trying to use that old version?  The more recent tags are already set to iOS 8.

**Comment by sheshnathiicmr** [comment]
thanks for response, and sorry for late reply, xcode version is 8.2.1, now  i proceeded with cocopods instead of carthage.

**Comment by rick-kln** [comment]
Same issue here:
```
protoc --version
libprotoc 3.2.0
```
```
swift --version
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```
```
macOS
10.12.2 (16C67)
```
```
git log -1
commit 1eab5a89b47925e035cc2449e8a8d166de9eeb1b
```
Carthage file:
```
github "apple/swift-protobuf" "0.9.24"
```

Our project targets iOS 8+ but the `SwiftProtobuf` modules seems to only target iOS 9+
```
...help.pb.swift:10:8: Module file's minimum deployment target is ios9.0 v9.0: 
...SwiftProtobuf.framework/Modules/SwiftProtobuf.swiftmodule/arm64.swiftmodule
```
![screen shot 2017-04-11 at 11 09 49 am](https://cloud.githubusercontent.com/assets/533058/24901471/7d86e0da-1ea7-11e7-9fb4-a75dda6d8f15.png)

**Comment by rick-kln** [comment]
I tried changing the Cartfile to target a later version:
```
github "apple/swift-protobuf" ~> 0.9.24
```
This results in Carthage checking out `swift-protobuf at "0.9.29"` which then results in the following build error:
```
*** Building scheme "SwiftProtobuf_iOS" in SwiftProtobuf.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/rick/projects/luno/ios/app/Carthage/Checkouts/swift-protobuf/SwiftProtobuf.xcodeproj -scheme SwiftProtobuf_iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```
The fixing the version at `0.9.24` solves the Carthage build error but results in the
```
Module file's minimum deployment target is ios9.0 v9.0
```
problem.

**Comment by rick-kln** [comment]
The build error which occurs with `0.9.29` also occurs when fixing the version to a version from `0.9.26` to `0.9.28`. Fixing to `0.9.25` results in `No object named "0.9.25" exists` and then `0.9.24` and lower result in `Module file's minimum deployment target is ios9.0 v9.0`.

**Comment by rick-kln** [comment]
We can't enable `use_frameworks` in CocoaPods in our project due to incompatibilities with some other libs so I will try manually adding the target to Xcode next. Will be nice when Carthage is working :)

**Comment by rick-kln** [comment]
When opening the Xcode project from this package and trying to build the target manually the following error occurs:
```
Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```
To fix it I had to go to the build settings for each target individually and toggle the `SWIFT_VERSION` to `Yes` and back to `No` as described in this [StackOverflow post](http://stackoverflow.com/questions/41157874/use-legacy-swift-language-version-swift-version-is-required-to-be-configured)
(Xcode/macOS versions listed earlier in this thread).

Finally building the framework manually at commit `1eab5a89b47925e035cc2449e8a8d166de9eeb1b` which seems to be version `0.9.30` and dragging that in still results in: `SwiftProtobuf` giving `Module file's minimum deployment target is ios9.0 v9.0`

**Comment by thomasvl** [comment]
> Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

I think that might have been a bug in Xcode 8.2 fixed in 8.2.1, but definitely fixed in 8.3

**Comment by rick-kln** [comment]
Thanks! Off to update Xcode...

**Comment by rick-kln** [comment]
So the upgrade to Xcode 8.3 fixed that issue and also showed that the Carthage build problems were related to Swift 3.. Updating to Xcode 8.3 and thus Swift 3.1 meant I could build versions `0.9.26-0.9.29` via Carthage. Once I got the Carthage build of `0.9.29` working the iOS 9 error disappeared. Thanks for the help. Perhaps add a note in the docs saying requires Swift 3.1 or higher?

**Comment by thomasvl** [comment]
Has anyone given Carthage a try with our 0.9.90x release?  Do we need to do anything else to support Carthage?

**Comment by tbkka** [comment]
I believe Carthage is working with the latest tagged version.

Closing.
