### ISSUE TITLE
Story for generating code being used in Swift modules

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#294]
The current code generation assumes the runtime will come from a module named `SwiftProtobuf` and that all generated code will end up in a single module.  But reality likely won't match that.

Something gRPC likely will have some protos it will bundle, and then the code they generate for a service will likely get built into another module.  So those _service_ will likely need something like _import gRPC_ to get access to the protos shipped there.  And to avoid collisions, any proto that is in _gRPC_ should likely get references in the generated code as _gRPC.[PROTO_NAME]_ (just like we do for the _SwiftProtobuf_ references.

This can also quickly cascade, one package might expose one set of protos, another package might need to reference those, a third provides some independent protos, and then a forth comes in and has protos that reference the ones from two and three.

Initially it might make sense to think of trying to providing a mapping that uses [proto packages](https://developers.google.com/protocol-buffers/docs/proto#packages) to decide what Swift package the code will be in; but that constraint is likely to cause problems.  A collection of proto files might all have the same proto package, but they could be needed by different independent modules, so they want to be in different Swift modules.

For reference the ObjC generator used a [generator options for this](https://github.com/google/protobuf/tree/master/objectivec#objective-c-generator-protoc-options).  Swift being different, the `generate_for_named_framework` doesn't seem like it will apply, as the module the code will end up in hopefully will never be needed because it won't be imported and the types shouldn't need scoping.  So something like `named_framework_to_proto_path_mappings_path` may make the most sense, some form of input let the generator figure out what modules would needed to be imported by each file for the referenced types and how to prefix the types to avoid collisions.

**Comment by tbkka** [comment]
I don't think we can use proto packages to infer Swift modules, the semantics are too different.

I would suggest we consider another file-level proto option for controlling this.

**Comment by thomasvl** [comment]
I'd rather keep it out of the proto files.  Just because one project bundles the protos one way doesn't mean the next project will bundle them the same way.  The name prefix option is a little different in that odds are no matter how they are packaged, they should be consistently named.

**Comment by thomasvl** [comment]
Sorry, should likely have spelled it out more.

The stuff I expect to be different for different developers (packaging, the current generator options for visibility and output paths), I'd rather those as generator options because the developers don't have to edit the proto files for their packaging needs.

The prefix is something that should likely be consistent in all builds (no matter how things are packaged), so the types will always be the same.  So having that in the file so everyone gets the same thing seems right.

**Comment by tbkka** [comment]
The tricky part is when a message in one package refers to a message in a different package.  So when `protoc` generates code for `Foo`, the generated code may need to know what module `Bar` is in (in order to `import` it if nothing else).  I don't know if a generator option can really work here, since `protoc` pulls in all of the referred-to protos and bundles them for the generator -- the generator will need to know the appropriate module to use for each referenced proto.

**Comment by thomasvl** [comment]
Right, see the mapping file method I used for objc.  The generator would use an option to tell it what file to read to figure out the file -> Swift module mappings to generate the right imports/references.

**Comment by thomasvl** [comment]
Taking this out of the 1.0 milestone as it doesn't change the library at all, just something in the plugin so we can do it in a point release.

**Comment by thomasvl** [comment]
So the basic information we need is something that tells us a proto file will be a specific Swift module (so we can generate the import and correct reference).  Since odds are multiple proto files will be in each module, the most likely logical support for this will be _module_ to _one\_or\_more\_proto\_files_.

There are two ways I can see to do this: generator option that can be used multiple times or generator option that provides a file where the mappings are read.  Using an option for the mapping directly is useful in the simple case where there aren't many mappings, but from what Google has seen internally, there could end up being a lot of these for full apps built off common components, so to avoid running in to max command line length, using a file seems like the better choice.  Supporting both seems like it would lead to confusion and more chances of conflicting data.

Format of the file is the next question, the data is logically a map.  TextFormat proto would work, but the TextFormat for those is just the repeated field, so I think it would be harder to use.  JSON protobuf format would work (using a google.protobuf.struct), so keys are modules and values as the proto file names.  The catch is JSON doesn't support comments, and I sorta worry about not having comments as they could be useful for a someone maintaining a mapping.  So that leaves our own text file format that can do comments, so something what the ObjC generation uses for this.  So…

```
# Comment
module_name: path/to/a.proto
different_module: some/other.proto, another.proto
```

- Comment can also go on the end of a line.
- Commas between file paths to allow spaces in file/directory names.
- A module name can be listed more than once if there are a lot of files that it applies to so they can be split up to avoid a really long line or to group things logically with comments/etc.

Anyone see any other way to go about this?

**Comment by thomasvl** [comment]
Actually, TextFormat might work if we don't try to use a map…

```protobuf
message Mappings {
  message Entry {
    string module_name = 1;
    repeated proto_file = 2;
  }
  repeated Entry mapping = 1;
}
```

would mean the config looks like:

```
mapping {
  module_name: "MyModule"
  proto_file: "foo/bar.proto"
}
mapping {
  module_name: "OtherModule"
  proto_file: "mumble.proto"
  proto_file: "other/file.proto"
}
```
