### ISSUE TITLE
Validate Group parsing

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#334]
Spun out of #333.

If the `nextFieldNumber` loop sees a field that is a startGroup, it doesn't seem to ensure everything to the endGroup goes into the unknowns for the message.

The unknown handling needs to deal with groups, if the field number wasn't known, it needs to ensure all the subfields make it into the messages unknowns.  The catch is this can be recursive, there could be another startGroup so it needs to read until both endGroups.

We might want to double check that the normal group parsing ensure the endGroup is found and that the startGroup wire type was seen.  (on quick look, I think the startGroup check is there, just not sure about the endGroup vs. data happening to end)

**Comment by thomasvl** [comment]
Fixed up a few things, last thing on my list is unknownFields within the group are completely dropped at the moment.

**Comment by tbkka** [comment]
There is a `skip` method used for grabbing the body unknown fields that should know how to skip an entire group.  It sounds like it was never fully tested...

**Comment by thomasvl** [comment]
The problem is nothing puts the unknowns on to the group.  I think I've got things sorted out now, going to do some more tests and a perf test to check the impact on things, and hopefully get the PR out early tomorrow.
