### ISSUE TITLE
protobufBytes faster than protobuf in decoding

### ISSUE THREAD

**Issue by stonetip** [apple/swift-protobuf#339]
More a question than an issue. I inadvertently discovered this to be the case because [Geobuf.proto](https://github.com/mapbox/geobuf/blob/master/geobuf.proto) unfortunately uses the rather generic "Data" for its Message structure. In loading a file as NSData, I couldn't use:

`let decoded = try GBData(protobuf: srcPbf as Data)`

Instead I had to use:
```
let count = srcPbf.length / MemoryLayout<UInt8>.size

var byteArray = [UInt8](repeating: 0, count: count)

srcPbf.getBytes(&byteArray, length: count * MemoryLayout<UInt8>.size)

let decoded = try GBData(protobufBytes: byteArray)
```
With a fairly large .pbf (~3.5Mb) the latter runs ~37% faster. Should I care about which I use from any other than a performance standpoint? Otherwise, I thought I'd mention it in case it leads to any improvement in the more general call.

(Incidentally, when I reran protoc on the .proto file after renaming Data to GBData all the confusion over namespacing went away and I am able to use the former call. But the performance difference is still the same).

**Comment by thomasvl** [comment]
What version are you using?  `master` has a lot of speed improvements (and api cleanup).  So you may find the numbers to be different now.

**Comment by thomasvl** [comment]
The updated init is [`init(serializedData:extensions:partial:)`](https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/BinaryTypeAdditions.swift#L56-L72).  Otherwise you'd have to use the new `merge(serializedData:extensions:partial:)` method listed right after that to merge into an empty instance you create.

**Comment by stonetip** [comment]
I'm still using 0.9.24. I'll update and try further testing. Thanks. 

BTW, the other Swift protobuf lib I tried generated over 3X as many lines of code from the .proto file and runs twice as slow. Overall, I'm really impressed with the performance and effort that has gone into this.

**Comment by tbkka** [comment]
@stonetip:  Thanks for the kudos.  We're still working on performance and would greatly appreciate any reproducible test cases that show weaknesses there.

Another hint:  You can disambiguate references to standard Swift classes by using the module name:  the standard `Data` type in Foundation can be referred to as `Foundation.Data` if you have another `Data` in scope.  You can also add package declarations or `option swift_prefix` to your proto files to globally alter the way the resulting structs get named.

**Comment by tbkka** [comment]
I just went back and looked at the old version of the code:  In the version you're using, we internally converted `Data` to `[UInt8]` and then parsed the `[UInt8]` form.  That code has been streamlined significantly in the latest master.  Please let us know if you're still seeing problems here.

**Comment by stonetip** [comment]
I updated to use 0.9.26 with protoc and in my SPA project. Other than a minor issue with TimeUtils (#341) I was able to do away with the byteArray code and just use:

    `let decoded = try GBData(serializedData: srcPbf as Data)`

Performance is notably better. Decoding went from ~.4 to ~.25 seconds. Assigning decoded.serializedData() to a new object added ~.6 seconds ( down from ~.8 seconds)
