### ISSUE TITLE
Check/Fix Group Extension type names

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#352]
[Test_Extensions.swift](https://github.com/apple/swift-protobuf/blob/master/Tests/SwiftProtobufTests/Test_Extensions.swift) has a few lines with comments like:

> // Bug: This should be in SwiftTestGroupExtensions

Taking a quick look, it appears the question is about group extensions and picking up the correct name.

**Comment by thomasvl** [comment]
Looking at [unittest_swift_groups.proto](https://github.com/apple/swift-protobuf/blob/master/Protos/unittest_swift_groups.proto), the `extend {...}` doesn't actually scope those extensions, so I believe they should be named based on the file along.  If the `extend` were within a `message`, they yes, they should pick up the message's name in their naming.  So this may actually be WAD and we just need to clean up the comments.

**Comment by thomasvl** [comment]
Tagging as API Change since if there is a problem it changes the generated api surface and could break code if changed later.

**Comment by thomasvl** [comment]
@tbkka do you recall what prompted the comments on these?  They seem right, so I'm will to just remove the comments, but wanted to check before doing a PR for it.

**Comment by tbkka** [comment]
Yep, those comments were based on my misunderstanding of extension scoping.  Those comments should just be removed.
