### ISSUE TITLE
Investigate Any behaviors for consistency

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#359]
Capturing this so we look to double check the behaviors, at quick glance some parts seem like they aren't right -

- `hashValue` looks like it will come up with different values if an `Any` was initialized with a message vs. json vs. binary, even if the _message_ is the same in all cases.
- `_protobuf_generated_isEqualTo` looks like has a partial impl, but it needs to be consistent with `hashValue`.
- `_protobuf_generated_decodeField` seems like it is directly accessing `_value`, which may mean we don't output binary if the object was created from JSON input.
- The comments in a few places talk about delayed decoding of JSON to avoid doing it if the output is going to be JSON.  But when serialized binary is desired, because we travers once to collect sizes, we might actually do the JSON decode twice to generate the serialized form.

**Comment by tbkka** [comment]
Re: `hashValue` and `isEqualTo` -- I'm not convinced there is a completely robust solution here.  For example, if you decode one object from binary, another from JSON, and don't have the message available, then I don't think you can determine whether the objects actually represent the same value.  (Honestly, I suspect the best answer might be for `Any` to be neither `Equatable` nor `Hashable` and for any-valued fields to be completely omitted from equality tests and hash calculations.)

I'm not sure I follow your concern about `decodeField`.  Any objects override `decodeJSON` and `traverse()` forces the deferred decode as required, so the specific concern you have here should never arise.

I think you are right about the double-decode for JSON-to-binary transcoding, but I'm not sure how important it is.  I've long assumed that transcoding is actually the least common case, so we should optimize first for encode/decode to the object form and then for same-format recoding.  In both cases, the deferred decoding should be the best approach.

Another question to consider:  Should we defer TextFormat decoding as well?

**Comment by thomasvl** [comment]
Re leaving Any out of Equality/Hash - I'm a little worried there since I would fully expect someone to use Any within other messages (since it is the proto3 syntax replacement for Extensions).  So not having it in quality would greatly limit the value of Equality on messages in general.

Re decodeField - yea, sorry, fired this off to quickly, I was thinking about encoding, not decoding; so there isn't an issue here.

Re double-decode / transcode - yea, I'm not sure on this one either.  If a developer is storing the protos client side as data models/etc.  I would sorta hope they would do it as binary because they would be smaller and faster to encode/decode. But they might still want to send them to/from the server as JSON.  So in that sorta flow, the transcoding could be common.  I guess if this sorta flow is common, the issues with hash/equality could also come up if they are comparing data loaded from the store vs. returned by a server.

**Comment by tbkka** [comment]
Certainly, if we provide equality and hashValue implementations for Any, they should agree with each other.

For known types (WKTs and registered user types), the equality test should act as if we decoded the objects and compared the result.

For unknown types, I think it gets very complicated.

**Comment by thomasvl** [comment]
Capturing this thought, not sure if it is really valid, just wanted to record it as part of the discussion issue –

Since conversions can happen behind the scenes, accessing the `value` could actually be very expensive for some messages but not others (will depend on how they were created). And the value isn't cached since we can't mutate in the `get`.  So someone might expect the access to be cheap and it could end up on some more performance sensitive code path (main thread).

So while always converting could be a waste of work, it might move things into a more reliable/predictable code path.

**Comment by thomasvl** [comment]
#397 chipping at part of this.  As noted there, there doesn't actually seem to be a way to compare the `_message` within two `Any` objects at the moment due to how we've got them defined.

**Comment by thomasvl** [comment]
Question for folks - Since equality on an Any really only works if we have it in message form, does it make sense to add some api (_inflate()_? _normalize()_?) that takes an optional extension registry and does the decode into the internal _message_ state, so comparisons are then better defined?

My hesitation on waiting to see if it is a problem it could really suck for someone to debug, so by providing the API we could be providing the docs that help a developer avoiding the obscure bug it would cause.

**Comment by thomasvl** [comment]
Given no real feedback on the addition, I'm going to go ahead and close this out, and we can look at adding that helper in the future.
