### ISSUE TITLE
int32 fields should not be promoted to 64-bit when varint encoding

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#37]
See https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/ProtobufBinaryTypes.swift#L194.

If the number is negative, the 32-to-64 bit sign extension causes the number to be encoded with more bytes than it needs to be. There should be separate code paths for 32- and 64-bit varint encoding/decoding.

For example, refer to the Java implementation (selected arbitrarily) which has different code paths for [32-bit](https://github.com/google/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L1306-L1337) and [64-bit](https://github.com/google/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L1352-L1383) encoding.

**Comment by tbkka** [comment]
I'm a little confused.  I actually implemented 32-bit varints differently at one time, but changed it because of this:

   https://developers.google.com/protocol-buffers/docs/encoding

>  If you use int32 or int64 as the type for a negative number, the resulting varint is always ten bytes long – it is, effectively, treated like a very large unsigned integer.

**Comment by allevato** [comment]
That's interesting indeed. The Java and Objective-C implementations both have separate code paths for 32- and 64-bit integers though. @thomasvl, is this a mistake in the spec, or are the implementations doing something different?

**Comment by allevato** [comment]
Ok, the Java implementation also has this: https://github.com/google/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L1297-L1304

...where they handle negative numbers as a special case.

This was a side effect of the size calculation that I was doing, so there may have been a bug there where I was misapplying the logic for those negative numbers. False alarm—closing this issue.
