### ISSUE TITLE
Does the Google_Protobuf_Any registry work with modules/frameworks?

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#379]
Any project that needs to transform their Any usage between JSON/BinarySerialization will have to registry the mapping. So, given…

- Project A uses some protos as an impl detail, so it registers them.
- Project B uses some protos as an impl detail, so it also registers them.
- App XYZ comes along, and uses Projects A and B.

What happens if there was overlap between the protos in A & B?  Won't Swift modules successfully let both A & B have their own private copies of the message?  Yet how will the registry end up working?  The last one registered will _win_, meaning one library will never successfully be able to do the JSON->Binary conversion because the `Message.Type` registered will be wrong for them. App XYZ is the one that's going to run into this problem, not Project A or project B.

**Comment by thomasvl** [comment]
Tagging this with API change and Milestone 1 since I fear this is an API change to address it.

**Comment by tbkka** [comment]
> Any project that needs to transform their Any usage between JSON/BinarySerialization will have to registry the mapping.

There are two areas to worry about:

* Transcoding.  If you are transcoding, then the registered types are used only to decode/recode the data when you reserialize.  This is fundamentally no different than what C++ does -- it uses the registered descriptors to translate between JSON and binary encodings.  If there is a conflict (different protos with the same name), then it will not behave predictably.

* Packing/unpacking:  This doesn't use the registered types; it uses the type provided by the user at the point of packing/unpacking, so is unaffected by this.  (This should work correctly even if the Any is holding a deserialized object, as the unpack code serializes and deserializes if the provided type is not identical.)

**Comment by thomasvl** [comment]
Transcoding - The C++ is a little different in that they have descriptors that get _globally_ registered via module initializers (load time); and ensure there are no collisions around the message names they use.  So they can't really get into the case where they have >1 message class claiming a given type.  Even if it was the same class, just linked into different shared libs, things blow up just loading the two libraries into the same process space.  Swift's scoping of classes to modules seems to mean the binary can have the class twice because the end up being unique; pushing the problem to our registry.

We could also make registration assert/fail if the a given type is already registered.  Recrafts the problem into something where an App might have to go to their dependencies that share a proto and force them to come up with a way for them to share a module that provides it.

**Comment by tbkka** [comment]
> Swift's scoping of classes to modules seems to mean the binary can have the class twice because the end up being unique; pushing the problem ...

If it's truly the same class (with a copy in two different modules), it seems that the transcoded result should be the same regardless of which one actually ran the code.  (The decoded object isn't retained in this case, so it should not matter which copy of the class actually ran the decoding/encoding logic.)

But there is a concern here if the two modules were the same type but with different schema versions.  In that case, transcoding could fail since transcoding cannot preserve unknown fields.

> We could also make registration assert/fail if the a given type is already registered

This would seem to match the C++ behavior.  It would certainly be easier to relax this in the future if it proved unnecessary than to add this restriction if we started without it.

**Comment by thomasvl** [comment]
Closing this out, with https://github.com/apple/swift-protobuf/commit/0c527c9346b6972b650684e086fad7c79c9eafb5 (part of #389), register returns success/failure.  Using a passed registry would work better for the conflicting types that are different schema, but we're hoping this covers the needs for 1.x; and can revisit it at an API break if need be.
