### ISSUE TITLE
Set up some form of CI

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#38]
Maybe https://swift.org/continuous-integration can be leveraged, but something should likely get set up to test things as they land and to test PRs as they come in.

**Comment by fabiomassimo** [comment]
Would a free solution for open source projects, like Travis, be a valid option for you?

**Comment by timburks** [comment]
+1 for Travis. The grpc-swift Travis tests recently failed with the following:
```
/home/travis/build/grpc/grpc-swift/Plugin/Packages/SwiftProtobuf-0.9.29/Sources/SwiftProtobuf/Google_Protobuf_Any+Registry.swift:50:31: error: use of unresolved identifier 'DispatchQueue'
fileprivate var serialQueue = DispatchQueue(label: "com.apple.swift.typeRegistry")
```

The problem appears to be that "import DispatchQueue" is only necessary on Linux. Since Travis tests run on Linux, it's likely that this would have been caught here.

**Comment by thomasvl** [comment]
#973 just added GitHub actions for a linux build.

**Comment by thomasvl** [comment]
Closing this since the linux CI actions are now running on PRs.
