### ISSUE TITLE
Generating  Person.proto.swift - doesn't find any method/initializer/extension in this file - BUG

### ISSUE THREAD

**Issue by kuzdu** [apple/swift-protobuf#381]
Hi,

i use a standard person.proto from google - nothing special.

`syntax = "proto2";
message Person {
    required int32 id = 1;
    required string name = 2;
    optional string email = 3;
}
`

I installed a protobuf compiler with brew:
`1.ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
2.brew install protobuf-swift`

My version is 3.0.13

I created a Podfile like this
`source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  use_frameworks!

  target 'ProtobufTest' do
  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.24'
  pod 'ProtocolBuffers'
  end`

After that I generated the Person.proto.swift with
`protoc smart_access_messages.proto`

and add this one to my project.

I got 57 error, see image:
![protobuferror](https://cloud.githubusercontent.com/assets/7271766/23865705/caad590e-0816-11e7-8eff-33194305f586.png)

So I really don't know what I'm doing wrong. 

It's important for me that I have proto2 syntax.

**Comment by thomasvl** [comment]
So odds are you are getting a mix of versions at the moment.  We still haven't reached a "1.0" status making this a worse because things are changing.  If you pull directly from git (a label or trunk), and use that version of the protobuf plugin and library things will work, but from these errors, you seem to be using one version of the plugin and a different version of the supporting library.

**Comment by tbkka** [comment]
You need to check the versions:
```
$ protoc-gen-swift --version
```
will show you the version of the code generator.   You may need to adjust the version of the library to match that.  (0.9.24 is fairly old right now)

**Comment by tbkka** [comment]
The `SwiftProtobuf` code generator creates a `Person.pb.swift` file, not a `Person.proto.swift` file.  I believe you are using someone else's code generator with our library.  You either need to install the `SwiftProtobuf` code generator or use their library.

(`SwiftProtobuf` fully supports both proto2 and proto3 syntax.)

**Comment by kuzdu** [comment]
Thanks for reply.

Now I did everything from beginning:

my protoc version is 3.2.0 

I did this steps: 
`$ git clone https://github.com/apple/swift-protobuf.git`
`$ cd swift-protobuf`
`$ git checkout tags/0.9.28`
`$ swift build`

> This will create a binary called protoc-gen-swift in the .build/debug directory. To install, just copy this one executable anywhere in your PATH.

see image
![protobuf](https://cloud.githubusercontent.com/assets/7271766/23895251/6ef04664-08a5-11e7-88f4-1c1e6926edd3.png)

Then I execute (path: /Users/myUserName/Desktop/Tutorials/ProtobufTest)
`protoc --swift_out=. person.proto`

error:
>protoc-gen-swift: program not found or is not executable
>--swift_out: protoc-gen-swift: Plugin failed with status code 1.

When I do this
`./protoc-gen-swift --version` my response is protoc-gen-swift 0.9.28

What I'm doing wrong?

**Comment by thomasvl** [comment]
Is `protoc-gen-swift` really on your path?  if you just type `protoc-gen-swift -h` in a terminal what happens?

**Comment by kuzdu** [comment]
Unknown option -h

I think I haven't installed all/the right protobuf components. Is there any list which one I need?

**Comment by tbkka** [comment]
You need to put the `protoc-gen-swift` program into a directory that is part of your `PATH`.  You can see what directories those are:
```
$ echo $PATH
```
You can temporarily add a directory to your `PATH` with this command:
```
$ export PATH="/Users/myUserName/Desktop/Tutorials/ProtobufTest:$PATH"
```

**Comment by HieuLsw** [comment]
Hi, why each one run command to gen swift file from file .proc . In swift file import ProtocolBuffers instead of SwiftProtobuf???
