### ISSUE TITLE
Track plan for preserving unknown fields in Proto3

### ISSUE THREAD

**Issue by chmod007** [apple/swift-protobuf#382]
After much discussion, Google is changing the Proto3 spec to preserve unknown fields, in line with proto2 behavior.

https://github.com/google/protobuf/issues/272

https://docs.google.com/document/d/1KMRX-G91Aa-Y2FkEaHeeviLRRNblgIahbsk4wA14gRk/edit#heading=h.w8dtggryroj4

swift-protobuf should also support this.

**Comment by thomasvl** [comment]
Already done #347

**Comment by chmod007** [comment]
Excellent!
