### ISSUE TITLE
StorageClass: copy initializers instead of a copy method

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#388]
Comment by @tbkka on #387

>Bit of an aside: Is there any benefit to using copy initializers instead of a copy method like this? The method form needs to initialize every field before copying everything over; would a copy initializer avoid that?

**Comment by tbkka** [comment]
Actually, I don't think this is a 1.0 blocker.  It only affects how the generated struct uses the generated Storage object; we can change it later without any problems.
