### ISSUE TITLE
Automate/improve the dependency on google/protobuf

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#42]
The `Protos` directory contains a bunch of protos taken from [google/protobuf](github.com/google/protobuf/), the reality is they need to stay stay in sync (especially things for the plugin and the Well Known Types).

An ideal setup would likely to be try and pull them via a gitmodule so they always are in sync.  Short of that, something should be done to automate updating them.

Maybe once there is a CI system (#38), it could check/error if they need updating.

**Comment by tbkka** [comment]
The plugin and well known types definitely should be synced somehow.  A gitmodule approach  is certainly worth considering.  At one time, I had a Makefile target to copy the files from google/protobuf.

For the rest, I could go either way.  They could be synced or not.  Syncing them benefits from new cases added upstream, but diminishes their usefulness for generator testing.

**Comment by thomasvl** [comment]
PR #150 added a makefile target that will sync things.  Keeping this open as it would be nice to have things automatically done instead of a manual process.

**Comment by thomasvl** [comment]
Closing this since #1005 adds an easy way to check this.
