### ISSUE TITLE
Support other string encodings when decoding JSON from Data?

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#420]
If a user makes a request to some web service for some JSON, the API is likely to return `Data` rather than `String`. We currently support decoding directly from `Data`, but we assume that it's encoded as UTF-8.

Foundation's `JSONSerialization` has some interesting logic for decoding `Data` where it makes a best guess at sniffing out the encoding (looking for a BOM, or otherwise checking for zero-bytes in appropriate places), and then wraps the get-next-byte/index-advancing logic in such a way that the main parsing loop becomes encoding-agnostic. It supports UTF-8, UTF-16LE, UTF-16BE, UTF-32LE, and UTF-32BE.

We should look into doing this as well; I have some thoughts on the design rolling around in my head that I hope to code up soon.

This isn't 1.0 critical; it's additive and would not break public API.

**Comment by thomasvl** [comment]
Should we spin a 1.0 task to do a little encoding sniffing and add an error if the data appears to be an encoding we don't support?

**Comment by allevato** [comment]
The documentation at least states that the JSON is expected to be UTF-8 encoded, so I don't think it's *urgent* to do so.

If someone gets bitten by this, I think we can add the fix then, or better yet, have the rest of the work described by this PR done instead.

**Comment by tbkka** [comment]
According to the RFC, encoding sniffing for JSON is actually very simple.  The first character in a JSON-encoded data is always an ASCII character, and JSON only permits UTF-8, UTF-16, and UTF-32.  So you only need to look at the first four bytes and notice the pattern of zero bytes.

The RFC also makes the point that a lot of implementations only accept UTF-8, so I think the odds of someone hitting this are pretty low.

**Comment by allevato** [comment]
Right—I realize I forgot to leave the link to `JSONSerialization` where they do exactly that: https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSJSONSerialization.swift#L229

Adopting that should be fairly straightforward, if we want to do it.

**Comment by tbkka** [comment]
Almost 7 years later, and we've had no requests for this.  Maybe it's not worth the complexity?

**Comment by allevato** [comment]
It didn't seem critical enough to jump on when I filed the issue, so I think we can close it. It's reasonable that if someone wants to decode from JSON and they have text in a different encoding, they need to transcode it first. Especially since protobuf-JSON is more specific than just arbitrary JSON; it would be weird to write a backend that generated protobuf-JSON but encoded it in something other than UTF-8.
