### ISSUE TITLE
Update Documentation/API.md before 1.0

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#425]
[This file](https://github.com/apple/swift-protobuf/blob/master/Documentation/API.md) has become seriously out of date. Let's make sure it's accurate before 1.0.

**Comment by tbkka** [comment]
I updated a bunch of the method and initializer names so it's less-inaccurate.  Still needs a careful editing review, though.

**Comment by tbkka** [comment]
I believe this is accurate now.

**Comment by thomasvl** [comment]
@tbkka close this out then?

**Comment by tbkka** [comment]
Thanks for the reminder:  Fixed via #511.
