### ISSUE TITLE
Swift 3.1 support

### ISSUE THREAD

**Issue by mayur-gauswami** [apple/swift-protobuf#432]
After upgrading to xcode 8.3 there are build errors, e.g.:
- In ProtobufJSONDecoding.swift:
'Generator' has been renamed to 'Iterator'

**Comment by thomasvl** [comment]
What version of the sources are you using?  We're building master just fine.

**Comment by mayur-gauswami** [comment]
SwiftProtobuf (0.9.24)

**Comment by geegaset** [comment]
The same applies to 0.9.26

**Comment by tbkka** [comment]
I just tagged 0.9.29 which should have all the newest fixes for this.  Please try that.

**Comment by geegaset** [comment]
@tbkka now it works fine, thanks.

**Comment by tbkka** [comment]
Good.  I'll close this then.
