### ISSUE TITLE
Error generating swift after updating Xcode tools

### ISSUE THREAD

**Issue by davidmuzi** [apple/swift-protobuf#440]
After updating to Xcode 8.3, I am unable to generate messages.

- protoc-gen-swift built from 0.9.28
- Apple Swift version 3.0-dev (LLVM 440a472499, Clang e10506ae1c, Swift 395e967875)

Command:
`protoc --swift_out=. *.proto`

Output:
```
dyld: Symbol not found: __TWPVSS13CharacterViews13IndexableBases
  Referenced from: /usr/local/bin/protoc-gen-swift
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/protoc-gen-swift
--swift_out: protoc-gen-swift: Plugin killed by signal 6.
```

**Comment by thomasvl** [comment]
Trying doing a clean and then rebuild, that could be mixing old and new swift versions.  A there is now an unofficial 0.9.29 cut today for some of the latest updates.

**Comment by davidmuzi** [comment]
I've tried cleaning and building, but the build fails too. I'll create an issue for that

**Comment by davidmuzi** [comment]
After updating to `Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38)` and 0.9.29, I am able to build.

**Comment by johndpope** [comment]
it was working fine for last few days - now suddenly failing.

 -  xcrun swift -version
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)

**Comment by johndpope** [comment]
going to try brew upgrade.

**Comment by johndpope** [comment]
fixed it. https://github.com/johndpope/updater-for-macos

**Comment by senlinmuvs** [comment]
@davidmuzi +1
Did you fix it?

**Comment by edopelawi** [comment]
@davidmuzi, I just found the same issue, but I'm using Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42). Could you shed some light on this? 

Thanks!

**Comment by edopelawi** [comment]
Oh, turns out it's because I used RayWenderlich's precompiled protoc-gen-swift, which incompatible with my current Swift version.

Apologies for the rubber ducking!

**Comment by tbkka** [comment]
We should see about static linking protoc-gen-swift.  Otherwise, folks are going to keep running into problems with mismatched Swift system libraries.
