### ISSUE TITLE
How to set the visibility of the generated pb files?

### ISSUE THREAD

**Issue by aventurella** [apple/swift-protobuf#442]
For example, I am including the swift PB files into a framework, but the generator does not expose them publicly:

```
struct MyModel: SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {...}
```

Am I missing a flag or a setting? Is this even possible?

**Comment by thomasvl** [comment]
The generator option should cover it: [Visibility](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#generation-option-visibility---visibility-of-generated-types)

**Comment by thomasvl** [comment]
ps - cleaning up/improving our docs is one of thing things still on our 1.0 Milestone list so this is easier to find.  😄

**Comment by aventurella** [comment]
That did the trick! thank you!!

**Comment by thomasvl** [comment]
np, closing this out.
