### ISSUE TITLE
Problems with generated sources in multiple modules with Swift 3.1

### ISSUE THREAD

**Issue by gmosx** [apple/swift-protobuf#443]
I upgraded to Swift 3.1
Then I updated to swift-protobuf 0.9.29 
Compiled proto-gen-swift from the 0.9.29 sources and use the 0.9.29 version as a dependency.

Some protobuf files that were previously working correctly now generate *hundreds* of errors like:

```
/.../Work/Swift/Systems/****/.build/checkouts/***Protobuf-5523697989699535816/Sources/***Messages.pb.swift:1292:22: note: overloads for '!=' exist with these partially matching parameter lists: (Any.Type?, Any.Type?), (UInt8, UInt8), (Int8, Int8), (UInt16, UInt16), (Int16, Int16), (UInt32, UInt32), (Int32, Int32), (UInt64, UInt64), (Int64, Int64), (UInt, UInt), (Int, Int), (ContiguousArray<Element>, ContiguousArray<Element>), (ArraySlice<Element>, ArraySlice<Element>), (T?, T?), (T?, _OptionalNilComparisonType), (_OptionalNilComparisonType, T?), ((A, B), (A, B)), ((A, B, C), (A, B, C)), ((A, B, C, D), (A, B, C, D)), ((A, B, C, D, E), (A, B, C, D, E)), ((A, B, C, D, E, F), (A, B, C, D, E, F)), (LazyFilterIndex<Base>, LazyFilterIndex<Base>), ([Key : Value], [Key : Value])
    if snapshotEntry != other.snapshotEntry {return false}
                     ^
/.../Work/Swift/Systems/****/.build/checkouts/***-5523697989699535816/Sources/***Messages.pb.swift:1476:17: error: binary operator '!=' cannot be applied to two '[Proto****]' operands
    if trendbar != other.trendbar {return false}
       ~~~~~~~~ ^  ~~~~~~~~~~~~~~
```

Any help appreciated!

swift version: 3.1
protoc version: 3.2.0
protoc-gen-swift version: 0.9.29
MacOS: 10.12.4

**Comment by gmosx** [comment]
Also tried version 0.9.26 but I couldn't compile it with Swift 3.1

**Comment by yanniks** [comment]
Don't use a release but the master branch. That fixed if for me.

**Comment by gmosx** [comment]
How can I use the master branch?
Swift Package Manager needs a tagged repository, or am I missing something?

**Comment by yanniks** [comment]
Actually I don't know. As a workaround you could fork the repo and create your own tag for now.

**Comment by thomasvl** [comment]
Comparing 0.9.29 and master, there aren't any changes that likely would apply to something like this.  Can you create a reduced test case out of your proto files so we can try to recreate it?

**Comment by thomasvl** [comment]
> Some protobuf files that were previously working correctly now generate _hundreds_ of errors like:

Just checking you did regenerate the files with the update library?  We've done a bunch of naming/generation cleanup, and I just want to make sure this isn't a case of mixing files generated from the older version with the runtime from the newer version.

**Comment by tbkka** [comment]
It sounds like your build is still using the old SwiftProtobuf library for some reason.  I suggest you try `swift package clean` and rebuild to see if that fixes it.  You can also `cd .build/checkouts/SwiftProtobuf-*` and `git show` to see the exact commit of the SwiftProtobuf library that SwiftPM is using.

**Comment by gmosx** [comment]
No, I used swift package clean and I get the same errors.
Also

$ git show
$ git tag

shows the 0.9.29 tag

:(

**Comment by tbkka** [comment]
In the error messages you shared:
```
/.../Work/Swift/Systems/****/.build/checkouts/***Protobuf-5523697989699535816/Sources/***Messages.pb.swift:1292:22: note: overloads for '!=' exist with these partially matching parameter lists: (Any.Type?, Any.Type?), (UInt8, UInt8), (Int8, Int8), (UInt16, UInt16), (Int16, Int16), (UInt32, UInt32), (Int32, Int32), (UInt64, UInt64), (Int64, Int64), (UInt, UInt), (Int, Int), (ContiguousArray<Element>, ContiguousArray<Element>), (ArraySlice<Element>, ArraySlice<Element>), (T?, T?), (T?, _OptionalNilComparisonType), (_OptionalNilComparisonType, T?), ((A, B), (A, B)), ((A, B, C), (A, B, C)), ((A, B, C, D), (A, B, C, D)), ((A, B, C, D, E), (A, B, C, D, E)), ((A, B, C, D, E, F), (A, B, C, D, E, F)), (LazyFilterIndex<Base>, LazyFilterIndex<Base>), ([Key : Value], [Key : Value])
    if snapshotEntry != other.snapshotEntry {return false}
                     ^
/.../Work/Swift/Systems/****/.build/checkouts/***-5523697989699535816/Sources/***Messages.pb.swift:1476:17: error: binary operator '!=' cannot be applied to two '[Proto****]' operands
    if trendbar != other.trendbar {return false}
       ~~~~~~~~ ^  ~~~~~~~~~~~~~~
```

What is the type of the `snapshotEntry` and `trendBar` fields here?  Are they message types or enums or some other type?

**Comment by gmosx** [comment]
snapshotEntry:

```
...
message ProtoDepthSnapshotEntry {
    required uint64 volume = 1;
    optional uint64 bid = 4;
    optional uint64 ask = 5;
}

...
repeated ProtoDepthSnapshotEntry snapshotEntry = 3;
```

trendbar:

```
message ProtoTrendbar {
    optional uint64 low = 1;
    ...
    optional uint32 utcTimestampMins = 5;
}

...
message ... {
    repeated ProtoTrendbar trendbar = 2;
    ...
}
```

Hope this helps.

**Comment by thomasvl** [comment]
At first glance, those would appear to be pretty much the same as https://github.com/apple/swift-protobuf/blob/master/Protos/google/protobuf/unittest.proto#L136-L138, those cover the other message being defined in the same file or being defined in another file.

**Comment by gmosx** [comment]
The messages are defined in different files, indeed.

**Comment by thomasvl** [comment]
Like the protobuf_unittest_import.ImportMessage case linked before?

**Comment by gmosx** [comment]
Hmm, I think my proto files are missing the 'namespacing' e.g. something like:

**protobuf_unittest_import**.ImportMessage

**Comment by thomasvl** [comment]
If you can make two files you can attach that show this, it will help us understand what is happening.

**Comment by gmosx** [comment]
Can you provide an email address or something where I can send you the files privately?

**Comment by thomasvl** [comment]
> Can you provide an email address or something where I can send you the files privately?

Mine is on my github user page.  I can get them over to @tbkka also.  Thanks.

**Comment by gmosx** [comment]
Btw, please note I have the following setup:

Package `MyProtobuf`:

```
Sources/*.proto
Sources/*.pb.swift
```

I can **successfully** build this package with `swift build`

Then there is:

Package `MyClient`

which depends on the package `MyProtobuf`. When trying to build **this** file, I get the aforementioned errors.

**Comment by thomasvl** [comment]
So all the messages are in one package, but the error happen when using that package in another package?  Are you trying to expose the protos between packages or leave them internal to the first package?  We have a [Visibility](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#generation-option-visibility---visibility-of-generated-types) generator option, which may help, but it almost sounds like a case we don't have covered in our testing yet.

**Comment by gmosx** [comment]
I tried the --swift_opt flag:

```
protoc --swift_opt=Visibility=Public --swift_out=. *.proto
```

but I get the following error:

```
Unknown flag: --swift_opt
```

**Comment by thomasvl** [comment]
https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#changing-how-source-is-generated

> NOTE: protoc 3.2.0 does not recognize --swift_opt if you rely on protoc-gen-swift being found on the PATH. To work around this, you need to explicitly add the argument --plugin=[PATH-TO-protoc-gen-swift] to the command line, then the --swift-opt argument will be understood. If you are using protoc 3.2.1 or later, then this workaround is not needed.

**Comment by gmosx** [comment]
OK, tried with

```
protoc --plugin=/usr/local/bin/protoc-gen-swift --swift_opt=Visibility=Public --swift_out=. *.proto
```

it builds the first package (`MyProtobuf`) but produces the same errors when building the 'consumer' package(`MyClient`).

Anyway, I think I will have to wait for the 1.0 version and try again.

**Comment by tbkka** [comment]
I'm not sure how SwiftPM handles transitive dependencies, so I wonder if you might need `MyClient` to depend directly on `SwiftProtobuf` as well (so that it sees the protocols in `SwiftProtobuf` that define message equability).

**Comment by gmosx** [comment]
Unfortunately that didn't help either.

**Comment by thomasvl** [comment]
This is sounding like a Swift PM and/or issue with Swift Modules issues, where the default impls around found when protos are exposed via a module that pulls in another module that uses protos.  Tagging it with _help wanted_ since if someone can give us a test case setup, we should be able to help figure it out as well as see if we can make it some sort of a _test_ that we can put in `make check` so we ensure this stays working.

**Comment by thomasvl** [comment]
So I was looking at adding some _integration tests_ for this that would be two packages, one exporting protos and the second using them so we can support this, but the SwiftPM makes this really hard:

1. For the `dependencies` you can use a `.Package()` with an `URL` of `../..` to pull in _SwiftProtobuf_, but it still pulls needs a version.  [SE-0150](https://github.com/apple/swift-evolution/blob/master/proposals/0150-package-manager-branch-support.md) looks like it will help in that we can use `branch: "master"` to avoid pinning and working with what is currently in the tree.
1. The logical way I see to do this is create a directory with the integration test, and have that have two subdirectories: a _provider_ and _consumer_.  The _provider_ would depend on _SwiftProtobuf_ and expose a proto as part of what it declares public.  The _consumer_ would then use `Packages.swift` to pull in the _provider_ and have a simple Swift file to use some of the exposed proto classes.  The catch is the `URL` of the `.Pacakge()` seems to have to be a full git repo that can be cloned.  There doesn't seem to be a way to have this just point to a directory that isn't a git root also.

**Comment by gmosx** [comment]
Indeed, SE-0150 can't come soon enough

**Comment by thomasvl** [comment]
For future self (or anyone else that looks at this) – Reading the SwiftPM sources, they do a bunch of tests by using "Fixtures" that clone a directory, turn it into a git repo, and then run SwiftPM on it so they can unittest the behaviors/operations.  That's about the only way I can see to do tests for this as I realized even when we get `branch` support in Packages, it would be pinned, so while someone works on a a CL, the tests wouldn't be using the code the developer has locally (let alone locally committed to their branch).

**Comment by tbkka** [comment]
Retitled to reflect that the issue seems to be with using multiple modules

**Comment by thomasvl** [comment]
This hasn't gotten an update in a while and Swift has moved well past 3.1 at this point, should this just be closed out or is it still a concern?

**Comment by thomasvl** [comment]
Closing this since this project no longer supports Swift 3.x
