### ISSUE TITLE
Convenience initializers for all required properties

### ISSUE THREAD

**Issue by bridger** [apple/swift-protobuf#449]
Most of my messages have a few required fields. I'd like to make sure they are all specified in code rather than falling back to their default values. The easiest way to do this would be if there was a convenience initializer with all required fields. This wouldn't run into the issue from #86 because they wouldn't have default values for each field.

For example, I'd expect a convenience initializer to be generated for this message:

```
message WidePoint {
   required double x = 1;
   required double y = 2;
   required double w = 3;
}
```

```
public init(x: Double, y: Double, w: Double)
```

**Comment by thomasvl** [comment]
The [protobuf docs](https://developers.google.com/protocol-buffers/docs/proto#required_warning) some what strongly suggest avoiding required because it can cause problems in the proto needs to evolve.  So I'm not sure how much we want to promote them directly with library features.

However, Swift is different than other languages, you can create a Swift Extension within your code to provide these extra initializers yourself; so they don't have to be provided by the generated code.

**Comment by tbkka** [comment]
One of the questions we ran into in #86:  What order should the arguments be in the initializer?  In order of field number?  In the order they appear in the proto?

As @thomasvl pointed out, protobuf usage over the years has largely moved away from using `required`.  The new proto3 language dialect has entirely dropped the `required` modifier.

We did recently gain some checks on required fields -- the serialization should fail if required fields have not been set.  That should help with your use case, but I agree that it would be even cleaner to have a convenience initializer.

We'll certainly think about it....

**Comment by bridger** [comment]
Now that I've read more on required properties I've decided to switch to proto3 and not use them.  I will certainly need to write some app logic to validate these structs and make sure they are filled in. Already I need to write validation logic just to make sure they are logically consistent too, which can't be done with a static check. I'll go ahead and close out this feature request.

Food for thought would be how to make the code more maintainable when a new property is added. For example, a new property might be added which should be used in every case that a struct is created but the compiler won't help me find which code needs to be updated. If it changed the signature of the initializer then that would do it.

> In order of field number? In the order they appear in the proto?

If you do decide to do this, that order seems fine.
