### ISSUE TITLE
init(json:) missing?

### ISSUE THREAD

**Issue by vCrespoP** [apple/swift-protobuf#46]
The README.md file specifies in the quick example the following:

> JSON serializable: The .serializeJSON() method returns a flexible JSON representation of your data that can be parsed with the init(json:) initializer.

But when generating all the Swift code from a protoBuf (v.3) there's no initializer that has that parameter.

For instance:

```
syntax = "proto3";

message BookInfo {    
    int64 id = 1;
    string title = 2;
    string author = 3;
}
```

I would expect by reading the docs to get a method like:
```
let jsonDict: Dictionary<String,Any> = [
  "id": 42,
  "title": "The Swift Programming Language",
  "author": "Apple Inc."
]

let book = BookInfo(json: jsonDict) // try? BookInfo(json: jsonDict)
```
 that takes a serializable object (Dictionary?, Data?, Array?, Any?, ...) and fills all the inner properties found in the given JSON.

This is the generated code:
```
/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: DataModel.proto
 *
 */

import Foundation
import SwiftProtobuf


public struct BookInfo: ProtobufGeneratedMessage {
  public var swiftClassName: String {return "BookInfo"}
  public var protoMessageName: String {return "BookInfo"}
  public var protoPackageName: String {return ""}
  public var jsonFieldNames: [String: Int] {return [
    "id": 1,
    "title": 2,
    "author": 3,
  ]}
  public var protoFieldNames: [String: Int] {return [
    "id": 1,
    "title": 2,
    "author": 3,
  ]}

  public var id: Int64 = 0

  public var title: String = ""

  public var author: String = ""

  public init() {}

  public init(id: Int64? = nil,
    title: String? = nil,
    author: String? = nil)
  {
    if let v = id {
      self.id = v
    }
    if let v = title {
      self.title = v
    }
    if let v = author {
      self.author = v
    }
  }

  public mutating func _protoc_generated_decodeField(setter: inout ProtobufFieldDecoder, protoFieldNumber: Int) throws -> Bool {
    let handled: Bool
    switch protoFieldNumber {
    case 1: handled = try setter.decodeSingularField(fieldType: ProtobufInt64.self, value: &id)
    case 2: handled = try setter.decodeSingularField(fieldType: ProtobufString.self, value: &title)
    case 3: handled = try setter.decodeSingularField(fieldType: ProtobufString.self, value: &author)
    default:
      handled = false
    }
    return handled
  }

  public func _protoc_generated_traverse(visitor: inout ProtobufVisitor) throws {
    if id != 0 {
      try visitor.visitSingularField(fieldType: ProtobufInt64.self, value: id, protoFieldNumber: 1, protoFieldName: "id", jsonFieldName: "id", swiftFieldName: "id")
    }
    if title != "" {
      try visitor.visitSingularField(fieldType: ProtobufString.self, value: title, protoFieldNumber: 2, protoFieldName: "title", jsonFieldName: "title", swiftFieldName: "title")
    }
    if author != "" {
      try visitor.visitSingularField(fieldType: ProtobufString.self, value: author, protoFieldNumber: 3, protoFieldName: "author", jsonFieldName: "author", swiftFieldName: "author")
    }
  }

  public func _protoc_generated_isEqualTo(other: BookInfo) -> Bool {
    if id != other.id {return false}
    if title != other.title {return false}
    if author != other.author {return false}
    return true
  }
}
```

If I have missed any step it would be nice to update the readme, or if this feature is missing it would be wonderful to have it included as I had understood.

Thank you for your time,
Vicente Crespo.

**Comment by tbkka** [comment]
`.serializeJSON()` and `init(json:)` are actually defined in the `SwiftProtobuf` module.  You can see the actual implementation here:

   https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/ProtobufJSONTypes.swift#L777

Note that `.serializeJSON()` returns a String, not a dictionary.  A key principle of protobuf (and Swift, for that matter) is type-safe parsing, so we tend to not use constructs like `Dictionary<String,Any>`.

**Comment by vCrespoP** [comment]
I see! 

All clear then, thank you

**Comment by vCrespoP** [comment]
By the comment in #48 this may seem to be a problem I'm facing.

```
let book = BookInfo(id: ......) // initialize with the properties you want
let jsonBook = try? book.serializeJSON() 
let sameBook = BookInfo(json: jsonBook)
```

The last line does not compile and I understood it should.

**Comment by vCrespoP** [comment]
I'm including the swift protobuf with CocoaPods (v1.1.rc2).

It's reeeeeaaaally strange, as I have this in a single project, with only this dependency. I cleared everything out, removed derived data, ran again 'pod install' and now it's working.... 

:(

I can close now this issue, sorry for any inconvenience.

**Comment by tbkka** [comment]
`jsonBook` here is type `Optional<String>` because of the `try?`

You could instead do something like this:
```
   let jsonBook: String
   do {
      jsonBook = try book.serializeJSON()
   } catch {
      // handle failure
   }
   let sameBook = BookInfo(json: jsonBook)
```

There are other ways of handling the possible error here, of course.

**Comment by vCrespoP** [comment]
Yes yes I know. 

For the sake of simplicity I assumed the value was there when writing the code here, not taking care of error handling, or doing a guard/let, do/catch.

All clear 100% now, thank you so much both of you :D
