### ISSUE TITLE
Dealing with optionals/collisions with real values

### ISSUE THREAD

**Issue by vCrespoP** [apple/swift-protobuf#47]
Hello once again :)

I'm testing out protoBuf (v.3) and now optionals have been dropped. How do you suggest dealing with them when the default value collides with a possible real value?

For instance:
User has to input an amount of 0, which is different from not having set the field at all.

- Is there any mechanism built inside this framework/protocol buffers that allows something similar?
- Is the protoBuf definition limiting this _need_?
- Should that be handled from the UI/models knowing if the user enters a default value then we should actually have nothing? (Seems not really right, and Swift and optionals would personally be the way to go)
- Anything else?

Thanks a lot.

**Comment by thomasvl** [comment]
By _v.3_ I'm assuming you mean protobuf syntax _proto3_?  Both proto2 and proto3 syntax are supported and usable.  As the [protobuf overview](https://developers.google.com/protocol-buffers/docs/overview) mentions, both syntaxes are supported, so you you don't want the proto3 behaviors around zeros, you can use proto2.

If you do want to use proto3 syntax, there are a few options to deal with explicit zero values:
* You can out the field in a `oneof`, it will then property to tell which item in the oneof is set (or if
   non are).  That can then signal is the value is set to zero.

   ```protobuf
   message MyMsg {
     oneof has_value {
        int32 value = 1;
     }
   }
   ```
* You can use the [wrappers](https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto) Well Known Types.  By putting it in a message, it does nest it on the wire (in binary and JSON), but that provides a message that can be tested to see if it is present before accessing the value.

FYI - As mentioned on the [protobuf support page](https://developers.google.com/protocol-buffers/docs/faq), there is a [forum \(Google group\)](https://groups.google.com/forum/#!forum/protobuf) for general protobuf questions.  Most of what you are asking here isn't really specific to Swift and is generally about protocol buffers.

One last comment - The Swift library is still very young, so some of the what fields get exposed may well end up changing as we finish working out the best interfaces.  But the method mentioned above is generally how'd you'd capture this sorta information.

**Comment by vCrespoP** [comment]
Yes I meant proto3, exactly.

All right Thomas, thanks a lot for your response. I got the forum link correctly and I will head there for future inquiries about proto2/3 that are not Swift specific related, although I have to say the forums page is, let's say, not really great :D

I'm eager to see this framework grow as I see quite a lot of potential in it. Thanks for your work, effort and communication.

Cheers!
