### ISSUE TITLE
Don't see the buid directory

### ISSUE THREAD

**Issue by AndrewCarre** [apple/swift-protobuf#478]
Hi,

I am new to swift development(and its build system) and I cannot find the `.build/debug` directory. It built successfully so it's obviously something I am missing.

**Comment by thomasvl** [comment]
You're going to have to give us a little more info.  How'd you get the code?  How'd you do a build?  etc.

**Comment by AndrewCarre** [comment]
I found the build folder after checking out the tagged branch. It was a confusion on my part.
