### ISSUE TITLE
Extract some plugin building block into PluginLibrary

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#484]
For things like grpc, we should likely expose some minimal building blocks from the generator so folks don't have to duplicate out code.

- graph lookup/resolving
- swift type string generation

**Comment by tbkka** [comment]
This was my motivation for PluginLibrary.  I was planning to migrate facilities that other people might need to use into that library.  So far, it just contains the generated protobufs and a couple of general utilities, but I'd like to flesh it out by migrating the name-generation logic and graph lookup knowledge.

(I envision something similar to `Descriptor.cc` but tailored for the specific requirements of Swift code generation.)

**Comment by thomasvl** [comment]
Yup, I'm just gonna start in on that now.  It should actually help generation time also since we can revisit where we spend some of our time in in the current impl.

**Comment by thomasvl** [comment]
Once #524 lands, I believe that's everything someone writing a plugin is likely to need.  The Descriptor classes along with the Namer class should allow something to build on top of SwiftProtobuf without having to duplicate the type generation.
