### ISSUE TITLE
Add SwiftProtobuf to the Swift source compatibility suite

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#486]
The Swift team has created a manifest of real-world Swift projects that get regularly built against development snapshots to verify source compatibility. We should add this project.

https://swift.org/source-compatibility/#adding-projects

**Comment by thomasvl** [comment]
Is this still worth doing?

[Swift Unwrapped: 39: Source Compatibility Suite Woes](https://spec.fm/podcasts/swift-unwrapped/99551) talked about how project get disabled in the suite without being informed, and other issues.  So I'm not sure if it is/isn't worth adding.

I'm guessing #904 could have caused this project to have gotten disabled at some point.

**Comment by allevato** [comment]
Or would it have revealed a legitimate regression in the exhaustiveness checker? 🤔

**Comment by thomasvl** [comment]
I'm going to close this, since we haven't done it and from the linked Swift Unwrapped it isn't clear if it is worth it.
