### ISSUE TITLE
message fields don't have a has* property to go with them

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#49]
Message fields always return an instance, it is what allows one to dot into them to autocreate and assign something and to dot in and get default values.  But, that means there is no way to tell if they have been set.  There should be a has* method to tell if it has an explicit value or not.

**Comment by tbkka** [comment]
Yep.

I hope to sit down and expand GENERATED_CODE with a full rationale of how I think the various fields should be generated.  There are certainly cases where a `hasXyz` property will be required, and this is one of them.

**Comment by thomasvl** [comment]
I believe this got resolved with #102
