### ISSUE TITLE
Lock down visibility of as much of the runtime as possible

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#51]
A lot of types in the runtime library are public when they probably don't need to be. By making certain implementation details (especially extensions on public protocols) internal instead of public, we can be sure that those names won't collide with generated message members that happen to share those names. In other words, we significantly reduce the number of collisions we have to worry about, _and_ make sure that the user-facing API of a generated message is as small as possible.

**Comment by thomasvl** [comment]
Tagging as API changing since changing visibility adds/removes symbols.

**Comment by allevato** [comment]
Also, for things that have to be public as implementation details, move them into an extension of the `Internal` struct if possible (i.e., they're not generic or protocols).

**Comment by thomasvl** [comment]
I believe I've completely this, but before closing this out; @tbkka & @allevato can you both make a sweep of all the files/types to confirm what is public makes sense to you?

**Comment by tbkka** [comment]
I've gone through a `grep public` of the library code and it looks pretty good.

**Comment by allevato** [comment]
Ditto; I think we're done here for 1.0.
