### ISSUE TITLE
Use in App Store App

### ISSUE THREAD

**Issue by klaas** [apple/swift-protobuf#517]
How am I supposed to use swift-protobuf in an app that is submitted to the App Store?

During submission I receive the error message:
```
iTunes Store operation failed.
Invalid Bundle. The application bundle may not contain tools or frameworks provided by Apple, or using bundle identifiers in the 'com.apple.' namespace. Invalid bundle: SwiftProtobuf [com.xxx.yyy.pkg/Payload/My App.app/Contents/Frameworks/SwiftProtobuf.framework], with bundle identifier 'com.apple.protobuf.SwiftProtobuf'.
```

This seems to be a fair assessment and I don't want to submit any code that I compile with an Apple bundle identifier.

I renamed the swift-protobuf bundle identifier to a custom one and everything now works fine. But is this ok to do so?

**Comment by tbkka** [comment]
> I renamed the swift-protobuf bundle identifier to a custom one and everything now works fine. But is this ok to do so?

Yes.

**Comment by stonetip** [comment]
Perhaps it would be possible for Apple to use a different identifier for its open source projects, e.g. "com.apple-opensource.protobuf.SwiftProtobuf". I don't know what other issues that might cause but it would head off problems for people submitting apps who may never see this issue.

**Comment by thomasvl** [comment]
Sorry for the lack of update on this one, @tbkka is working on figuring out an answer on changing the default.  Interestingly, it seems to be something that hasn't come up for Apple before.

**Comment by tbkka** [comment]
The "swift.org" maintainers have kindly agreed to let us use 'org.swift.protobuf' as the base domain for our project.  We've changed the default bundle IDs accordingly.

@klaas: Thank you for pointing this out, and good luck with your app!

**Comment by stonetip** [comment]
Beautiful!

**Comment by klaas** [comment]
Great news! :-)
