### ISSUE TITLE
Code style/conventions (indentation, wrapping, etc.)

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#52]
Now that we have multiple people contributing to the repo, it would be a good idea to agree to a few code style/conventions so we can try to stay consistent across the repo (and because I just realized that I inadvertently checked in some tabWidth changes to the .pbxproj because I had to adjust the files I was working in to meet existing indentation).

I'd like to propose the following:

* 2 space indentation (matches Swift stdlib source)
* 100 character line length (Xcode's default wrapping isn't ideal, IMO. Swift stdlib uses 80, but I find that to be too short with Swift's descriptive naming conventions).
* One type per file, with the filename matching the type name, where reasonable. This one can be a little flexible, especially for small related types; for example, it's probably fine to have all the `ProtobufBinaryTypes` types stay in a single file, rather than a handful of very small source files.
* In a similar vein, if a file primarily contains an extension that adds protocol conformance to a type, name it `Type+Protocol.swift` so the content/purpose is easily glanceable. (As a new reader of the code, I've found myself bouncing between multiple files trying to hunt down certain extensions because the filenames don't directly map to the things in them.)

Feel free to disagree and/or add your own, and we can have a discussion and resolve this issue with the final decisions.

We don't necessarily have to reformat the entire repo at once, but as we make changes, it might be nice to do a "slow burn" and cover what we can.

Sadly, the `swift-format` tool that was added to the `swift` driver doesn't look like it made it into the Swift release that's in Xcode 8.0; it would have been nice to use it to automate things.

Thoughts?

**Comment by thomasvl** [comment]
👍  with the footnote and if `swift-format` does work well, then as soon as we get an Xcode GM with it bundled, I'd say we switch to always letting format do its thing (other languages that have a standard formatter, this seems to be a nice win for them)

**Comment by jcanizales** [comment]
> This one can be a little flexible, especially for small related types

Require a plural file name for this case? (Like `ProtobufBinaryTypes`).

This XCode plugin might be worth a try too: https://github.com/Jintin/Swimat

**Comment by allevato** [comment]
> Require a plural file name for this case? (Like ProtobufBinaryTypes).

👍

> This XCode plugin might be worth a try too: https://github.com/Jintin/Swimat

Unfortunately a lot of these plugins are unstable or busted in Xcode 8 😞. It's probably worth seeing if any of them work well enough, though.

**Comment by allevato** [comment]
@tbkka Do you want to chime in on any of these so we can lock it down?

**Comment by tbkka** [comment]
I'm hearing folks within Apple point to the Swift standard library as a good reference for general formatting style.

I also agree with @thomasvl that `swift-format` is probably the best answer if it works.
