### ISSUE TITLE
import Dispatch framework at header needs.

### ISSUE THREAD

**Issue by VladimirRoaming** [apple/swift-protobuf#523]
Dear 'swift protobuf' community, 
  Latest release of Package has issue with building on linux.
If you try to build, you will get error:  
`/mnt/Kraken/Kraken/.build/checkouts/swift-protobuf-runtime.git--7221025210804308591/Sources/SwiftProtobuf/DoubleFormatter.swift:85:57: warning: '+' is deprecated: Mixed-type addition is deprecated. Please use explicit type conversion.
        return _doubleToUtf8(Double(f), digits: FLT_DIG + 2)
                                                        ^
/mnt/Kraken/Kraken/.build/checkouts/swift-protobuf-runtime.git--7221025210804308591/Sources/SwiftProtobuf/DoubleFormatter.swift:89:49: warning: '+' is deprecated: Mixed-type addition is deprecated. Please use explicit type conversion.
        return _doubleToUtf8(d, digits: DBL_DIG + 2)
                                                ^
/mnt/Kraken/Kraken/.build/checkouts/swift-protobuf-runtime.git--7221025210804308591/Sources/SwiftProtobuf/Google_Protobuf_Any+Registry.swift:50:31: error: use of unresolved identifier 'DispatchQueue'
fileprivate var serialQueue = DispatchQueue(label: "com.apple.swift.typeRegistry")
                              ^~~~~~~~~~~~~
`

Solution is add `import Dispatch` in file ..Sources/SwiftProtobuf/Google_Protobuf_Any+Registry.swift 

Environment:
roaming@octadero-kraken-builder:/mnt/Kraken/Kraken$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
roaming@octadero-kraken-builder:/mnt/Kraken/Kraken$ swift -version
Swift version 3.1.1 (swift-3.1.1-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by thomasvl** [comment]
What version are you using?  The import was added on Mar 29th - https://github.com/apple/swift-protobuf/commit/ea4b43949df497963dfdf12c6ef6a984951c64eb#diff-184c4a870f84be381b03d312487342f5

It looks like that should have been in all of the 0.90x tags.

**Comment by VladimirRoaming** [comment]
Yes, I see, sorry my fault, has wrong number:
`        dependencies: [.Package(url: "https://github.com/apple/swift-protobuf-runtime.git", Version(0,9,29)),
`

**Comment by thomasvl** [comment]
No worries.  Thanks for the report.  @tbkka also just landed a few other linux fixes in the 0.9.902 tag cut last week.
