### ISSUE TITLE
protobuf message JSON stringify format error

### ISSUE THREAD

**Issue by macwish** [apple/swift-protobuf#557]
### Files:

file: Models.proto
```
// file: Models.proto

package M;

message ChunkInfo {
    uint64 order = 1;
    uint64 size  = 2;
    string crc   = 3;
}
```

file: test.swift
```
// file: test.swift

do {

    var chunkInfo   = M_ChunkInfo.init()
    chunkInfo.order = 1
    chunkInfo.size  = 1024
    chunkInfo.crc   = "bd15a475"

    //// Case A: (raise an error)

    // 1. JSON stringify
    let jsonString = try chunkInfo.jsonString()
    print("jsonString: \(jsonString)")
   
    // Output JSON string A:
    // > jsonString: {"chunkInfo":{"order":"1", "size":"1048", "crc":"9a723688"}

    // 2. send string to server

    // 3. decode message at server-side.
    // try to decode the message.
    // (in Ruby with " gem 'google-protobuf', '~> 3.2.0' " )
    message = M::ChunkInfo.decode_json(json_encoded_string)
    // An error raised:
    // > Error occurred during parsing: String specified for non-string/non-enum field: 'order'


    //// Case B: (works well)

    // 1. (Another way to) generate a JSON string
    let chunkInfo: [String: Any] = [
        "order": 1,             // an Int type
        "size" : 1024,          // an Int type
        "crc"  : "bd15a475"     // a String type
    ]
    let dict: [String: Any] = [
        "chunkInfo": chunkInfo
    ]
    let data = try JSONSerialization.data(withJSONObject: dict)
    let string = String(data: data, encoding: .utf8)!
    print("string: \(string)")

    // Output JSON string B: (not the same as Output-A here!)
    // > string: {"chunkInfo":{"order":1, "size":1024, "crc":"bd15a475"}}

    // 2. send string to server...

    // 3. decode message at server-side.
    message = M::ChunkInfo.decode_json(json_encoded_string)
    // It works well.

    print("message: #{message.order}")
    // > message: 1

} catch {
    print("an error: \(error)")
}
```

### Env
> Mac 10.11.6
> SwiftProtobuf 0.9.902
> libprotoc 3.3.0 ( $ protoc --version )
> 

BTW, Thank you, thanks all of you guys! Project "swift-protobuf" is a great job! 👍

**Comment by thomasvl** [comment]
At first look, the bug in in the ruby protobuf support.

[Protobuf JSON encoding](https://developers.google.com/protocol-buffers/docs/proto3#json) -

> proto3 | JSON | JSON example | Notes
> ------ | ---- | ------------ | -----
> int64, fixed64, uint64 | string | "1", "-10"| JSON value will be a decimal string. Either numbers or strings are accepted.

So what we are generating is correct, and they are just failing to properly parse it.  The [google/protobuf release page](https://github.com/google/protobuf/releases) includes a 3.3.0, so you might want to see if that fixes your issue.

**Comment by thomasvl** [comment]
Hm, looking at [google/protobuf conformance's failure_list_ruby.txt](https://github.com/google/protobuf/blob/master/conformance/failure_list_ruby.txt), it seems like there's a bunch of issues in the JSON support.  😦

**Comment by macwish** [comment]
@thomasvl Thank you Thomas. 

Follow the link: [Protobuf JSON encoding ](https://developers.google.com/protocol-buffers/docs/proto3#json) , you are right, proto3 "uin64" mapping to JSON "string".

Thanks for your pointing out the problem.

**Comment by tbkka** [comment]
Also please see google/protobuf#3013

**Comment by macwish** [comment]
Thanks @tbkka :smile:
