### ISSUE TITLE
Document swift_prefix

### ISSUE THREAD

**Issue by Arial7** [apple/swift-protobuf#562]
Hey guys 👋 

I have some protos in a package called `jump` and it generates my messages with a `jump_...` prefix, which I don't want (e.g. `Jump_User`). 

By digging around in the source, I found the `swift_prefix` option (thanks Github search). However, this option is not documented (it is mentioned in the README, but not explained), so I think someone should explain this option in the docs.

**Comment by tbkka** [comment]
Addressed in #634:  Added a discussion to `Documentation/API.md` that discusses how messages, enums, and enum cases get named, including `option swift_prefix` and the stemming support for enum cases.
