### ISSUE TITLE
documentation on parseFromBytes from binary wire format / .pb files

### ISSUE THREAD

**Issue by johndpope** [apple/swift-protobuf#572]
I've skimmed over documentation but couldn't see any obvious pointers on this.
Perhaps / need to update readme (if this is possible).

Here is what I'm trying to do

this proto file 
https://github.com/tensorflow/tensorflow/blob/799e31f3840c21322e380e1ec6e5bacb95d016fa/tensorflow/core/framework/op_def.proto

marries up with this  text file / it's not json. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt

I run some command to encode  it into a .pb file

   protoc \
      --proto_path=serving \
      --encode=tensorflow.OpList \
      --proto_path serving $opdef_file_path \
      < ./tensorflow/tensorflow/core/ops/ops.pbtxt > ops.pb

I now have .pb file. 

can I use this library to read / parse the .pb file in conjunction with .proto file?
if so how. 

N.B. I already have the generated protobuffer file spat out from protoc. 

https://github.com/nubbel/swift-tensorflow/blob/33c35daa3a794bd2b351e98084d58d6092751c1e/SwiftGenerated/tensorflow/core/framework/op_def.pb.swift

**Comment by thomasvl** [comment]
If you generate from a more current release, you'll find we've added some comments to help point folks in the correct direction.  [Here is an example](https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/duration.pb.swift#L116-L119).

The docs also have a [basic overview](https://github.com/apple/swift-protobuf/blob/master/Documentation/API.md#message-api) on the api with some comments.

What you are basically after is likely the info in [`Message+BinaryAdditions.swift`](https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/Message%2BBinaryAdditions.swift)

Having said all that, any specific you can give us to help better improve the docs would be welcome, we know they have a long way to go.  Docs are always one of the hard things for the people working on the code as we know it and aren't always sure what needs to be called out.

**Comment by johndpope** [comment]
looking for something exactly like this command
https://github.com/alexeyxo/protobuf-swift

<img width="762" alt="screen shot 2017-05-31 at 11 16 32 am" src="https://cloud.githubusercontent.com/assets/289994/26639497/f88e2640-45f2-11e7-9586-dd2b89caeeb3.png">

**Comment by johndpope** [comment]
ah....
trawling through repo 
https://github.com/apple/swift-protobuf/search?utf8=%E2%9C%93&q=deserialize&type=

High-performance binary serialization: The .serializedData() method returns a Data with a compact binary form of your data. You can deserialize the data using the init(**serializedData**:) initializer.

it would help if there was an example as above.

**Comment by thomasvl** [comment]
Just `let msg = MyMessage(serializedData: bytes)`.

The docs I linked before have a little of that info.

**Comment by johndpope** [comment]
I'll close this - but consider adding this to readme. it's not so clear.

**Comment by tbkka** [comment]
@johndpope:   I took a stab at rewriting the README to make this basic information clearer.  What do you think of this version?

https://github.com/tbkka/swift-protobuf/blob/tbkka-readme-quickstart/README.md

**Comment by johndpope** [comment]
nice. thanks. my only critique  would be a tiny note restoring from  .pb /data bytes file.

**Comment by tbkka** [comment]
FYI:  The Quick Start focuses on the most common cases (binary and JSON), but we also support the Protobuf Text format (your `.pbtxt`) directly.  So you shouldn't need to convert it to binary format, just read the contents into a string in memory and then decode the text data:
```
  let pbtxt = try NSString(contentsOfFile: filename, encoding: String.Encoding.utf8.rawValue)
  let msg = try MyMessage(textFormatString: pbtxt)
```

**Comment by johndpope** [comment]
nice.

**Comment by tbkka** [comment]
Just for completeness, I believe this is the equivalent for binary protobuf data:
```
   let fileUrl = URL(fileURLWithPath: filename)
   let fileData = try Data(contentsOf: fileUrl)
   let msg = try MyMessage(serializedData: fileData)
```

**Comment by johndpope** [comment]
let pbtxt = try String(contentsOfFile: filename, encoding: .utf8)
  let msg = try MyMessage(textFormatString: pbtxt)
