### ISSUE TITLE
Question:  Using Objective-C protobuf and SwiftProtobuf in same project?

### ISSUE THREAD

**Issue by ukpOnline** [apple/swift-protobuf#578]
Hi,

I am working with project which had implemented Protobuf in objective-c, currently I would like to add Swift Protobuf into our project. While integrating i getting few errors.
So kindly provide a sample project which integrated the same.

**Comment by thomasvl** [comment]
You can use the ObjC protos from Swift.  That way you only have to link one protobuf library.  Is there a specific reason you are trying to use both libraries in a single binary?  I'm also not sure it is something we really would want to encourage.

**Comment by tbkka** [comment]
What errors are you getting?

**Comment by cameronehrlich** [comment]
@ukpOnline this example from google really helped me: https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/speech/Objective-C/Speech-gRPC-Streaming

**Comment by thomasvl** [comment]
Closing this out since there doesn't seem to be an issue here vs. just a question and there hasn't been activity in a while.
