### ISSUE TITLE
Improve JSONDecodingError

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#581]
On client devices most JSON decoding errors will simply be "give up" types of cases.  But some applications might want to log the error and report it back to a server via some metrics/usage channel.

In server uses, being able to get more details about bad inputs from clients will likely help debug the clients as well as for better server side logging to help detect DoS attacks vs. bad clients.

So…

Currently JSONDecodingError provides no real context of what went wrong.  Some of them can easily include the sub part of the JSON that was bad (`.malformedDuration`, `.malformedTimestamp`, `.unrecognizedEnumValue`).  In almost all cases, also including a line number/column number (or atleast offset into the blob) being parsed would likely help.

**Comment by mustiikhalil** [comment]
Is this issue still open? and do you want help with it?

**Comment by thomasvl** [comment]
Yes, still open.  Adding associated values for the additional context is what would be useful.

**Comment by mustiikhalil** [comment]
Okay, I’ll work on it during the weekend 😁

**Comment by thomasvl** [comment]
`main` has gotten the infrastructure for a new error model that won't be api breaking, so new errors can have more details. However moving existing errors to that new model was counted as api breaking. So I'm closing this off as we won't actually evolve `JSONDecodingError`, but at some future point with 2.0 work, the existing errors could be given more context like this.
