### ISSUE TITLE
Does it support iOS8?

### ISSUE THREAD

**Issue by lazyjean** [apple/swift-protobuf#595]
I found that, this framework use Data to store binary data, but this data type is an iOS 10+ api

**Comment by muukii** [comment]
@lazyjean 
Which tag do you use? 
I've used 0.9.902. And it works on iOS9+.

**Comment by thomasvl** [comment]
> I found that, this framework use Data to store binary data, but this data type is an iOS 10+ api

What makes you say `Data` is an iOS 10+ api?

[Apple's docs on Data](https://developer.apple.com/documentation/foundation/data) says:

> _SDKs_
> 
> iOS 7.0+
> macOS 10.9+
> tvOS 9.0+
> watchOS 2.0+
> Xcode 8.0+

If you hit a specific problem, please open an issue with the details.

**Comment by lazyjean** [comment]
Thanks a lot. I think Apple make some mistake on Xcode internal Documentation

**Comment by thomasvl** [comment]
If you find that spot again, it might be worth filing a Bug Report with Apple for their docs.

**Comment by lazyjean** [comment]
document of xcode9 has fix the mistake
