### ISSUE TITLE
Generate as class

### ISSUE THREAD

**Issue by j70** [apple/swift-protobuf#609]
Provide an option to select whether to generate **Message** types as classes or structs, as of now everything is generated as structs. In some situations there may be a need to use the swift's nature of passing the class instances as references.

**Comment by thomasvl** [comment]
Duplicate of #194 

See the other issues.  This would be a non trivial thing to support as it would take completely different generation as well as different runtime support.

**Comment by tbkka** [comment]
If you need class objects in order to interoperate with Obj-C frameworks, you might consider using Google's Obj-C implementation of protobuf.
