### ISSUE TITLE
When converting a certain byte sequence, python protobuf works, swift-protobuf does not

### ISSUE THREAD

**Issue by EdenShapiro** [apple/swift-protobuf#618]
My system: OSX 10.11.6
Swift version: Apple Swift version 3.0.1
protoc compiler: libprotoc 3.3.0
swift-protobuf version: v0.9.26 (commit 118dbd3f91127cd9b85fc4160637ba1e92358335)
Python version: 3.6.1

The proto files I'm using are in proto2 syntax. All of the generated swift proto files work as expected and are able to be instantiated from the data I get back from the server, except for one. 
The problematic proto definition looks like this:
```
message SubscribeToFriendsResponse {  
	optional uint32 max_friends = 1;  
	optional uint32 max_received_invitations = 2;  
	optional uint32 max_sent_invitations = 3;  
	repeated Role role = 4;  
	repeated Friend friends = 5;  
	repeated invitation.Invitation sent_invitations = 6;  
	repeated invitation.Invitation received_invitations = 7;  
}
```
For reference, [here](https://github.com/EdenShapiro/bnet-protos/tree/master/bnet) are the rest of the proto definitions.
I've been working with swift protobuf but also python protobuf, which is where this gets strange. With the generated python protobuf files, I am able to take the data returned by the server and instantiate a protobuf object, like so (forgive the long data sequence, but it's using this sequence that the problem arises):
```python
def testing_function(self):  
    bytes_from_server = [8, 200, 1, 16,  [deleted for user privacy]]  
    data = bytes(bytes_from_server)  
    body = proto.SubscribeToFriendsResponse()  
    body.ParseFromString(data)  
    print body  
```
This function results in a properly instantiated python protobuf object, SubscribeToFriendsResponse, and the printed result looks like this:
```
max_friends: 200
max_received_invitations: 200
max_sent_invitations: 200
role {
  id: 1
  name: "battle_tag_friend"
}
role {
  id: 2
  name: "real_id_friend"
}
friends {
  id {
    high: 720575
    low: 1110
  }
  role: 1
  privileges: 1
}
... 
(I can link to full output if desired)
```
 
Now, with that exact *same* long byte sequence returned by the server and using that *same* protobuf object, but in Swift instead of python, I get a schema mismatch error. Here is that same function, but in swift:
```swift
func testingFunction(){
    let bytesFromServer: Array<UInt8> = [8, 200, 1, 16, ...]  
    let data = Data(bytes: bytesFromServer)  
    do {  
           let response = try Bnet_Protocol_Friends_SubscribeToFriendsResponse(protobuf: data)  
           print("test worked: \(response)")  
     } catch let e {  
           print("Error: \(e)")  
     }  
}  
```
This results in:  
`Error: schemaMismatch`  

It seems like it is something particular to this byte sequence, as I've instantiated a SubscribeToFriendsResponse object (in both python and swift) and manually set all of the properties to try to represent the same byte sequence once serialized. Once serialized, it does not result in the same byte sequence that the server returns. However I *am* able to re-instantiate the proto object from the byte sequence I produced, both the python SubscribeToFriendsResponse and the swift SubscribeToFriendsResponse (with the exact same byte sequence). So something about *this* afore-pasted byte sequence is causing the python protobuf to work but the swift one to result in a schema mismatch. Any ideas? One idea that came to me as I'm writing this is that there may be an issue converting special characters. I'm going to look into it but I wanted to post this anyway since it's an issue regardless.

**Comment by tbkka** [comment]
0.9.26 is very old; a *lot* of things have been changed and fixed since then.

Could you try a newer version?

**Comment by tbkka** [comment]
Are you sure you're using the same proto definitions everywhere?  It looks like your server has a different idea of Friends than you do:

Here's a tear down of the first "friends" object in your sample message:
```
42, 31,   // Field 5, 31 bytes ("friends" in your message above)
    // Field 2, 18 byte subobject ("id" field of "Friend" object, has two 8-byte fields
    10, 18, 9, 0, 0, 0, 0, 0, 0, 0, 1, 17, 9, 242, 16, 0, 0, 0, 0, 0,
    // Field 3, 1 byte, value [1] ("role" field of "Friend" proto)
    26, 1, 1,
    // Field 4, value 1 ("privileges" field of "Friend" proto)
    32, 1,
    // Huh?  Field 6 here holds a large number value.  Friends message expects field 6 to be a string
    48, 145, 166, 180, 193, 5,
```

Some other protobuf implementations treat field type mismatches like this as "unknown" fields, but SwiftProtobuf is not forgiving of this type of mismatch.  (I've personally been bitten too many times when things like this turned out to be real errors.)

**Comment by EdenShapiro** [comment]
Okay, updated to 0.9.904 and regenerated the swift structs. Have a lot of errors to fix in the project (you're right, a lot *has* changed), but will report back when I'm able to run it. What happened to serializedProtobufSize()?

**Comment by tbkka** [comment]
> What happened to serializedProtobufSize()?

As with many other things, we've made that internal for now, since we want our v1 release to only expose things we're absolutely positive won't ever change.  We'll expose more stuff as we go forward.

For anything you were relying on that has become internal:  Please file an Issue here explaining how you were using it.  The more we understand your usage, the better job we can do of exposing things that really make sense to everyone.

**Comment by EdenShapiro** [comment]
Welp, that did it. Whatever the bug was, it's been fixed since the latest version. That'll teach me not to update my version regularly 😓

**Comment by tbkka** [comment]
Glad to hear it's working for you!
