### ISSUE TITLE
Swift proto file extension values empty, data showing up in unknown storage

### ISSUE THREAD

**Issue by EdenShapiro** [apple/swift-protobuf#622]
My system: OSX 10.11.6
Swift version: Apple Swift version 3.0.1
protoc compiler: libprotoc 3.3.0
swift-protobuf version: v0.9.904

The proto files I'm using are in proto2 syntax. The proto definition I am having an issue with looks like this:
```
message ChannelState {
	enum PrivacyLevel {
		PRIVACY_LEVEL_OPEN = 1;
		PRIVACY_LEVEL_OPEN_INVITATION_AND_FRIEND = 2;
		PRIVACY_LEVEL_OPEN_INVITATION = 3;
		PRIVACY_LEVEL_CLOSED = 4;
	}

	optional uint32 max_members = 1;
	optional uint32 min_members = 2;
	repeated attribute.Attribute attribute = 3;
	repeated invitation.Invitation invitation = 4;
	optional uint32 max_invitations = 5;
	optional uint32 reason = 6;
	optional PrivacyLevel privacy_level = 7 [default = PRIVACY_LEVEL_OPEN];
	optional string name = 8;
	optional string delegate_name = 9;
	optional string channel_type = 10 [default = "default"];
	optional fixed32 program = 11 [default = 0];
	optional bool allow_offline_members = 12 [default = false];
	optional bool subscribe_to_presence = 13 [default = true];
	extensions 100 to 10000;
}
```
and in another file:
```
message ChannelState {
	optional EntityId entity_id = 1;
	repeated FieldOperation field_operation = 2;
	optional bool healing = 3 [default = false];
	extend .bnet.protocol.channel.ChannelState {
		optional ChannelState presence = 101;
	}
}
```
After this ChannelState object is instantiated from serialized data, calling the getExtensionValue(ext:) on it returns nothing, the _protobuf_extensionFieldValues is empty, and seemingly so are many of channelState's properties. The data is there, as the debugDescription prints out all the appropriate data, but instead of being in the appropriate fields, it appears to all be inside unknownFields, as channelState.unknownFields.data contains a lot of bytes. The description for unknown storage says:

> /// Contains any unknown fields in a decoded message; that is, fields that were
> /// sent on the wire but were not recognized by the generated message
> /// implementation or were valid field numbers but with mismatching wire
> /// formats (for example, a field encoded as a varint when a fixed32 integer
> /// was expected).

which leads me to believe there is something wrong with the way the proto files are being compiled to their swift structs, as all of this works without a hitch in my python implementation of this, but maybe I'm missing something.

**Comment by thomasvl** [comment]
The "and in another file:" part is a little odd.  As you have that written, that would be declaring another message with the name ChannelState.  Normally it would be an `extends ChannelState` - https://developers.google.com/protocol-buffers/docs/proto#extensions

**Comment by thomasvl** [comment]
Oh wait, there is an extension within that to the other ChannelState…  rereading.

**Comment by EdenShapiro** [comment]
Yeah, that might be confusing. Let me upload the proto files I'm using and link them.

**Comment by thomasvl** [comment]
Ok, after rereading, it's a little hard to tell what you are asking for/doing.  With what you have provided…

I'm assuming the first `message ChannelState {...}` is the `package bnet.protocol.channel`.

Then the second `message ChannelState {...}` defines a new message, but also declares one extension field (`presence`) on the other message.

When you read the binary, which ChannelState class are you using?  Also, are [passing](https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/Message%2BBinaryAdditions.swift#L72) the ExtensionMap generated from that second file?  If you don't provide it, the extension can't be looked up, so the field will be unknown.

**Comment by thomasvl** [comment]
ps - the `[PACKAGE]_Extensions` value in the second file in will be of type `SwiftProtobuf.SimpleExtensionMap` and can be used for all the extensions defined within that file.

**Comment by EdenShapiro** [comment]
Ah, okay, so I just wasn't using the extension map correctly. Didn't realize I'd have to use a separate method to instantiate, since in the python code the extensions are just something you can reference after the fact. And then when I thought "maybe I can try this `serializedData: Data, extensions: ExtensionMap?` method, I couldn't figure out what exactly would be the `ExtensionMap`. Thanks!

**Comment by thomasvl** [comment]
Yea, some languages have the concept of a static initialization code, so that is used to register all extensions linked in, but Swift doesn't have that, so it has the follow the model where there are manually registered and/or a local mapping is provided.

The section on extensions in our Documentation directory likely needs some more detail to help with this.  🙁

**Comment by AquaGeek** [comment]
(For anyone who happens to find this issue in the future and was confused like I was about the solution:)

As mentioned above, there will be a `[YOUR_PACKAGE_NAME]_Extensions` generated for you that includes all the extensions defined in the .proto file. Pass that when attempting to decode:

```swift
guard let message = try? SomeMessageYouAreTryingToParse(
    serializedData: data,
    extensions: [YOUR_PACKAGE_NAME]_Extensions  // <- This is the important part
) else { … }
```
