### ISSUE TITLE
Verify behavior of zero values in wrappers.proto

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#64]
When I started looking at removing the hand-generated protos, I started with wrappers.proto and ran into some behavior that we need to verify.

The hand-generated protos have the `value` property as a Swift optional ([example](https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/Google_Protobuf_Wrappers.swift#L86)). The JSON serialization logic then says "if the value is unset, write `null`, else write the value".

However, since wrappers.proto is proto3, there should be no distinction between "not set" and zero/empty. The property should not be optional.

So, we need to figure out what the spec/other languages/the conformance tests are doing here. If the value is zero/empy, does it get serialized to JSON as zero, or null?

For now I'll duplicate the existing behavior to avoid breaking the tests, but we need to double-check this.

**Comment by thomasvl** [comment]
I haven't looked at the code, but this might be because this is where some remapping between the proto object model and swift happens.  If you look at what wrappers defines a bunch of messages that wrap a basic type.  I think the comment/code intent is likely capturing the fact that where these messages are used, they could be unset (since they are a message).  If the message is unset it might go as null, but if it is set, the the value from the single field goes as json but not wrapped in the object.

```protobuf
message foo {
  google.protobuf.DoubleValue value = 1;
}
```

So if `foo.value` isn't set, maybe that uses `Null`:

```json
{
  "value": null
}
```

But when it is set, the value goes out:

```json
{
  "value": 12.3
}
```

?

Anyway, I'll have to dig back through the docs to confirm.

**Comment by tbkka** [comment]
Unfortunately, I can't find my notes from when I changed this to optional.  I do recall spending a lot of time trying to satisfy all of the requirements for `null` handling.  The test cases reflect my understanding of the spec.

**Comment by tbkka** [comment]
From https://developers.google.com/protocol-buffers/docs/proto3#json

> Wrappers use the same representation in JSON as the wrapped primitive type, except that null is allowed and preserved during data conversion and transfer.

In particular, I read this to say that `{"wrappedFloatField": null}` has to actually store a `Google_Protobuf_Float()` that will serialize to a JSON `null`.  (For regular proto3 messages, a `null` gets treated the same as an omitted field.)  That must be represented differently than a `Google_Protobuf_Float()` with a value of `0`.

**Comment by allevato** [comment]
Now that the conformance tests are more easily runnable, it looks like the current implementation is wrong based on its output:

```
ERROR, test=Required.JsonInput.RepeatedInt32Wrapper.JsonOutput: Output was not equivalent to reference message: added: repeated_int32_wrapper[0].value: 1
deleted: repeated_int32_wrapper[1]: { value: 1 }
. request=json_payload: "{\"repeatedInt32Wrapper\": [0, 1]}" requested_output_format: JSON, response=json_payload: "{\"repeatedInt32Wrapper\":[null,1]}"
```

We should be outputting 0/false/"" instead of null. The change is simple and fixes all of the broken wrapper conformance tests without breaking any new ones; PR coming shortly.
