### ISSUE TITLE
why  optional not work?

### ISSUE THREAD

**Issue by ondev** [apple/swift-protobuf#644]
I have declare my message like:
`syntax = "proto3";
message MessageModel {
    string messageId = 1;
    uint32 userId = 2;
}
`

the generated swift class like
var messageID: String = String()
var userID: UInt32 = 0

why have a default value,  is optional, the value should nil

**Comment by allevato** [comment]
Please see the discussion in #522 about why the decision was made to not use Swift optionals—there are a number of reasons that Swift's `Optional` type and protobuf's `optional` fields do not map well to each other.
