### ISSUE TITLE
Trouble compiling protos within nested tree

### ISSUE THREAD

**Issue by EdenShapiro** [apple/swift-protobuf#651]
My system: OSX 10.11.6
Swift version: Apple Swift version 3.0.1
protoc compiler: libprotoc 3.3.0
swift-protobuf version: v0.9.904

I have a tree of directories containing various proto files that are all interconnected, and haven't been able to find a way to extract all of them without putting them all in one directory and editing the protos themselves. I've written all sorts of scripts but keep getting one swift-protobuf error or another. The root directory is here https://github.com/EdenShapiro/bnet-protos/tree/master/new%20protos. Are there any go-to methods for doing this? Or any ideas?

**Comment by tbkka** [comment]
> ... keep getting one swift-protobuf error or another ...

Are these errors when you run `protoc`?
    If so, how were you running `protoc` before?  It should work the same for Swift, just using `--swift_out` instead of some other language option.

Or are you getting errors when you try to compile the generated code?

**Comment by EdenShapiro** [comment]
I'm getting errors running protoc. I'm a bit new to protocol buffers, but I'm running this script from the root of the nested directories (which I linked to above):
```
#!/bin/bash
set -e

BASEDIR="$(greadlink -f $(dirname $0))"
PROTO_DIR="$BASEDIR/new-protos-aug"
SWIFTPROTO_DIR="$BASEDIR/new-swift-protos-aug"

echo "Converting files from $PROTO_DIR into $SWIFTPROTO_DIR"

FILES=$(find $PROTO_DIR -type f -name "*.proto")
for proto in $FILES; do
	protoc -I=$PROTO_DIR --swift_out=$SWIFTPROTO_DIR $proto;
done
```
But I'm getting all these "import not found" errors (for example `Import "bgs/low/pb/client/global_extensions/field_options.proto" was not found or had errors.`) and proto not defined errors (for example `bgs/low/pb/client/account_service.proto:83:18: ".bgs.protocol.EntityId" is not defined.`)
I'm not sure how to compile all these protos that are dependent on each other and can't seem to find one another within the nested directory structure.

**Comment by thomasvl** [comment]
Like @tbkka mentions, the problems seem to be able using protoc in general and not specific to generating Swift.

General rule of thumb with protoc, you and a `-I` directive for each root director where proto imports should be resolve relative too (likely your `PROTO_DIR` here).  Then for the files you pass to protoc, you want those paths to be relative to one of the import dirs (the `-I` directives).  You can also pass multiple proto files at a time to speed up generation.

Try something like (assuming `SWIFTPROTO_DIR` ends up as an absolute directory):

```bash
cd $PROTO_DIR
protoc -I=. --swift_out=$SWIFTPROTO_DIR *.proto `find bgs -type f -name "*.proto"`
```

That way all the paths passed to protoc should match how they are on the import directives in the proto files themselves.

**Comment by EdenShapiro** [comment]
Thanks for the response. Turns out I think I'm actually just missing proto files. The extractor I used produced a lot of protos so I figured the missing ones in the error output just weren't being accessed properly. But it turns out they don't exist ¯\_(ツ)_/¯

**Comment by tbkka** [comment]
Good luck working that out!
