### ISSUE TITLE
Revisit WebSafe Base64 in JSON

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#653]
The conformance test has been updated to now check for this.

Looks like C++ defaults to trying to do WebSafe decode first, and then fall back to "normal" decode.

Looks like C++ also picked up encoding flag to request WebSafe generation (defaults to off).

**Comment by tbkka** [comment]
PR #656 fixes the decode side of this.

I don't have any immediate plans to add support for writing the alternate encoding.

**Comment by thomasvl** [comment]
> I don't have any immediate plans to add support for writing the alternate encoding.

Yea, I wasn't sure if it made sense, the fact that C++ seems to favor websafe decode was the part I found interesting.

**Comment by thomasvl** [comment]
Closing this out, since I don't think we're planning on directly adding support for encoding into websafe until there is a reason.
