### ISSUE TITLE
Generated server.pb.swift missing guard -> return.

### ISSUE THREAD

**Issue by sabiland** [apple/swift-protobuf#659]
```
guard let provider = self.provider else {
      assert(false) // the server requires a provider
        return // <--- this return statement is missing after auto generating pb files
    }
```

**Comment by thomasvl** [comment]
@sabiland did you open this on the correct project?  I'm not completely sure what you are referring to here.  This project doesn't directly generate anything for _service_ entries in _.proto_ files.  Did you mean to file against something else?  (grpc?)

**Comment by sabiland** [comment]
Yes, maybe I am mistaken. I created pb files with this tool: _protoc <your proto files>  --swift_out=. --swiftgrpc_out=._

**Comment by thomasvl** [comment]
What is the specific file name generated?  If it is `[something].pb.swift`, then is likely is from this project, if it has _grpc_ in the name, it is from the grpc project you used.

**Comment by thomasvl** [comment]
From the snippet, this seems to be https://github.com/grpc/grpc-swift/blob/1ef3b54deacccf9c683cf17a0d442b0b29c7fe66/Plugin/Templates/server.pb.swift#L116, so closing since it isn't for this project.
