### ISSUE TITLE
Properties renamed for proto3

### ISSUE THREAD

**Issue by gemedet** [apple/swift-protobuf#661]
The docs say that `hasXyz` properties are only generated for proto2 optionals, so it seems like proto3 fields don't need to be renamed. Using version 0.9.904, this:
```proto
syntax = "proto3";
message Foo {
    string bar = 1;
    string hasBar = 2;
}
```
results in:
```swift
var bar: String = String()

var hasBar_p: String = String()
```
There's no generated `hasBar`, so is there an option to prevent the renaming?

**Comment by thomasvl** [comment]
I'll have to go back and double check, but I don't think our renaming code checks if the files are proto2 vs. proto3 syntax when checking for a "has" or "clear" collision.

Also need to figure out if it would be confusing to only rename on the proto2 syntax case (if a developer is dealing with a message that has a field that comes from a file with the other syntax, they could see both sets of behaviors pretty easily.

**Comment by allevato** [comment]
IMO, having different naming schemes for proto2 and proto3 only has the potential to lead to confusion, especially as you said if proto2 and proto3 messages are mixed.

Given that the `has*` pattern exists throughout many of the protobuf implementations, I think it's reasonable to suggest that users not name their properties using that prefix because Swift isn't the only language where they would run into this problem.

**Comment by thomasvl** [comment]
Yup, the code that checks for these names doesn't currently factor in the syntax of the defining file to decide if there will be collisions on has/clear.

As mentioned and @allevato chiming in, the next question becomes should this not do the renaming.  There as been a few requests for having support for has even in proto3 syntax avoid having to use wrappers and directly support nullability of the fields when using JSON.  google/protobuf#1606 has a fair amount of the traffic on this; and while the current decision is no, [looks like](https://github.com/google/protobuf/issues/1606#issuecomment-281832148) the protobuf-team seems to imply this could get revisited based on need.

So at the moment, it seems like staying consistent and avoiding a potential rename in the future is the better idea.

**Comment by thomasvl** [comment]
Actually, I'll try to find it, I thought there was discussion of also including the has methods for fields in an oneof for both proto2 and proto3.  I think a few languages already do this, and Swift might be acting differently there.

ps - I believe the logic is in part for a proto2 syntax file it makes it safer to move a field into a oneof without breaking code; and for proto3 syntax file, it lets the oneof with a single field be an easier way to add presence for for an individual field without having to use a wrapper message which does have more api and wire overhead.

**Comment by gemedet** [comment]
It's good to know there's been discussion about this already. Based on xfxyjwf's comment, it doesn't seem like the protobuf-team is all that keen on bringing back field presence, since they deliberately dropped it for proto3.

If users are mixing proto2 and proto3, I'd expect them to be prepared for different naming schemes, but I can understand wanting to be consistent by default. What do you think about adding a `swift_opt` to turn off the renaming?

I'm interested in the oneof discussion. If the `has` properties do get included in proto3, why wouldn't they be the ones to get `_p` added?

**Comment by thomasvl** [comment]
> It's good to know there's been discussion about this already. Based on xfxyjwf's comment, it doesn't seem like the protobuf-team is all that keen on bringing back field presence, since they deliberately dropped it for proto3.

Unknown fields were also stripped during binary parsing for `proto3` and that got reversed with enough evidence at how it made things harder.   So while the current position seems to be against bringing any presence back, there's enough folks asking about it I'm hesitant to say the door is completely closed.

> I'm interested in the oneof discussion. If the has properties do get included in proto3, why wouldn't they be the ones to get _p added?

Consistency with the proto2 syntax `has` methods and consistency with the other languages.

**Comment by thomasvl** [comment]
Trying to search for _has_ and _oneof_ on the google/protobuf issues and the google group isn't letting me find the thread I think I've see before.  🙁

**Comment by gemedet** [comment]
No problem, thanks for looking!
