### ISSUE TITLE
Missing bytes in serializedData()

### ISSUE THREAD

**Issue by cqin5** [apple/swift-protobuf#672]
Our team had been using [protobuf-swift](https://github.com/alexeyxo/protobuf-swift) for some time and we wanted to give Apple's a try. 

We notice that two identical requests are serialized into Data differently, and to be exact, three bytes different.

Following strings are printed with `serializedData.map { String(format: "%02x", $0) }.joined()`

The serialized data with **protobuf-swift** that is working for us:
`0a3b080112001a0b713135407171712e636f6d22063131313131312a003204746573743a04746573744204746573744a04746573745001580160016801`

**swift-protobuf** that is not working for us: 
`____08011a____0b713135407171712e636f6d2206313131313131____3204746573743a04746573744204746573744a04746573745001580160016801`

It seems the request is missing bytes like `SOH`, `DC2`, and we are still trying to figure out what the first byte is.

**Comment by allevato** [comment]
Let's look at the second two blocks first: what got omitted was `1200` and `2a00`, which would be field numbers 2 and 5, length-delimited, each with a length of 0 bytes. In those cases, you don't have anything to worry about—it looks like protobuf-swift is serializing fields with empty data that it doesn't need to.

The first block, `0a3b` would correspond to field number 1 with the length-delimited wire format, followed by a length of 0x3b (59 bytes). That's exactly the number of bytes present after those first two in the hex string that you pasted.

Is this a nested message of some sort? That would explain why it's preceded by a field number and size. (It's also worth noting that the second pair of bytes, `0801`, corresponds to field number 1 with a varint value of 1, which is what makes me suspect nesting.) So, it's possible that the way you're calling swift-protobuf to serialize a message isn't compatible with what protobuf-swift was doing.

If you can show us any code/.proto definitions, that would help us figure out what's going on.

**Comment by cqin5** [comment]
Yes, we are indeed using a nested message. A `RequestMessage` that embeds an `oneof`:

`message RequestMessage {
    oneof msg {
        UserLoginRequest userLogin = 1; 
        UserLogoutRequest userLogout = 2; 
        ...
    }
}`

and we were trying to send a UserLoginRequest:

`
message UserLoginRequest {
    uint64 requestId = 1;  
    ...
}
`

**Comment by allevato** [comment]
The behavior that you described in your initial post is consistent if you:

* Serialized a `RequestMessage` containing a `UserLoginRequest` with swift-protobuf (and assuming it handles oneofs correctly)
* Serialized a `UserLoginRequest` directly using protobuf-swift

Can you show us the snippets of serialization code that you used in each case?

**Comment by cqin5** [comment]
I realized there was something written incorrectly on our end, that we weren't using the RequestMessage correctly. 

Thanks for the help and I'm going to close the issue!

**Comment by allevato** [comment]
Glad you got it resolved!

**Comment by thomasvl** [comment]
Just wanted to clarify one of @allevato comments:

> Let's look at the second two blocks first: what got omitted was 1200 and 2a00, which would be field numbers 2 and 5, length-delimited wire format, each with a length of 0 bytes. In those cases, you don't have anything to worry about—it looks like protobuf-swift is serializing fields with empty data that it doesn't need to.

The last part here (_it looks like protobuf-swift is serializing fields with empty data that it doesn't need to_) isn't completely right.  If a field is a message, and that sub message has no field set directly on it, the library has to write out the zero length delimited field to capture that the field in the parent message is set, but that no sub fields were set.

**Comment by allevato** [comment]
But is that the case here, given that protobuf-swift appears to be serializing it differently? Our testing and the conformance test suite surely verify something that fundamental?

We can't know for sure without seeing the original proto definition for `UserLoginRequest`, but I wasn't referring to any possible length-delimited message, just the ones present here.

**Comment by thomasvl** [comment]
Right, without seeing the proto definition and code filling in the object we can't say for sure.  I was just referring to the comment _it looks like protobuf-swift is serializing fields with empty data that it doesn't need to_, as I read the code (and what the conformance tests might also be checking), the library is never doing something that doesn't need too be done to be in spec.
