### ISSUE TITLE
Cocoapods install fails?

### ISSUE THREAD

**Issue by bmt22033** [apple/swift-protobuf#673]
I just tried to add the project to my Podfile using this line:

pod 'SwiftProtobuf', '~> 1.0.0'

When I run 'pod install --repo-update', I get the following error:

> Analyzing dependencies
> [!] Unable to satisfy the following requirements:
> 
> - `SwiftProtobuf (~> 1.0.0)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `SwiftProtobuf (~> 1.0.0)`.
> 
> You have either:
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
> 

If I remove the version 1.0.0 specifier, Cocoapods will install correctly with the previous release (0.9.905).

**Comment by thomasvl** [comment]
Oops, working on pushing the updated podspec.

**Comment by bmt22033** [comment]
That was fast!  Thanks.  :-)

**Comment by thomasvl** [comment]
Happened to be going through my email this morning when this came in.  😄

**Comment by thomasvl** [comment]
Podspec pushed.
