### ISSUE TITLE
Generated Code ignores integer field when value is 0

### ISSUE THREAD

**Issue by sunnypurewal** [apple/swift-protobuf#686]
OS: macOS 10.12.6
xcode 9.0 9A235
swift 4.0
SwiftProtobuf 1.0.0

Here is my .proto file:
```
syntax = "proto3";

message Test {
    int32 num = 1;
}
```

and the generated code contains the following:
```
    if self.num != 0 {
      try visitor.visitSingularInt32Field(value: self.num, fieldNumber: 1)
    }
```
This means that this field will be ignored by the serializer if it is 0. But 0 should be a valid value for integers. Am I missing something that is special about value 0?

**Comment by allevato** [comment]
In proto3, zero is the default value for numeric fields and the field is only serialized if it is non-zero.

If you need that behavior, consider using proto2 which does handle explicit field presence.

**Comment by tbkka** [comment]
Here's how I remember it:  proto3 _compresses_ the serialized message by leaving out fields that have the default value.  The decoder initializes all fields to their default value before decoding.  For number fields, this means that zero values are never actually transferred, but the decoder ends up with the right value.

The older "proto2" omits fields that were not explicitly set, which is a more complex and subtle behavior.

**Comment by sunnypurewal** [comment]
Thanks for the comments. Turns out my server is looking for the field to exist but it doesn't so it throws a validation error, and this validation was running before the proto decode. I'll close this as a non-issue
