### ISSUE TITLE
Too many build errors

### ISSUE THREAD

**Issue by ujjwalap** [apple/swift-protobuf#687]
Please be sure to include:

* what OS you are developing on (Linux or macOS, including the version)
Mac OS 10.13

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
  for Linux, what version of Swift (`swift --version`)

xcodebuild -version
Xcode 9.0.1
Build version 9A1004

Also happening on Xcode 8.3.3

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
Xcode 9.0.1

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
/// Protobuf-swift version: 3.0.22

* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.
/// Generated by the Protocol Buffers 3.4.0 compiler.  DO NOT EDIT!
/// Protobuf-swift version: 3.0.22
/// Syntax "Proto3"

import Foundation
import ProtocolBuffers

No such module 'ProtocolBuffers' in XX.proto.swift

Use of undeclared type 'Ee_Depcloudmdmservice_Service_DefineProfileRequest' >> Around 58 errors

XX.service.client.pb.swift
XX.service.server.pb.swift 

* lastly, if it all possible, provide a snippet of `.proto` and/or source
  that shows the problem.

I do not see any structs created. Please help us to understand what are we missing here. 

Thank you!

**Comment by thomasvl** [comment]
We just did a 1.0 release (https://github.com/apple/swift-protobuf/releases), so the fact that you say you have _Protobuf-swift version: 3.0.22_ seems to imply you are using a different project for your protobuf support.

**Comment by tbkka** [comment]
You should file this with https://github.com/alexeyxo/protobuf-swift which is entirely unrelated.

**Comment by ujjwalap** [comment]
Thanks for your response!

My bad we intend to use Resolving https://github.com/apple/swift-protobuf.git at 0.9.903

Also I am curious if "import ProtocolBuffers" is internally called by swift-grpc or swift-protobuf? I do not have a copy of this locally.

**Comment by tbkka** [comment]
> ... we intend to use Resolving https://github.com/apple/swift-protobuf.git at 0.9.903 

You should use 1.0.0 or later if you can.

> I am curious if "import ProtocolBuffers" is internally called ...

swift-protobuf does not use `import ProtocolBuffers`.  I don't believe swift-grpc uses such a library either.
