### ISSUE TITLE
Integrate "Building and Installing the Code Generator Plugin" as part of the build

### ISSUE THREAD

**Issue by paktree** [apple/swift-protobuf#704]
In the README, there are manual steps on installing the code generator plugin and install the protoc binary. We have quite a few developers in the company, it will require additional set up steps in order for everyone to install those plugins.

As part of the build integration, could those binaries live in the codebase and we can set up some "Run Script" steps in Xcode project to generate those swift code with those binaries instead of copying them to $PATH?

**Comment by thomasvl** [comment]
Yup, can set it up any way you want.  Always invoke `protoc` with a qualified path in your setup and the developers `$PATH` doesn't matter.  Likewise, use `protoc`'s `--plugin` argument and you can provide a qualified path to a plugin so `protoc` doesn't reply on the user's `$PATH` for finding the plugin.  The exact form would be something like `--plugin=protoc-gen-swift=YOUR_PATH_TO_THE_PLUGIN`

**Comment by thomasvl** [comment]
Closing this out since the question seems answered and there hasn't been any followup.
