### ISSUE TITLE
Swift 4.1 added warnings for "near misses" with default impls of protocols that cause build warning in generated code

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#719]
Moving discussion from PR #715 into an issue directly.

Swift 4.1 adds a new warnings message for _near misses_ for things are the close to be protocol overrides of things that provide default implementation. 

Within the SwiftProtobuf library this comes up on WKT's `Type` because it has a `value` field, so the presence test (`hasValue`) gets flagged as being close to `hashValue`.  Within SwiftProtobufs unittests there are other hits around some other methods.

Looking though the current library code, this comes up for:

`Message.swift` - `Message` -
* `isInitialized`
* `hashValue`
* `debugDescription`

The other protocols we have (`ExtensibleMessage` and `_MessageImplementationBase `) we think use names for things that they aren't likely to encounter the issues.

Looking at the Swift compiler sources, it looks like the warnings is triggered by looking at the _edit distance_ between the names to then decide to then trip the warnings.

The "fix" from the warning is to move the method into a category to then avoid the warning.  So the generation needs to change what is generated to avoid getting these warnings because we don't really want to encourage developers that was warnings as error to go edit the generated code.

**Comment by thomasvl** [comment]
So I made some basic test messages to see what happens:

```protobuf
syntax = "proto2"

message Msg2NamesNoStorage {
  optional int32 is_initialized = 1;
  optional int32 debug_description = 2;
  optional int32 value = 3;
}

message Msg2NamesUsesStorage {
  optional int32 is_initialized = 1;
  optional int32 debug_description = 2;
  optional Msg2UsesStorage value = 3;
}
```

```protobuf
syntax = "proto3"

message Msg3NamesNoStorage {
  int32 is_initialized = 1;
  int32 debug_description = 2;
  int32 has_value = 3;
}

message Msg3NamesUsesStorage {
  int32 is_initialized = 1;
  int32 debug_description = 2;
  Msg3UsesStorage value = 3;
}
```

The generator to avoid the collections turns the first two properties into `isInitialized_p` and `debugDescription_p`.

For the `proto2` syntax case, we get the warnings for both storage and no storage for `isInitialized` - `isInitialized_p`, `debugDescripion` - `debugDescription_p`, and `hashValue` - `hasValue` (field presence).  In both storage/no storage cases, the field accessors are computed properties.

For the `proto3` syntax case, we don't have any issues on the no storage cases because those generate is direct properties.  In the Storage case, we get the same set of warnings because of the computed properties to relay into the Storage.

**Comment by thomasvl** [comment]
It is also worth calling out some discussion on Twitter (and I think @allevato might start a followup on _swift-dev_), there was talk about maybe requiring the types to match in addition to the edit distance threshold, but that only partially helps here, as we could have a proto with an `is_initialized` field that holds a `bool` and the warning for the generated `isInitialized_p` would still fire.  Same being true for the types/names on the other two.  So while the warning may fire less often, it will still be possible, meaning the generator does need to find a way to deal with it.

**Comment by thomasvl** [comment]
Looks like we could remove `isInitialized` from the potential issues if we drop the default implementation and _always_ generate the method instead of only generating it when it needs to do some work.

This would come at the cost of making every generated message a little larger as they would get a custom impl of the message instead of being able to share the default.

But we still have to deal with the issue with the other cases, so removing one case doesn't _solve_ the problem, so given we still have the baseline problem and it makes for slightly larger code because it impacts every message, this change doesn't seem worth while.

**Comment by thomasvl** [comment]
The current generated code pays some attention to what the code _looks like_ to help developers that have the habit of jumping to the type definition in their IDE.

So if we do simplest implementation of  the _suggested_ fix, and moved all of these computed fields into an extension, jumping to the type would be a type with `fileprivate` fields (with leading underscores) the impl details for travers, etc., and _no_ access to the fields themselves.  They'd have to scroll to the extension to then see all the fields.

The _better_ solution seems to be if we can only move a field with a problem name and leave a comment for that.  Then the majority of the messages/fields will continue to generate as they do today.  The catch is how to figure out what fields need to be moved, and having to keep that in sync with all versions of Swift we support as the details of when the warning could always be changed/refined.

**Comment by allevato** [comment]
For reference, here's the PR that added near miss detection: https://github.com/apple/swift/pull/12645

There was some discussion in the Twitter thread about making it a little stronger—for example, ignoring cases where the name _and_ type don't match. That helps us in cases like `hasValue/hashValue`, but wouldn't help us in cases where the property has a matching type, too.

The near-miss detection uses edit-distance calculations supported by LLVM, along with a bunch of other logic to determine whether something should be considered a miss or not. I don't think it would be a valuable exercise to try to duplicate this logic in our generator, since it's likely to be a moving target as well. Trying to handle these near-misses as a special case strikes me as a never-ending game of whack-a-mole.

We should probably just move all of our generated field properties into an extension 😢

**Comment by thomasvl** [comment]
> We should probably just move all of our generated field properties into an extension 😢

All that work to make browsing the generated code more readable… 😭 

@tbkka any thoughts?  Otherwise, I'll look at doing the generator change and see if there is anything we can do to make sure the code is as browsable as possible.

**Comment by tbkka** [comment]
I agree that moving the generated field properties into an extension is unpalatable.

I'll ask some folks and see if I can dig up any alternatives.

**Comment by tbkka** [comment]
A possible alternative:  Apparently, the warning is triggered when the conformance and the properties are in the same context.  So instead of moving the properties to an extension, maybe it would suffice to move the conformance:
```
struct Foo {
    // ... exact same contents as currently ...
}
extension Foo: SwiftProtobuf.Message {
    // .empty
}
```

**Comment by thomasvl** [comment]
A quick hack at it seems to say that will work.  It also is sorta nice in that we could move the methods like `traverse` down there so folks are less likely to think they need to use them.  I'll work on changing the generator for this tomorrow.
