### ISSUE TITLE
Allow static library usage from Cocoapods

### ISSUE THREAD

**Issue by bridger** [apple/swift-protobuf#723]
Version [1.4.0 of Cocoapods](http://blog.cocoapods.org/CocoaPods-1.4.0/) allows a pod to be used as a static library, even in a Swift app. It requires the library's podspec to contain `s.static_framework = true`.

I believe this will help apps launch faster. Here's a blog post that explains why too many dynamic frameworks slows down launch: https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea

**Comment by mackoj** [comment]
This might help https://github.com/CocoaPods/CocoaPods/pull/6966 to answer your questions.

**Comment by bridger** [comment]
It looks like CocoaPods v1.5 lets the app decide if the dependencies are static or dynamic. http://blog.cocoapods.org/CocoaPods-1.5.0/ This issue can be closed now. Thank you!
