### ISSUE TITLE
Determine support for SE0194's CaseIterable

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#729]
[Derived Collection of Enum Cases](https://github.com/apple/swift-evolution/blob/master/proposals/0194-derived-collection-of-enum-cases.md) was [approved](https://forums.swift.org/t/accepted-se-0194-derived-collection-of-enum-cases/10723).

I believe it will show up post Swift 4.1.

**Comment by thomasvl** [comment]
The proposal got updated to say it is in Swift 4.2.

**Comment by thomasvl** [comment]
For a proto2 enum, this is pretty clear, the compiler generated support can be used.

For a proto3 enum, we'll need to provide our own impl of `allCases` and leaves off the `UNRECOGNIZED(int)` case and just exposes the others.

@allevato and I were talking about some of the details for this the other day, and did some double checking of what the compiler does, [SR-7152](https://bugs.swift.org/browse/SR-7152) is open to expose a more simple collect, but it seems like the compiler support exposes it as a full `Array`.  The one down side here is once you expose an `Array` you are pretty much locked in to always exposing an `Array` or you can break someones code.  At this point is doesn't seem like SR-7152 is going to happen, so maybe just exposing an `Array` isn't that bad as we're only matching with the compiler is going to lock folks into also.  The other option would be to do like SR-7152 suggests and expose a custom `Collections` to hide the details (it could wrap/forward to an `Array` without exposing the full `Array` support), which reserves us some flexibility in the future should we want to change things.

**Comment by thomasvl** [comment]
For reference: [`DerivedConformance::deriveCaseIterable()`](https://github.com/apple/swift/blob/master/lib/Sema/DerivedConformanceCaseIterable.cpp#L80)

**Comment by thomasvl** [comment]
After looking at all the options and talking some more with @allevato, we're leaning toward just exposing an `Array` just like the compiler would generated.  Doing anything more complex just is feeling like bloat/complexity and drifts from what happens in the compiler generated case to not be worth it.

**Comment by jackxujh** [comment]
I just found out the protocol included in Apple's documentation for Swift 4.2: [CaseIterable - Swift Standard Library | Apple Developer Documentation](https://developer.apple.com/documentation/swift/caseiterable)
