### ISSUE TITLE
protoc-gen-swift: program not found or is not executable

### ISSUE THREAD

**Issue by SwiftExpert** [apple/swift-protobuf#730]
Hey.
**my environment:**
Mac OS Sierra, Xcode 9.2, swift 4, protobuf 1.0.3.

**im using this commands to create the "protoc-gen-swift" file but the file is not there when installation completes.**
$ git clone https://github.com/apple/swift-protobuf.git
$ cd swift-protobuf
$ git tag -l
$ git checkout tags/1.0.3
$ swift build -c release -Xswiftc -static-stdlib

Also i tried installing with "brew":
$ brew install swift-protobuf

in both cases when i'm turning my ".proto" into swift($ protoc --swift_out=. my.proto
) i'm getting the error: 
"protoc-gen-swift: program not found or is not executable"

**Comment by thomasvl** [comment]
Did you do the last step in the [instructions](https://github.com/apple/swift-protobuf#building-and-installing-the-code-generator-plugin)?

> This will create a binary called `protoc-gen-swift` in the `.build/release` directory. To install, just copy this one executable into a directory that is part of your `PATH` environment variable.

i.e. - does `which protoc-gen-swift` find it as expected?

If `brew` also doesn't work, it might be that your brew setup isn't set up correctly to install things on your `PATH` also.

**Comment by SwiftExpert** [comment]
1) i wanna do the last step but can't find the executable/binary "protoc-gen-swift".
2) i installed brew with:
 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Thats the folder being created with the regular steps:
![screen shot 2018-03-22 at 3 30 03 pm](https://user-images.githubusercontent.com/35992075/37773333-fa777b6a-2de5-11e8-8971-ea60b6a2a2d6.png)

**Comment by thomasvl** [comment]
The `.build` directory will be hidden in the Finder (leading dots hide files).  That is the directory the Swift Package Manager writes out into.  Just us `cp` in the Terminal to copy it into a location on your `PATH`.

**Comment by SwiftExpert** [comment]
Thanks a lot. it works.

**Comment by tbkka** [comment]
Glad you fixed it!

**Comment by ajayz7** [comment]
Can some one help me please?  I ma facing same issue, protoc-gen-swift : program is not executable . if possible can someone create grpc.swift file and send me back the same 
[dispatcher.proto.zip](https://github.com/apple/swift-protobuf/files/4677473/dispatcher.proto.zip)

**Comment by ajayz7** [comment]
@thomasvl I am facing same issue.

**Comment by ajayz7** [comment]
sure @al1m4ik, same to you if you find anything please post here. Thanks

**Comment by Noveen** [comment]
@ajayz7 and @al1m4ik  are you still facing any issues
