### ISSUE TITLE
Failed adding the SwiftProtobuf library to my Xcode project

### ISSUE THREAD

**Issue by IvyDev0** [apple/swift-protobuf#734]
Hi, I'm using Xcode 9, and I opened the project in the branch 1.0.3.
I'm confused about the instruction in readme: "Add the appropriate `SwiftProtobuf_<platform>` target from the Xcode project in this package to your project."

I first build the SwiftProtobuf.project using the target `SwiftProtobuf_iOS`, and then added the generated `SwiftProtobuf.framework` into my swift project. But an error shows in my `.pb.swift` file, at `import SwiftProtobuf`: `Could not build Objective-C module 'SwiftProtobuf`.

I don't get it why it says Objective-C module. My project is in Swift.

**Comment by YiyiDeng** [comment]
I changed to Carthage, it build succeed. But when I run it on iPhone 6s Plus, “dyld`__abort_with_payload” error occurred. 
<img width="959" alt="screen shot 2018-04-09 at 4 28 28 pm" src="https://user-images.githubusercontent.com/16366840/38487547-1ba2f3ce-3c13-11e8-925a-89a659b75c53.png">

**Comment by tbkka** [comment]
I hope you've been able to fix this issue in your build.  Please add more information if you're still blocked.
