### ISSUE TITLE
Xcode 9.3 - Basic usage fails

### ISSUE THREAD

**Issue by kylekurz** [apple/swift-protobuf#741]
Please be sure to include:

* what OS you are developing on (Linux or macOS, including the version)

macOS 10.13.4

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
  for Linux, what version of Swift (`swift --version`)

Xcode 9.3
Build version 9E145

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)

Swift 4.1

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)

Whatever comes with default Podfile install (looks like 1.0.3)

* if you are getting compile errors, please be sure include all errors/warnings,
  sometimes the error before the one you are stuck on is important.

First problem is the generated code imports ProtocolBuffers, which is not a dependency of SwiftProtobuf. Once you add that dependency, 50+ build errors are generated, all within the protoc-generated code. Full project attached, `pod install` and build to see errors, first one is `Use of undeclared type 'ExtensionRegistry'`.

* lastly, if it all possible, provide a snippet of `.proto` and/or source
  that shows the problem.

Full repro:
[ProtobufTest.tar.gz](https://github.com/apple/swift-protobuf/files/1989451/ProtobufTest.tar.gz)

Thank you!

**Comment by tbkka** [comment]
```
/// Protobuf-swift version: 4.0.0
```

It appears that you're mixing "SwiftProtobuf" with "protobuf-swift".  These are two entirely separate and incompatible projects (with regrettably similar names).  If you use "protobuf-swift" to generate the code, you should link with it's supporting library.

**Comment by kylekurz** [comment]
Wow, thanks for figuring that out. I assume since this falls under the "Apple" github org, this is the recommended project for protocol buffers and Swift?

**Comment by thomasvl** [comment]
> Wow, thanks for figuring that out. I assume since this falls under the "Apple" github org, this is the recommended project for protocol buffers and Swift?

Since this one is in the _Apple_ github org and has two main contributors with _@google.com_ address (where protocol buffers originated), we think it is.  😄
