### ISSUE TITLE
Custom FieldOptions going to unknownFields instead of extensionFieldValues

### ISSUE THREAD

**Issue by vs-asapp** [apple/swift-protobuf#742]
* what OS you are developing on (Linux or macOS, including the version)
**macOS 10.13.4**

* for macOS, what version of Xcode you are using (`xcodebuild -version`),
  for Linux, what version of Swift (`swift --version`)
**Xcode 9.3.1
Build version 9E501**

* what version of Swift is your code set to compile with (i.e. from project
  settings, etc.)
**Swift 4**

* what branch/tag of SwiftProtobuf you are using (1.0.0, etc.)
**1.0.3**

* lastly, if it all possible, provide a snippet of `.proto` and/or source
  that shows the problem.
```
message Something {
  string name = 1 [(testOpt)=2];
}

extend google.protobuf.FieldOptions {
  int testOpt = 66666;
}
```
The following is printed for `field.option`:
```
field.option: SwiftProtobufPluginLibrary.Google_Protobuf_FieldOptions:
  66666: "true"
```

Mirror of the object:
```
  Attr: uninterpretedOption, value: []
  Attr: unknownFields, value: UnknownStorage(data: 4 bytes)
  Attr: _protobuf_extensionFieldValues, value: ExtensionFieldValueSet(values: [:])
  Attr: _ctype, value: nil
  Attr: _packed, value: nil
  Attr: _jstype, value: nil
  Attr: _lazy, value: nil
  Attr: _deprecated, value: nil
  Attr: _weak, value: nil
```

As you can see the option is going to unknownField instead of `_protobuf_extensionFieldValues`

Is there a way to retrieve the custom option from unknown fields?

**Comment by thomasvl** [comment]
Custom options (https://developers.google.com/protocol-buffers/docs/proto#customoptions) like this are basically metadata about the type.  They aren't in the message itself (which is what unknown fields are used for, per message data that isn't in the message description).  The languages that expose custom options do so by exposing the descriptor options.

The issue has come up on a few issues before, but at this time, SwiftProtobuf has not decided to capture this data and expose it at runtime.  One of the biggest concerns is the bloat on apps that don't end up needing it.

**Comment by thomasvl** [comment]
#761 was opened for tracking how to capture/model options in the Swift api.
