### ISSUE TITLE
Should we consider filtering away extension to file/message/field/etc. options?

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#751]
Thinking about #727 got me wondering again about the need for the descriptor objects.

The proto objects themselves really aren't that interesting/useful (for the generator, we had to wrap it in a custom set of objects to actually build a usable graph out of the object, like what C++ does).

My though was this might come up a lot just from files that use field/message/field/etc. options, as those end up as extensions on the descriptor proto object.  But since we don't actually capture the binary descriptor dump as part of generation (like C++ does), it isn't real clear to me what these would be used for.

So…

The folks that run into the need for the generated descriptor - why do they need it?  Is it just to get some other file with real types to compile?  What is we default to dropping all extension on the descriptor objects since our runtime doesn't provide the data?  It would help keep folks binary needs smaller.  But there could be some use for it, which might mean we still get suck having to provide some generator option to enable for those really rare cases that need them.

Anyway, I'm not convinced one way or the other, just capturing the thought/discussion for reference here.

**Comment by pasdam** [comment]
In my case I have a proto similar to:
```proto
syntax = "proto3";

package protocol;

import "google/api/annotations.proto";

extend google.protobuf.MethodOptions {
    bool requiresSession = 50999;
}

service AccountManager {

    // Authenticate the user and returns a valid session
    rpc authenticate(AuthenticationRequest) returns (AuthenticationReply) {
        option (protocol.requiresSession) = false;
    }

    ...
}

...
```
I use it to mark endpoints that require a valid session, so the server knows that it has to verify its presence, and clients knows that they have to add the related metadata.
I hope this answer your question.

**Comment by tbkka** [comment]
@pasdam -- How are you using that?  SwiftProtobuf doesn't support `service` nor does it support custom options like this.

**Comment by pasdam** [comment]
Sorry, I forgot to specify that I'm using gRPC (hence `service`) and the option is ATM used only on the server side.

**Comment by thomasvl** [comment]
@pasdam thanks.  That's what I mostly expected.  Hopefully we'll get some other confirmations to finish making some decisions here.

**Comment by thomasvl** [comment]
One other idea while I think of it: rather then filter them away, just like we've talked about moving some of the "text" support into a second generated file so developers and pick to include it or not, we could also consider doing that with everything related to descriptors.  i.e. - we could put all the extensions needed for options into a different source and developers can then decide if they want to link them in or not.  Only down side is to keep build integrations clean, we likely would need to generate the file even if it was empty.

**Comment by thomasvl** [comment]
Splitting these into separate files or filtering could have long term impacts if we do eventually expose this info form the library.

If it is a option (to filter them away), we're potentially stuck with it and options always run into the problem two libraries using the same proto, but trying to generate with different options.

**Comment by thomasvl** [comment]
I'm closing this out since I don't see justification for trying to come up with some filtering currently, and whenever the library does something to support something "descriptor like" for reflection and/or a way to expose the message/field/etc. options, these extensions might be needed again.  So at the time those are done, it make sense to worry think about this again, but not in the mean time.
