### ISSUE TITLE
Revisit float/double to string transforms (JSON and TextFormat)

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#752]
@tbkka has been landing some code to the Swift StandardLib to speed up the float and double formatting.  `Float.description` should now avoid the heap, but `Double.description` does still use the heap.

We should revisit current releases with our perf harness to see if we can move our code into a conditional block for old versions of Swift, to eventually phase it out.

**Comment by tbkka** [comment]
Resolved via #882.
