### ISSUE TITLE
Swift4.2 Hasher support

### ISSUE THREAD

**Issue by shoheiyokoyama** [apple/swift-protobuf#767]
`swift-protobuf` supports Swift 4.2 in the latest master version. but `Hasher` does not seem to support yet.
`swift-protobuf` generates `hashValue` with its own logic, but I think that it is better to generate `hashValue` using `Hasher`.
This is valid for instances that generate `hashValue` with multiple properties.

Is there a clear reason not to use `Hasher`?

If there is no problem,  I will submit pull request.

### Reference

The `stdlib` has switched to a randomly seeded, high-quality hash function for all hashing. 

- [Proposal: SE-0206](https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md)

**Comment by thomasvl** [comment]
We just haven't gotten to it (or opened an issue for it, I thought we had).  I have a PR out for CaseIterable, and I'll likely work on the hashing changes next (they are a little trickier).  The good news is 4.2 isn't GM yet, so we really aren't _behind_ from that  POV.
