### ISSUE TITLE
Double check unknown JSON support

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#769]
Looks like the conformance test on protobuf trunk added something for handling of unknown fields (https://github.com/google/protobuf/pull/4839), and for most of their conformance tests, they had to make things known to not work, but if I run the swift test against it nothing fails which makes me think either something is wrong in our conformance test support or in our JSON support.

**Comment by thomasvl** [comment]
Looks like `JSONScanner.nextFieldNumber(names:)` is automatically skipping unknown fields without the support to error at all, so sorta out of spec (https://developers.google.com/protocol-buffers/docs/proto3#json_options says things should reject by default).

**Comment by tbkka** [comment]
Good catch.

> ... if I run the swift test against it nothing fails ...

That suggests there are no conformance tests to verify that unknown fields in JSON are rejected by default.

**Comment by thomasvl** [comment]
> That suggests there are no conformance tests to verify that unknown fields in JSON are rejected by default.

yea, I've already started a thread with the protobuf team about it (and the fact that these new tests are required but the spec anything the option isn't required.

**Comment by texuf** [comment]
Sorry for commenting on an old closed task, but are you sure you want this in the library? Now adding a field to an existing protobuf message will break old clients unless all calls to Message.init(jsonString: ...) include the JSONDecodingOptions.ignoreUnknownFields option....
Amy I missing something? This seems annoying.

**Comment by thomasvl** [comment]
> Sorry for commenting on an old closed task, but are you sure you want this in the library? Now adding a field to an existing protobuf message will break old clients unless all calls to Message.init(jsonString: ...) include the JSONDecodingOptions.ignoreUnknownFields option....
Am I missing something? This seems annoying.

This was an oversight in the initial implementation as the spec actually requires that they get rejected:

https://developers.google.com/protocol-buffers/docs/proto3#json_options

> *  *Ignore unknown fields:* Proto3 JSON parser should reject unknown fields by default but may provide an option to ignore unknown fields in parsing.

So the change brought things inline with they required behavior.

We also bumped the library minor version (to 1.1.0) and called it out in the [release notes](https://github.com/apple/swift-protobuf/releases/tag/1.1.0).

Hopefully something like this won't ever come up again, but if it were to, if you have any better suggestions on how to message it, we'd be interested.

**Comment by texuf** [comment]
Thanks for replying so quickly and with such detail. I naively filed a bug: https://github.com/protocolbuffers/protobuf/issues/5432. Will see what happens.
