### ISSUE TITLE
# Would you update the pod  to the latest?

### ISSUE THREAD

**Issue by Insfgg99x** [apple/swift-protobuf#775]
# Would you please help to update the pod  to the latest?

# Thank you!

**Comment by thomasvl** [comment]
What's the issue you are hitting that you need a new release?  We are working on 4.2 support at the moment, so will have a release after that is done, but if there is something pressing we look at cutting a release with other fixes in the mean time.

**Comment by Insfgg99x** [comment]
I need a new release
