### ISSUE TITLE
EXC_BAD_ACCESS while serializing the data

### ISSUE THREAD

**Issue by kushdixit** [apple/swift-protobuf#779]
Please be sure to include:

* IOS 11.1

* XCode 9.4

* Swift 4.1

* pod 'SwiftProtobuf', '~> 1.0'

My code is crashing when i try serialize Message with BinaryDelimited
Code Snippet:
       
 let outputstream = OutputStream()
do {
            **try BinaryDelimited.serialize(message: message, to: outputStream, partial: false)** //Crashes here
        }
        catch {
            print(error.localizedDescription)
        }

Thank you!

**Comment by thomasvl** [comment]
Sorry, but there really isn't enough to go on here.  What's the stack trace look like?  Can you make an example project that shows this?  We do have tests using the API that work, so it likely is something specific to your outputStream and/or message.

**Comment by kushdixit** [comment]
Can you please add a sample snippet how i should use BinaryDelimited.serialize ?
Thanks

**Comment by thomasvl** [comment]
This does look like a bug to report to Apple for the Swift wrapper on OutputStream. `OutputStream()` doesn't appear to make a working stream, but `OutputStream(toMemory:())` and `OutputStream.toMemory()` do seem to be usable.

**Comment by kushdixit** [comment]
Thanks a lot @thomasvl . :)
It worked for me now after reading you test case.
