### ISSUE TITLE
Size of message.serializedData() is zero

### ISSUE THREAD

**Issue by dinobei** [apple/swift-protobuf#789]
Hi,

I have a problem.
When serializing using swift-protobuf, the size is always 0. (google/protobuf too)

this is my code.

```proto
enum Option {
  foo = 0;
  bar = 1;
}

message Packet {
  Option option = 1;
}
```

```swift
var msg = Packet()
msg.option = Option.foo;
let serializedData = msg.serializedData()
print("serializedData.count: \(serializedData.count)")
// "serializedData.count: 0" (Why?)

msg.option = Option.bar;
let serializedData2 = msg.serializedData()
// "serializedData.count: 2" (This is the correct state.)

```

Why is this happening?

**Comment by thomasvl** [comment]
You file is probably `syntax = "proto3";`, with `proto3` syntax, fields set to the default values are not encoded on the wire.  For your enum (`Option`), the first value is `foo` and hence the default, which means it isn't set. So `msg` actually has no fields set.

**Comment by thomasvl** [comment]
More info on `proto3` and default values: https://developers.google.com/protocol-buffers/docs/proto3#default

**Comment by dinobei** [comment]
Thanks for the reply.
I am using proto3.
So it is normal to work like this.

I've experimented with the following:
If any one is not a default value, it will be serialized normally.

```proto
syntax = "proto3";
package example;
enum Foo {
  int32 value1;
  int32 value2;
}
```

```swift
// in swift
let foo = example::Foo()
foo.set_value1(0); // For numeric types, the default value is zero.
foo.set_value2(1); // not a default value
let serializedData = foo.serializedData()
// serialized normally.
```


By the way, for example, when there is the following code,
If all of them are defaults, then serialization is not possible.
Is there no way to bypass it in proto3?

```swift
// in swift
let foo = example::Foo()
foo.set_value1(0); // For numeric types, the default value is zero.
foo.set_value2(0); // For numeric types, the default value is zero.
let serializedData = foo.serializedData()
// serializedData.count() equal 0.
```
The reason I chose proto3 instead of proto2 is because I think it would be better.
Should I use proto2 if I expect this?

**Comment by thomasvl** [comment]
> By the way, for example, when there is the following code,
> If all of them are defaults, then serialization is not possible.
> Is there no way to bypass it in proto3?

I'm not sure what this means.  You can always serialize, it just result in a data of zero length.  That is still valid.  You can feed zero length data in, and the message will end up in the same state, those fields will return the default values.

> The reason I chose proto3 instead of proto2 is because I think it would be better.
> Should I use proto2 if I expect this?

The two syntaxes provide different sets of behaviors.  `proto2` syntax allows for custom default values, field presence, the messages support extensions, etc.  `proto3` syntax requires all defaults to be zero, only supports field presences for message fields, etc.  You should pick the one that meets your needs.

**Comment by dinobei** [comment]
I was mistaken.
I did not know that it was generated as a default message by feeding data of zero length.
Thanks for the clear answer!
