### ISSUE TITLE
.proto文件中的service怎么没有生成相应的代码

### ISSUE THREAD

**Issue by Lee-1991** [apple/swift-protobuf#793]
.proto  文件中，关于service的代码，在.pb.swift中没有生成相应的代码
service IM {
    // 客户端发送消息
    rpc SendMsg (SendMessage) returns (SendResult) {}
    // 服务端推送新消息
    rpc NewMsg (EmptyRequest) returns (stream NewMessage) {}
}

**Comment by thomasvl** [comment]
This has come up before, check out #682 and #118.
