### ISSUE TITLE
Why there is no Code about service in .pb.swift

### ISSUE THREAD

**Issue by Lee-1991** [apple/swift-protobuf#794]
There are some code about service in my  .proto,  after  "protoc --swift_out=. im.proto" ,there is no code about service that I wanted in .pb.swift
service IM {
    // 客户端发送消息
    rpc SendMsg (SendMessage) returns (SendResult) {}
    // 服务端推送新消息
    rpc NewMsg (EmptyRequest) returns (stream NewMessage) {}
}

**Comment by thomasvl** [comment]
This has come up before, check out #793, #682 and #118.
