### ISSUE TITLE
dyld: Symbol not found: __T0Bi64_WV - Xcode 10

### ISSUE THREAD

**Issue by biscottigelato** [apple/swift-protobuf#797]
macOS High Sierra v 10.13.6
Xcode 10.0 Build version 10A255
SwiftProtobuf 1.1.2/Master

I am getting this error running protoc. I tried both 1.1.2 and Master and gave me the same thing. I am wondering if there's incompatibility with Xcode 10? Thanks!

dyld: Symbol not found: __T0Bi64_WV
  Referenced from: /usr/local/bin/protoc-gen-swiftgrpc
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/protoc-gen-swiftgrpc
--swiftgrpc_out: protoc-gen-swiftgrpc: Plugin killed by signal 6.

**Comment by thomasvl** [comment]
That error is about `protoc-gen-swiftgrpc` which isn't part of this project.

My guess would be the binary is built/linked with a different version of the Swift runtime libraries, and you need to rebuild it.

Did you recently installed a new Xcode? That's likely the cause.

**Comment by biscottigelato** [comment]
My bad, I just had to rerun make for grpc/grpc-swift after installing the new Xcode 10. Now works. Closing this issue. Thanks!

**Comment by IbrahimKZ** [comment]
@biscottigelato I have the same problem. What I need to do to fix it? I didn't understand your advice `I just had to rerun make for grpc/grpc-swift`

**Comment by cepages** [comment]
@biscottigelato I have the same problem than @IbrahimKZ, I quite don't understand your comment. Could you add more detail in your previous comment please?

**Comment by cepages** [comment]
I think he meant to rebuild `protoc-gen-swift`. So he rerun make in `https://github.com/grpc/grpc-swift#getting-the-plugins` 

Unfortunately that did't work for me
