### ISSUE TITLE
Swift Build Error

### ISSUE THREAD

**Issue by mq3616** [apple/swift-protobuf#801]
Swift 4.2
After swift build -c release -Xswiftc -static-stdlib
I got "error: terminated(72): xcrun --sdk macosx --find xctest output:"
How can I fix this?

**Comment by thomasvl** [comment]
Can you provide more info?  Is this a new checkout?  And existing build?  If you just updated Xcode, try `swift package clean` before rebuilding incase you have artifacts build by an older Xcode.

**Comment by shakesVan** [comment]
use this:
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by tbkka** [comment]
This seems to have helped quite a few people.  Closing.
