### ISSUE TITLE
Using multiple .proto files

### ISSUE THREAD

**Issue by cyangf** [apple/swift-protobuf#802]
Hi,

I am working with multiple .proto files. Some files define the types referenced by other .proto files. I am currently generating the .pb.swift files using:

`protoc --swift_out=. *.proto`

However, in xcode, I'm seeing "Use of undeclared type" errors. 

What is the best way to generate the .pb.swift files such that the imports will also be translated?

Thank you!

**Comment by thomasvl** [comment]
Are you adding the sources to different modules or do they all go into the same module?  If they are all the same module, things should "just work".  If you want them in different modules, you need to tell the generator about the mappings from `*.proto` files to modules via the [ProtoPathModuleMappings  generator option](https://github.com/apple/swift-protobuf/blob/master/Documentation/PLUGIN.md#generation-option-protopathmodulemappings---swift-module-names-for-proto-paths).

**Comment by cyangf** [comment]
@thomasvl They are all going into the same module.

Currently I have:
- file_A.proto which defines a message `Foo`
- file_B.proto which references `Foo`, at the top of this file, it does `import "file_A.proto";`

After I generate the code, I get file_A.pb.swift and file_B.pb.swift. The generated struct for `Foo` is in file_A.pb.swift but I no longer see any imports in file_B.pb.swift of file_A.pb.swift. How does file_B.pb.swift know to look at file_A.pb.swift for `Foo`?

**Comment by thomasvl** [comment]
> After I generate the code, I get file_A.pb.swift and file_B.pb.swift. The generated struct for Foo is in file_A.pb.swift but I no longer see any imports in file_B.pb.swift of file_A.pb.swift. How does file_B.pb.swift know to look at file_A.pb.swift for Foo?

If you are compiling them in the same module, they don't need imports.  They have access to all the code in their own module.

Think of it just like code you write, your directory of `*.swift` files for you app go into a single target, and they don't need any imports to use the types from the other in that same target.

**Comment by cyangf** [comment]
Ah, this is my first time developing with xcode. I need to add the *.pb.swift files to the xcode project for it to be picked up (doh). Thanks for you help!
