### ISSUE TITLE
Why default implementation of `traverse` check for `if self.value != false` in case of bool?

### ISSUE THREAD

**Issue by kamal-mann** [apple/swift-protobuf#803]
**Issue**
For bool properties in a proto object, generated struct has an extension on 
`SwiftProtobuf.Message`. In the default implementation of `public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws` it checks for `if self.value != false` for bool values.   
_What about the case where other service/server expects a false value in request?_

[Code Location](https://github.com/apple/swift-protobuf/blob/53cd96329ee3eb8302af42cb655bacbd8e218b37/Reference/google/protobuf/wrappers.pb.swift#L399)

https://github.com/apple/swift-protobuf/blob/53cd96329ee3eb8302af42cb655bacbd8e218b37/Reference/google/protobuf/wrappers.pb.swift#L399

**Comment by tbkka** [comment]
The wrapper types are all proto3.  Proto3 encoding does not send `false` values for bool fields.  The other service/server knows that a missing bool field is `false`.

**Comment by tbkka** [comment]
See Google's documentation about Default values in Proto3 for more details: https://developers.google.com/protocol-buffers/docs/proto3#default

In essence, proto3 compresses messages by omitting all default values.  For a boolean field, if the value is not specified, the receiver will set the field `false`.  This means it is always safe for the sender to omit a `false` value.
