### ISSUE TITLE
missingFieldNames when I try to get JSON data object

### ISSUE THREAD

**Issue by cepages** [apple/swift-protobuf#805]
Please be sure to include:

OSx 10.13.6
Xcode 10.0
Build version 10A255
Apple Swift version 4.2
SwiftProtobuf (1.1.2)

```
syntax = "proto3";

package MyData;

message HD5Data {

	double a = 1;
	double b = 2;
	double c = 3;
	repeated int32 d = 4;
	string e = 5;
}
```

When I try to parse my protobuf object I always get the same error `SwiftProtobuf.JSONEncodingError.missingFieldNames`

```
        do {
            let jsonData = try myProtobuf.jsonUTF8Data()
            
        } catch (let error) {
            print("seria:\(error) ")
        }
```

I can serializedData with no problem but I can't get the json data. 

Any ideas?

Thanks

**Comment by thomasvl** [comment]
Can you provide a copy of the generated file? My guess would be you are trying to use this library (SwiftProtobuf), but you are using a generator for some other Swift Protobuf implementation and things some how happen to compile but fail at runtime.  What does `protoc-gen-swift --version` print out?

**Comment by cepages** [comment]
The generated file is:

```
// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: HD5Data.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct HD5_HD5Data {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var a: Double = 0

  var b: Double = 0

  var c: Double = 0

  var d: [Int32] = []

  var e: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "HD5"

extension HD5_HD5Data: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HD5Data"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "a"),
    2: .same(proto: "b"),
    3: .same(proto: "c"),
    4: .same(proto: "d"),
    5: .same(proto: "e"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularDoubleField(value: &self.a)
      case 2: try decoder.decodeSingularDoubleField(value: &self.b)
      case 3: try decoder.decodeSingularDoubleField(value: &self.c)
      case 4: try decoder.decodeRepeatedInt32Field(value: &self.d)
      case 5: try decoder.decodeSingularStringField(value: &self.e)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.a != 0 {
      try visitor.visitSingularDoubleField(value: self.a, fieldNumber: 1)
    }
    if self.b != 0 {
      try visitor.visitSingularDoubleField(value: self.b, fieldNumber: 2)
    }
    if self.c != 0 {
      try visitor.visitSingularDoubleField(value: self.c, fieldNumber: 3)
    }
    if !self.d.isEmpty {
      try visitor.visitPackedInt32Field(value: self.d, fieldNumber: 4)
    }
    if !self.e.isEmpty {
      try visitor.visitSingularStringField(value: self.e, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: HD5_HD5Data, rhs: HD5_HD5Data) -> Bool {
    if lhs.a != rhs.a {return false}
    if lhs.b != rhs.b {return false}
    if lhs.c != rhs.c {return false}
    if lhs.d != rhs.d {return false}
    if lhs.e != rhs.e {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
```

protoc-gen-swift --version: `protoc-gen-swift 1.1.2`

The way I'm generating the file is with a Build rule in Xcode:

`protoc "$INPUT_FILE_NAME" --swift_out="$DERIVED_FILE_DIR" --proto_path="$INPUT_FILE_DIR"`

The build rule is associated with all `*proto` files and the output files are: `$(DERIVED_FILE_DIR)/${INPUT_FILE_BASE}.pb.swift`

I also have another Build rule to generate `grpc` files just on top of it. 

I've tried to get the json from a protobuf object with the same implementation but in a new isolated project with `.jsonUTF8Data()` and it works. 

Maybe it could be that `grpc` is affecting? I've checked the code generated and it's exactly the same in both projects.

**Comment by tbkka** [comment]
The error you're quoting is simply claiming that the object it is trying to serialize does not implement the `_ProtoNameProviding` protocol.  The `HD5_HD5Data` type obviously does:
```
extension HD5_HD5Data:  ...  SwiftProtobuf._ProtoNameProviding {
```

I would suggest you check very carefully to make sure the `myProtobuf` object in your original code snippet above really is an `HD5_HD5Data`.

**Comment by cepages** [comment]
Yeah, I simply changed the name of the  package to `HD5`. The problem happens in before and after.

**Comment by thomasvl** [comment]
Since things work in an isolated project, it sounds like it is something specific to your project setup; which makes it a little hard for us to really help figuring things out.  Maybe take your test setup that works, and slowly add things to mirror the complexity if where things don't work, and see what addition breaks things.

**Comment by tbkka** [comment]
We'd be happy to help, but there really isn't enough information here to tell what might be going wrong.  Please re-open this issue if you figure out more information.
