### ISSUE TITLE
Is there an implementation of ByteSizeLong or ByteSize

### ISSUE THREAD

**Issue by cepages** [apple/swift-protobuf#806]
Please be sure to include:

OSx 10.13.6
Xcode 10.0
Build version 10A255
Apple Swift version 4.2
SwiftProtobuf (1.1.2)

This is a question, no an issue.

Is there any implementation of `ByteSize()` or `ByteSizeLong()`  (https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message_lite#MessageLite.ByteSizeLong) in Swift protobuf.

I would like to get the size of a protobuf object without doing the serialisation of the object.

I could not find anything in the documentation about it: https://github.com/apple/swift-protobuf/blob/master/Documentation/API.md

Thanks

**Comment by tbkka** [comment]
We have
```
  internal func serializedDataSize() throws -> Int {
```
but that's internal to the library right now.

Could you explain what you use this size for?  Personally, I've never needed to know the size of a message before I encoded it, so I'd like to better understand your use case.

**Comment by cepages** [comment]
Yeah sure. 

We would like to know the transfer speed in communication with protobuf. 

Our protobuf has a timestamp parameter and if we have the size of the protobuf object, the client (the iOS app) will be able to calculate the transfer speed.

**Comment by tbkka** [comment]
It would be much faster to check the size of the data object before you deserialize it and use that.  Computing the serialized size is almost as expensive as doing the serialization (it requires walking the object and inspecting every field and field value).

**Comment by cepages** [comment]
Well, the thing is I don't deserialize the object. We are using grpc, so the response just gives you a protobuf object in it ( I'm assuming grpc probably deserialize the object somewhere in the communications process, but I can't have access to the raw data, that I'm aware of).

About the fact it takes the same time, I was assuming that because `ByteSize()` makes an estimation of the size, it would be faster than serialize the protobuf object.

**Comment by thomasvl** [comment]
So even if we exposed a method for the binary size, I'm not sure that would really help you calculate the transfer speed _the transfer speed in communication with protobuf_.  Protobuf just provides binary and JSON encoding methods.  It takes something like gRPC to add on a layer for framing to say what message is requested, etc.  That framing can be thin or think, include sidecars data, etc.; so to now the _transfer speed_ you really would need the data at the gRPC level, not just the at the protobuf layer.

**Comment by PeterWong2015** [comment]
It's very important for streaming with forward compatibility, it's been implemented with reasons.

**Comment by thomasvl** [comment]
@PeterWong2015 I'm sorry, I'm not following.  No public method has been implemented for this.

**Comment by tbkka** [comment]
@PeterWong2015  -- For streaming, you need the size and the serialized data.

Here's the fast way to get the data and the size:
```
    let foo: MyProtoObject
    // Serialize the data
    let serialized = foo.serializedData()
    // Get the size of the data (fast!)
    let size = serialized.length
```

Here's the slow way (which we don't support today):
```
    let foo: MyProtoObject
    // This serializes the data and then discards the result
    let size = foo.serializedDataSize()
    // Now serialize the data again
    let serialized = foo.serializedData()
```

**Comment by thomasvl** [comment]
Closing this out since it seems to have been a question that has been answered.
