### ISSUE TITLE
Support proto options

### ISSUE THREAD

**Issue by pffan91** [apple/swift-protobuf#815]
**Environment:**
macOS
Swift 4.2
libprotoc 3.6.1 (installed via Homebrew)

**Problem**
I have an option inside message:

```
message GetBatteryLevelResponse {
    option (com.blerpc.message) = {
        size_bytes: 1
    };
    // Current device battery level percent.
    int32 battery_level_percent = 1 [(com.blerpc.field) = {
        from_byte: 0
        to_byte: 1
    }];
}

```

But `protoc --swift_out=.` generates it as:

```
struct GetBatteryLevelResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Current device battery level percent.
  var batteryLevelPercent: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}
```

Is there any way to get options inside message? + Where is fields `from_byte` and `to_byte` from extension `com.blerpc.field` ?

**Comment by thomasvl** [comment]
Options aren't per instance data, they are captured in the descriptors, and Swift Protobuf currently doesn't not capture/expose the descriptors because they can be a non trivial amount of data that leads extra binary size that a large number of apps don't need.

Duplicate #761
