### ISSUE TITLE
File generation strips directories (unlike other languages)

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#83]
When using large numbers of protos, it isn't uncommon to end up with a directory structure of them like:

```
dir1/
  foo.proto
  settings.proto
dir2/
  bar.proto
  settings.proto
```

The current generator strips all the passed directories, so generating all these at once would result in collisions.

Since the Swift Package Manager likes flat directories, the best solution is likely to add a compiler option to control the output file naming, supporting:

1. keeping the directory structure
1. flattening the structure by combining the directory names with underscores (for the package manager)
1. stripping the directory structure completely (for anyone with simple enough cases where they don't want any structure.

**Comment by tbkka** [comment]
Ignoring the package name when generating filenames was a very deliberate decision on my part.

I've many times in the past tried to use protoc with `make` or Xcode build rules and found it very frustrating.   Having the generator build a single output file in the current directory from a single input file makes it easy to do simple things with common build systems.   (This is also why the plugin does not mangle filenames like the Obj-C generator does or build multiple output files for a single input like the Java generator does.)

Tools like Bazel with specialized knowledge of proto semantics may be necessary for complex cases, but are overkill for common cases where people have just one or two protos in a project.

I would not be opposed to having alternate mechanisms that can generate more structured output, but I'm reluctant to make simple cases complicated by default.

**Comment by tbkka** [comment]
Re-reading, I now realize that the proposal was to use the input _directory name_ when generating the output, not the input _package name_.  The directory name is visible to build tools, so I could agree to that.
