### ISSUE TITLE
Generate (optional) CoreData NSManagedObjects from proto files

### ISSUE THREAD

**Issue by Jasperav** [apple/swift-protobuf#832]
I am duplicating a lot of data by manually copying the messages in the .proto files to NSManagedObjects since I want to cache data that is inside of the .proto files. This requires also a mapping.

It would be great that if the compiler (conditionally) would create the NSManagedObjects from the .proto files (along with a mapping function).

**Comment by tbkka** [comment]
This is outside the scope of SwiftProtobuf.

However, if you want to build this yourself, we created the `SwiftProtobufPluginLibrary` specifically to make it easy for folks to write new protoc plugins.  You can look at `protoc-gen-swift/main.swift` to see how a protoc plugin works.

Alternatively, have you considered just storing the serialized protobuf data as a binary blob in your CoreData database?  That would avoid the need to copy the data in this way.
