### ISSUE TITLE
Enum cases as siblings

### ISSUE THREAD

**Issue by mpdifran** [apple/swift-protobuf#838]
macOS 10.14.3
Xcode 10.1
Build version 10B61
Swift 4.2
libprotoc 3.6.1
apple/swift-protobuf 1.3.1

Hi, I'm just wondering why enum values are using  C++ scoping rules (cases are treated as siblings instead of children) when the generated Swift treats them as children. As an example, take a look at the below photo file.

```
syntax = "proto3";

message Test {
    enum Enum1 {
        FIRST = 0;
        SECOND = 1;
    }
    enum Enum2 {
        FIRST = 0;
        SECOND = 1;
    }
}
```

When generating the Swift files, I get the following error.

```
test/test.proto:9:9: "FIRST" is already defined in "Test".
test/test.proto:9:9: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "FIRST" must be unique within "Test", not just within "Enum2".
test/test.proto:10:9: "SECOND" is already defined in "Test".
test/test.proto:10:9: Note that enum values use C++ scoping rules, meaning that enum values are siblings of their type, not children of it.  Therefore, "SECOND" must be unique within "Test", not just within "Enum2".
```

But, If I remove `Enum2` (or rename the cases), the generated enum looks like this.

```
enum Enum1: SwiftProtobuf.Enum {
  typealias RawValue = Int
  case first // = 0
  case second // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .first
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .first
    case 1: self = .second
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .first: return 0
    case .second: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

}
```

Is this naming convention a requirement of the compiler, as opposed to a Swift requirement?

What is the recommended workaround for an established code base (.proto files) with many enums named incompatibly with the C++ naming convention? (a few options would be good here; trying to maintain backwards compatibility)

**Comment by thomasvl** [comment]
This is coming from protoc, it isn't from the Swift generator.

I'm not sure if protoc has a way to suppress this, but the warning is still sorta valid in that if you end up generating for other languages, it could cause problems.

Normally to avoid this, people use names like:

```
message Test {
    enum Enum1 {
        ENUM1_FIRST = 0;
        ENUM1_SECOND = 1;
    }
    enum Enum2 {
        ENUM2_FIRST = 0;
        ENUM2_SECOND = 1;
    }
}
```

The _good_ news, is the Swift generator will strip the enum prefix from the names, so you'll actually get the _swifty_ names while providing enum values that are more likely to work in all languages.

**Comment by tbkka** [comment]
> What is the recommended workaround for an established code base (.proto files) with many enums named incompatibly with the C++ naming convention?

How are you compiling them today?  This particular restriction has been part of protoc for a while now.

**Comment by mpdifran** [comment]
Our other platforms are compiling them into Java/Javascript using wire. We're just trying to generate them for a new iOS project now using `protoc`.

**Comment by tbkka** [comment]
* Please file a bug with square/wire if they're not enforcing this restriction.  No doubt other people will get bitten by this incompatibility.
* Please file a bug with protocolbuffers/protobuf to find out if they have a general protoc option to suppress this.  (Unfortunately, it's not something that a code generator plugin such as ours can change.)
* As Thomas pointed out, renaming the enum cases does not affect the protobuf binary encoding.  It can affect JSON encoding, though, and it may require you to update other code.

**Comment by mpdifran** [comment]
Thanks, will do!

**Comment by thomasvl** [comment]
Closing since this isn't an issue with SwiftProtobuf and it looks like the other followups have happened.
