### ISSUE TITLE
Revisit docs for `--static-swift-stdlib`

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#857]
The main `README.md` talks about `--static-swift-stdlib` and maybe some of the other pages.  They likely need a revisit given Swift 5 removing some of the static linkage support.

**Comment by thomasvl** [comment]
Just saw https://github.com/apple/swift-protobuf/pull/852 landed the other day, but I thought from other threads I'd read the static library trick wasn't going to generally work?

**Comment by keith** [comment]
With https://github.com/apple/swift-protobuf/pull/852 static linking still doesn't work but SwiftPM just warns and doesn't pass the flag through to swiftc
