### ISSUE TITLE
Remove the convenience initializers on generated messages

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#86]
The generated convenience initializers that take default values are a great idea in theory, because they let users quickly create a message using whatever combination of fields they wish to initialize. However, they come with a hidden but **large** performance cost.

Default function arguments in Swift are implemented by creating a small shim for each argument, which loads the default value onto the stack. When such a function is called, these shims are called for any argument not provided by the user, and then the function body is executed.

This implies two things:
1. Code is generated for each default argument, increasing the binary size
2. Calling a function with *N* arguments that have defaults incurs the execution cost of loading *all* of the arguments, even if only one is provided.

In other words, if you have a message with 100 fields, you generate 100 shims for those default arguments; but *worse*, the execution cost of initializing the message with one argument is the same as the cost of initializing it with *all 100* arguments. Even in release mode with heavy optimization, this cannot be avoided; see [this gist](https://gist.github.com/allevato/2a22bc877c5aec45fb76a53f1fe080aa#file-big_initializer-s-L834) for a snippet of the Hopper disassembly of a 100-field message where only `field89: 0x600b34` was passed in.

We can also look at the binary size effects of these initializers, using our performance harness:

 | With convenience init | Without convenience init
--- | --- | ---
Harness size, bytes (before stripping) | 415,544 | 250,352
Harness size, bytes (after stripping) | 152,992 | 144,536
Runtime .dylib size (release) | 3,044,060 | 3,012,252

Since the runtime .dylib size includes the well-known types, there's an effect there as well. The difference in harness size is very stark before stripping (a 165KB savings by removing *one initializer*!), but in that case, stripping eliminated much of the overhead.

## Proposed alternative

Being able to create a message with values at initialization time has its benefits; maybe you want to create one inline when you call another function to avoid a temporary variable, or you want to keep your variables immutable whenever possible and having to set properties after initialization time prevents that.

This is a topic that's been debated frequently on swift-evolution, because this isn't a protobuf-specific problem; indeed, all value types are affected. A very well-received alternative is to create a helper function that creates the value and takes a closure where initialization is performed. Unlike Swift value types in general, all of our protos conform to a common protocol, so we can provide such a helper easily across the board:

```swift
extension ProtobufMessage {
  public static func with(initializer: (inout Self) -> ()) -> Self {
    var message = Self()
    initializer(&message)
    return message
  }
}
```

Then, at the usage site, you can do:

```swift
let foo = My_Generated_Message.with {
  $0.bar = 5
  $0.baz = "quux"
}

// Or one-liners, if you prefer:
let foo = My_Generated_Message.with { $0.florp = "blorp" }
```

Granted, it's not quite as beautiful as argument list syntax, but this version incurs an execution cost relative *only* to the number of properties explicitly being set.

**Comment by tbkka** [comment]
Thanks for the detailed write-up.  To be clear, you're talking about a 1% size change in the Runtime .dylib size and a 5% difference in the (post-stripping) harness size.

I _think_ I agree with you, but I'd like to sleep on it first.

**Comment by allevato** [comment]
A more realistic test would be to add multiple messages and see how much it changes based on message count. @thomasvl and I have been chatting about adding a case to the perf harness that generates something akin to `TestAllTypes`, to test "more realistic" scenarios, along with multiple message support.

I'd still argue that bigger savings w.r.t. non-stripped builds is worth it, especially with stark differences as these, as it decreases the pain for local development/testing builds.

**Comment by allevato** [comment]
Upon further reflection, I realize that my conclusion about execution cost was a little too dire. I was focusing on the fact that the parameterized initializer assigns a value to each field, but forgetting that the default initializer does that as well, just implicitly; and even for zeros/nils, an explicit move instruction is still generated (especially for `.none`-valued optionals, because those are actually stored with a non-zero bit-pattern because of the way two-case enums with one payload are represented). So maybe that part isn't as critical now.

I still worry about the binary size changes with many messages and potential effects on compile time, though. We sometimes deal in messages that have hundreds of fields, so that's still a cause for concern.

**Comment by allevato** [comment]
(Apologies for the multi-post, I'm thinking very asynchronously tonight.)

Another design concern that just occurred to me: as the number of fields increases, a large initializer with default values has diminishing returns, because the arguments must be passed *in the order that they are listed.* So for a complex message, you have to be aware of that ordering. The `with` pattern, being more like a builder, doesn't suffer from this.

I definitely wish there was a clearer winner here that balanced all of these concerns.

**Comment by thomasvl** [comment]
Random late night thoughts –

While some what arbitrary, does it make any sense to only provide some of the fields to init?  Say basic types (numerics, strings, bytes (could even leave those off)) and messages; but not provides it for repeated fields and maps?

I was going to ask about taking your comment about number of args and order making large numbers not as useful, and suggest we only do it if there are say 6 or less fields; but that means if a proto gets a new field in the future, it could suddenly break code because it would stop getting an init.

**Comment by thomasvl** [comment]
Actually, I think you stumbled on another reason to remove these…

You mentioned the order is important.  Within a `.proto` file itself, order does not matter.  As a message definition evolves with a service/app/etc., developers are free to add fields anywhere, grouping things as they see fit. All that matters is the field never change, new ones are just added; not the order within the file.  No matter what order we pick (file order or field number order), when the message definition evolves, a new generation of source files could break developers code because the order to init could change.

So it may be safer to provide `with(initializer:)` and/or encourage developers to write their own extensions to add initializers their code needs rather than trying to provide them and have them be fragile in the fact of message evolution.

**Comment by jcanizales** [comment]
For what it's worth, the client libraries we're generating on top of gRPC, for other languages, can already be configured so users making an RPC don't have to explicitly create the request proto. For that, overloaded functions (for the specific service method) are generated with some of the fields as parameters. Field selection is tricky, due to the evolution problems you mentioned. Our solution is feeding a config file to our generator, which IMO would be too much trouble to do here.

**Comment by tbkka** [comment]
Swift extensions make it easy for people to add their own convenience initializers if they want, so I'm happy switching to the `.with {...}` syntax now.

**Comment by manan19** [comment]
> Actually, I think you stumbled on another reason to remove these…
> 
> You mentioned the order is important. Within a `.proto` file itself, order does not matter. As a message definition evolves with a service/app/etc., developers are free to add fields anywhere, grouping things as they see fit. All that matters is the field never change, new ones are just added; not the order within the file. No matter what order we pick (file order or field number order), when the message definition evolves, a new generation of source files could break developers code because the order to init could change.
> 
> So it may be safer to provide `with(initializer:)` and/or encourage developers to write their own extensions to add initializers their code needs rather than trying to provide them and have them be fragile in the fact of message evolution.

Does ordering matter if all the all the initializer parameters have defaults and they are sorted?

**Comment by lolgear** [comment]
You could provide memberwise initializers in extension. ( Minimum _one_ initializer improves situation ).

```swift
struct MyStruct {
  var first: String = .init()
  var second: String = .init()
  var unknownFields = SwiftProtobuf.UnknownFields() // not included, set if you want
  init() {}
}

extension MyStruct {
  init(first: String, second: String) { 
     self.first = first
     self.second = second 
  }
}
```

**Comment by lolgear** [comment]
Look at
https://github.com/lolgear/SwiftRewriter/tree/memberwise_convenient_initializer

I've added memberwise generators as shown above.

Usage:

```bash
# Simple rewrite in a source file.
 swift build
 swift run swift-rewriter run --path ./path_to_protobuf/commands.pb.swift
```

```bash
# Output to different source file.
 swift run swift-rewriter run --path ./path_to_protobuf/commands.pb.swift --idempotent --outputPath ./path_to_protobuf/commands+initializers.pb.swift
```
