### ISSUE TITLE
AnyMessageStorage internal access level

### ISSUE THREAD

**Issue by ialimz** [apple/swift-protobuf#864]
I'm using generated swift files in Xcode in order to implement SwiftProtobuf in our project.

There is something that prevents project to compile.
In a generated file, **Google/Protobuf/any.pb.swift** there is a piece of code that is aliasing **AnyMessageStorage**:

`typealias _StorageClass = AnyMessageStorage`

At this line of code I get `Use of undeclared type 'AnyMessageStorage'` error which I think happens because of `AnyMessageStorage` internal access level.

**Comment by thomasvl** [comment]
It sounds like you didn't put all the sources for the library into the same target with a module name of SwiftProtobuf.  If you are manually adding the sources to your project, you must recreate the same structure as the library itself uses so the sources/modules/etc. match.

**Comment by tbkka** [comment]
Are you generating `any.pb.swift` as part of your build?  That is already included in the SwiftProtobuf library, so you don't need to generate it yourself.
