### ISSUE TITLE
Package name in messages declarations

### ISSUE THREAD

**Issue by isaac-weisberg** [apple/swift-protobuf#875]
My .proto file declares a few messages and a `package` statement at the top. Generating the code using `protoc-gen-swift` plugin yields an interesting results of messages named with underscore-separated mention of the package name e.g. `Com_Assburgers_SomeMessage`.

How could I possibly get rid of the package's name substring and make it generate only SomeMessage declaration?

iOS 11+
Xcode 10.2.1
Build version 10E1001
Swift 4.2
protoc-gen-swift 1.3.1

**Comment by thomasvl** [comment]
Warning - removing the package means you are more likely to have conflicts with other .proto files because your names might not be unique.

To control it, use the `swift_prefix` option - https://github.com/apple/swift-protobuf/blob/master/Documentation/API.md#generated-struct-name

**Comment by isaac-weisberg** [comment]
@thomasvl so could I theoretically set it to an empty string - and thus have the-- name without package?

**Comment by isaac-weisberg** [comment]
lol I did try exactly that and it worked!

```
option swift_prefix = "";
```

Thank you @thomasvl
