### ISSUE TITLE
Homebrew update to 1.5.0

### ISSUE THREAD

**Issue by rayanmestiri** [apple/swift-protobuf#876]
**Config:**
OS: macOS 
`xcodebuild -version`:
Xcode 10.2.1
Build version 10E1001

I am trying to bump the version on homebrew to 1.5 via [the procedure](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) with  but I'm getting installations errors when building from source via the brew command.

> ==> swift build --disable-sandbox -c release -Xswiftc -static-stdlib
> Last 15 lines from /Users/rayan.mestiri/Library/Logs/Homebrew/swift-protobuf/01.swift:
>       _$s13SwiftProtobuf21BinaryEncodingVisitorV13visitMapField9fieldType5value0I6NumberyAA01_b7MessageG0Vyxq_Gm_SDy04BaseJ0Qzq_GSitKAA0g3KeyJ0RzSHR_AA0M0R_r0_lF in BinaryEncodingVisitor.swift.o
>       _$s13SwiftProtobuf19JSONEncodingVisitorV13visitMapField9fieldType5value0H6NumberyAA01_bF0Vyxq_Gm_SDy04BaseI0QzAKQy_GSitKAA0f3KeyI0RzAA0f5ValueI0R_r0_lF in JSONEncodingVisitor.swift.o
>       ...
>   "_swift_unknownObjectRetain", referenced from:
>       _$sSayxSicir in Visitor.swift.o
>   "_swift_willThrow", referenced from:
>       _$s11Conformance0A11_FailureSetV13SwiftProtobuf7MessageAadEP8traverse7visitoryqd__z_tKAD7VisitorRd__lFTW in main.swift.o
>       _$s11Conformance0a1_A7RequestV13decodeMessage7decoderyxz_tK13SwiftProtobuf7DecoderRzlF in main.swift.o
>       _$s11Conformance0a1_A7RequestV8traverse7visitoryxz_tK13SwiftProtobuf7VisitorRzlF in main.swift.o
>       _$s11Conformance0a1_A7RequestV13SwiftProtobuf7MessageAadEP8traverse7visitoryqd__z_tKAD7VisitorRd__lFTW in main.swift.o
>       _$s11Conformance0a1_A8ResponseV13SwiftProtobuf7MessageAadEP06decodeE07decoderyqd__z_tKAD7DecoderRd__lFTW in main.swift.o
>       _$s11Conformance0a1_A8ResponseV13SwiftProtobuf7MessageAadEP8traverse7visitoryqd__z_tKAD7VisitorRd__lFTW in main.swift.o
>       _$s11Conformance0A11_FailureSetV13SwiftProtobuf7MessageAadEP06decodeF07decoderyqd__z_tKAD7DecoderRd__lFTWTm in main.swift.o
>       ...
> ld: symbol(s) not found for architecture x86_64
> 

I got swift-protobuf 1.5.0 working fine when building directly from this repo though.
Can anyone help figure out what's causing this?

**Comment by tbkka** [comment]
Does it work without `-static-stdlib`?

**Comment by rayanmestiri** [comment]
It uses `-static-stdlib` by default. The whole command it runs is:

`swift build --disable-sandbox -c release -Xswiftc -static-stdlib`

**Comment by tbkka** [comment]
I believe the symbols mentioned in the log excerpt above -- `_swift_unknownObjectRetain` and `_swift_willThrow` -- are part of the standard library.  So it appears that there's some issue in your environment that's causing the code to fail to link the standard library correctly.

**Comment by rayanmestiri** [comment]
I removed the ` "-Xswiftc", "-static-stdlib"` part of the brew `def install` step and it worked.

**Comment by rayanmestiri** [comment]
I tried removing all traces of swift-protobuf and reinstalling it with brew fails if I keep the `"-Xswiftc", "-static-stdlib` arguments. I don't know what could be wrong with my setup.

**Comment by tbkka** [comment]
The `-static-stdlib` option is deprecated in newer Xcode, so that's not really surprising.

**Comment by rayanmestiri** [comment]
I reverted my changes and tried installing 1.3.1 from source and I have the same errors. It seems there's indeed an issue with my environment but I can't figure out what it is. I don't have the issue when installing from brew without building from source though.

**Comment by rayanmestiri** [comment]
> The `-static-stdlib` option is deprecated in newer Xcode, so that's not really surprising.

Oh that might explain it. So do you think it would be ok to remove the option for the installation procedure?

**Comment by tbkka** [comment]
I'm honestly not sure.  SwiftProtobuf tries to support the last few versions of Swift, and that option is definitely helpful for folks still using Swift 4.

**Comment by thomasvl** [comment]
Fyi - just sent https://github.com/apple/swift-protobuf/pull/877 to close out the issue about the docs maybe needing update.  Hopefully that covers it.
