### ISSUE TITLE
"protoc — swift_out=. UserModel.proto" shows error Missing output directives.

### ISSUE THREAD

**Issue by mithin-thomas** [apple/swift-protobuf#878]
Hey.
my environment:
Mac OS High Sierra, Xcode 10.1, protoc version: 3.8.0, 

command protoc — swift_out=. UserModel.proto gives an error:  Missing output directives.
Please help me with this.

**Comment by mithin-thomas** [comment]
Wrong command sorry

**Comment by mithin-thomas** [comment]
protoc --swift_out=. UserModel.proto

**Comment by tbkka** [comment]
"Missing output directives" is printed by protoc when you don't provide an output option such as `--swift_out=.`

```
$ protoc  UserModel.proto
Missing output directives.
```

Do you get that error message when you use the correct command?
