### ISSUE TITLE
"Tried to write the same file twice." / swift doesn't like dupe file names

### ISSUE THREAD

**Issue by gabek** [apple/swift-protobuf#88]
I have a filesystem organized into namespaced proto files.  The same names are often used in different namespaces, such as generic things like `api.proto`.  However the generation of the swift code doesn't doesn't take the directories into account and runs into an issue where it tries to generate multiple `api.pb.swift` files, failing with:

```
card.pb.swift: Tried to write the same file twice.
```

As a side effect, even if I were able to generate multiple files properly the Swift compile would fail because it can't handle the multiple same file names due to access control.
```
<unknown>:0: error: filename "api.pb.swift" used twice
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
```

Is there any way to get the generated code filenames to be generated to handle this?

Swift version:
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
Target: x86_64-apple-macosx10.9

protoc version:
libprotoc 3.1.0

**Comment by thomasvl** [comment]
For now, you can probably generate the files into different directories (multiple invokes of protoc/protoc-gen-swift.  But earlier we opened #83 to address this and I've started working on it.
