### ISSUE TITLE
Use of unresolved identifier 'Google_Protobuf_Any'

### ISSUE THREAD

**Issue by gogym** [apple/swift-protobuf#884]
Use of unresolved identifier 'Google_Protobuf_Any'

`Google_Protobuf_Any(message:ackReq);`

not find Google_Protobuf_Any

version:1.5.0

**Comment by tbkka** [comment]
Could you please explain how you solved this, in case other people run into the same issue?

**Comment by gogym** [comment]
import SwiftProtobuf

**Comment by tbkka** [comment]
Thank you!
