### ISSUE TITLE
SwiftProtobuff.framework missing at run time

### ISSUE THREAD

**Issue by Loris94** [apple/swift-protobuf#888]
MacOS: 10.13.6 (17G66)
xcode version: 10.1
swiftprotobuf version: 1.5.0
swift 4.2
iphone5

As the title says when I run my app on a iphone5 it crashes saying:

dyld: Library not loaded: @rpath/SwiftProtobuf.framework/SwiftProtobuf
Referenced from: /var/containers/Bundle/Application/484280D4-A568-4325-A58D-154797B314E7/MDProject.app/MDProject
Reason: image not found

I've followed all the steps suggested in the  readme:
I've created my .proto file and compiled it with the suggested protoc command and added the result .pm.swift file inside my project. I also copied the compiled swift-protobuf project folder inside my project + added SwiftProtobuf.xcodeproj in my build dependencies (Project > Build Phases > Target Dependencies) + linked binaries with library and selecting the SwiftProtobuff framework.

By doing like this xcode doesn't give any error but crashes with that error at runtime.
I'm new to xcode so I think I'm missing something simple. My guess is that it's not searching in the right path for the .framework file. Currently my runpath search path is set to “@executable_path/Frameworks” and in the xcode product folder the App Structure is this: 
![Screen Shot 2019-06-29 at 15 33 21](https://user-images.githubusercontent.com/18289596/60384881-52ad6780-9a83-11e9-886e-ba968e9178e0.png)

Edit: I forgot to mention, it works on a simulator but not on real devices

**Comment by thomasvl** [comment]
This isn't specific to this library, it's more of a general "how to use Xcode".  From what you describe, you probably are linking to the framework, but your Xcode isn't configured to bundle the framework, so it isn't being copied into the Frameworks directory of your iOS App.

**Comment by Loris94** [comment]
@thomasvl Yeah you are right, I thought it was an automatic procedure to copy the framework in the app directory. I don't know if this is basic stuff but I'll write what I did.
In project settings under build phases select the '+' sign and add a Copy File Phase. As destination pop-up select Framework and drag the SwiftProtobuf.framework file in.

**Comment by usman1579** [comment]
anyone Knows the solution for this mine is not working with 
xcode : 11.4.1
IOS : 11 
React Native : 62.2
