### ISSUE TITLE
ignoreUnknownFields default value should be true

### ISSUE THREAD

**Issue by Karo-Sahafi** [apple/swift-protobuf#901]
I think `ignoreUnknownFields` in `JSONDecodingOptions` default value should be true. when it's false, it would conflict with backward compatibility of proto.

**Comment by tbkka** [comment]
It's important here that we follow the behavior of Google's C++ implementation of protobuf.

Google's C++ behavior is defined here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/json_util.h#L63

If you feel strongly about this behavior, please file an issue with protocolbuffers/protobuf to see if they would be willing to change it in the C++ implementation.

**Comment by thomasvl** [comment]
I'll also add, I have a hard time seeing a default should be something that drops data without any indication that data was dropped; and that's what changing `ignoreUnknownFields` to default to `True` would do.  Dropping data seems like something developers should always have to opt into.

**Comment by lilhinx** [comment]
While strict behavior of developer tools can lead to good things, it's better for this strict behavior to be at compile time forcing the developer to sharpen their work. That indeed is the spirit of a type definition like protobuf in the first place. However the strict behavior that this field enforces is likely to be discovered at runtime. More over it's likely discovered at runtime by a development team with an app out of in the wild. Good API design must not only take into account the philosophy/opinion of the features, but also take into account how it's most likely to be used by the users (the developers using the tool/library.)
