### ISSUE TITLE
CaseIterable conformance is not synthesized for enums nested two levels deep

### ISSUE THREAD

**Issue by MrMage** [apple/swift-protobuf#922]
* using macOS 10.13.6, Xcode 10.1, Swift 4.2
* SwiftProtobuf 1.7.0

Running `protoc --swift_out=. test.proto` on the following file

```
syntax = "proto3";

enum ThisIsSynthesized {
    NONE = 0;
}

message Nested {
    enum ThisIsSynthesizedToo {
        NONE = 0;
    }

    message NestedNested {
        enum ThisIsNotSynthesized {
            NONE = 0;
        }
    }
}
```

produces the output at https://gist.github.com/MrMage/a4a1a80b746d8ffde6263c22dfca31ce, which is missing `CaseIterable` conformance for `ThisIsNotSynthesized`. I assume the enum collection method does not traverse nested messages.

**Comment by thomasvl** [comment]
Correct on the assumption, the nested message case wasn't fully recursive, so any depth paths two wasn't covered.

**Comment by MrMage** [comment]
Sorry for the backseat driving, but should there be a regression test for this?

**Comment by thomasvl** [comment]
We don't currently have a good setup for validating generation like this, instead we have the `Reference` directory and generally inspect things as changes are made.  No, not great, but it is about the same as what a _goldens_ test would do checking for expected output.

**Comment by MrMage** [comment]
Totally understand, but should this case (enum nested two messages deep) be part of one reference, then? :-)

**Comment by thomasvl** [comment]
It is.  See the PR, the reference files needed to be updated.

**Comment by MrMage** [comment]
Sorry, I had completely missed the PR and only looked at the commit referencing this issue.
