### ISSUE TITLE
Is there a way to enable debugging output on parse errors?

### ISSUE THREAD

**Issue by Stokestack** [apple/swift-protobuf#930]
I'm using the buffers in an iOS app, and would like to be able to troubleshoot parsing errors. Is there a mechanism to dump info about them?

Thanks!

**Comment by thomasvl** [comment]
The parsing api are all flagged with `throws` if they can fail, and thus will return a specific `Error` for what went wrong.  At the moment, the info is pretty basic, but we do have #580 and #581 open for adding more information to them.

**Comment by tbkka** [comment]
If you're using binary format and the deserialization fails, then there are a few ways you can troubleshoot.  The basic idea is to get the binary data and feed it to some other utility that can give you more information:

* You can use the `protoc` command-line tool to decode the message using your `.proto` file:  The `protoc` program has a `--decode` option that can take a binary-encoded message.  You use the same command line you would normally use to compile your `.proto` files and also pipe in the binary data.  Internally, `protoc` will use your `.proto` definition to decode the message and help point out discrepancies between the data you're trying to decode and the data definition in your `.proto` file.

* Use `protoc` to do a "raw" decode of the message.  The `protoc` program has a `--decode_raw` that can dump the structure of a binary message.  You can then compare this to your `.proto` file and see why it's not decoding.  This does not use your `.proto` file, so it's a little more cryptic.

* Within your Swift code, decode the data to a `SwiftProtobuf.Empty` object (this is pre-defined in the library).  That object has no fields, so any data will be handled as "unknown."  If that fails, your input is badly malformed in some fashion.  If that succeeds, try serializing back to TextFormat or JSON to see the contents and try to figure out what's different than you expect.

**Comment by Stokestack** [comment]
Cool, good info. Thanks guys!
