### ISSUE TITLE
[Implementation] Question regarding the implementation of swift-protobuf  

### ISSUE THREAD

**Issue by mustiikhalil** [apple/swift-protobuf#940]
Good afternoon, 
Hope are are all doing well. I want to add swift-gRPC to [Flatbuffers](https://github.com/google/flatbuffers), however swift-gRPC is heavily coupled to `swift-protobuf`. Most of the methods are using `protocol Message`, and I would love to know the following:
 -  If there is a way to get to the underlying data that is storing the actual buffer? will accessing `SwiftProtobuf.UnknownStorage()` will be enough to actually read the data + safe?

- Is there a way to bypass the following function `decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws` just to return our Buffer? or is there simply a way to just get the buffer from `Message` 

note: in flatbuffers, it would be nice to get either the `Data`, or `[UInt8]`

**Comment by thomasvl** [comment]
Unknown fields are only the fields that weren't defined in the message and thus weren't parsed into fields.  You would need to serialize it again to get the full binary.

As far as bypassing `decodeMessage`, that doesn't sound like a question for this repo, but instead for Swift-gRPC as you want the raw payload off the wire, so you want to head things off before this library is invoked.
