### ISSUE TITLE
Install 1.8.0 via Homebrew?

### ISSUE THREAD

**Issue by bmt2018** [apple/swift-protobuf#945]
I see that 1.8.0 was released a couple of days ago now.  I have the previous 1.7.0 release installed via Homebrew but can't seem to update to 1.8.0.  Is this just because the Homebrew formula hasn't been updated yet?  Thanks!

**Comment by thomasvl** [comment]
Homebrew isn't something we maintain (personally, I didn't even know it was there), so you'll have to reach out to the maintainers of that.

**Comment by bmt2018** [comment]
Thanks, Thomas!  Since it's mentioned as an installation option on the main page, I just assumed that somebody associated with the project was keeping it updated with new releases.  Thanks for the clarification!

**Comment by thomasvl** [comment]
Doh, I guess that came in via a PR.  If you find contact info, feel free to send in a PR to update our Releasing page with the contact info so we can reach out to who ever for future releases.
