### ISSUE TITLE
Possible to specify a key decoding strategy similar to JSONDecoder?

### ISSUE THREAD

**Issue by mpdifran** [apple/swift-protobuf#950]
#### Info:
macOS 10.15.3
Xcode Version 11.3.1 (11C504)
Swift 5
apple/swift-protobuf 1.8.0

#### Problem:
Our backend sends down JSON with keys encoded using snake case, but our proto files use camel case. Up until now we've been using Codable to decode the JSON, and we specified a `keyDecodingStrategy = .convertFromSnakeCase`, but now we're trying to move to use protobuf generated structs instead. Is there a similar setting for Swift Protobuf?

We do have the option of changing how our backend encodes JSON, but that's a potentially large undertaking, and since Codable supports it, I was wondering if the same was true for Swift Protobuf or if it would be easy to implement?

#### Examples:
```
/// TestObject.proto
syntax = "proto2";

message TestObject {
  optional string name = 1;
  optional string otherValue = 2;
  optional TestEnum newKey = 3;
}

enum TestEnum {
  FIRST = 1;
}
```
```
/// JSON
{
  "name":"Foo",
  "other_value":"Fhqwhgads",
  "new_key":"FIRST"
}
```

**Comment by thomasvl** [comment]
https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/JSONEncodingOptions.swift#L23 is an option to change what is generated.

But, not all JSON is the same; different systems make different choices about how to encode things (doubles, really large integers, etc.).  So If you are moving off of a something else, you'll need to make sure the [protobuf spec for JSON](https://developers.google.com/protocol-buffers/docs/proto3#json) matches what your server is already doing.

**Comment by thomasvl** [comment]
ps - you'll want snake case in your .proto file to get the keys in that form with the option.  The swift generation from the .proto file will move to camelcase in the generated code.  This is because the protobuf style guide calls for snake case, and the Swift generation tries to be more "swifty".

**Comment by mpdifran** [comment]
What you linked above looks like it might be useful for encoding, but what about decoding? I don't see an equivalent decoding option: https://github.com/apple/swift-protobuf/blob/master/Sources/SwiftProtobuf/JSONDecodingOptions.swift

**Comment by thomasvl** [comment]
The spec calls for supporting both forms, so no option is needed.

**Comment by mpdifran** [comment]
Ah gotcha, so the problem lies with our .proto files not using snake case. Thanks for the info!
