### ISSUE TITLE
Memberwise initializers for objects?

### ISSUE THREAD

**Issue by mpdifran** [apple/swift-protobuf#951]
#### Info:
macOS 10.15.3
Xcode Version 11.3.1 (11C504)
Swift 5
apple/swift-protobuf 1.8.0

#### Question
So I see `swift-protobuf` supports the following ways of initializing objects:

```
// Create a BookInfo object and populate it:
var info = BookInfo()
info.id = 1734
info.title = "Really Interesting Book"
info.author = "Jane Smith"

// As above, but generating a read-only value:
let info2 = BookInfo.with {
    $0.id = 1735
    $0.title = "Even More Interesting"
    $0.author = "Jane Q. Smith"
  }
```

Is there a reason why we don't also generate a membewise initializer (outlined [here](https://docs.swift.org/swift-book/LanguageGuide/Initialization.html) for structs)?

Would be a little less clunky than the above read-only variation, support autocomplete, etc. 

Eg:
```
let info3 = BookInfo(id: 1736, 
                     title: "The Most Interesting", 
                     author: "Jane Z. Smith")
```

**Comment by thomasvl** [comment]
See some of the recent discussions in #938.

The main issue is they can be source breaking if someone adds, reorders, etc. fields; which isn't breaking from a protobuf pov.
