### ISSUE TITLE
"Unknown flag: --swift-out" when installing with brew

### ISSUE THREAD

**Issue by Continuities** [apple/swift-protobuf#959]
As per the README, I installed swift-protobuf with `brew install swift-protobuf` and tried to run `protoc --swift-out=. MyModel.proto`.

It fails with `Unknown flag: --swift-out`

OSX 10.14.6
libprotoc 3.11.4
protoc-gen-swift 1.7.0

**Comment by tbkka** [comment]
Use an underscore, not a dash:  `--swift_out`

**Comment by Continuities** [comment]
Oh christ, I'm an idiot. Thank you. 🤦‍♂️
