### ISSUE TITLE
Confirm proto2 extension naming conventions

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#96]
We need to confirm the way proto2 extensions are generated. At first glance, the use of Swift's extensions seems nice, but it seems like it is reversing the scoping as defined by the [proto language](https://developers.google.com/protocol-buffers/docs/proto#extensions).

Specifically, a top level `extend` is scoped into the package where it is defined.  And a _nested_ `extend` is scoped to the `message` it was defined in.  Then when accessing them, the apis in the other languages make you pass some form of extension identifier to collect them.  This scoping is done because two places could extend the same message and both add `foo` (with different extension numbers).  So from an API pov, the two need unique naming so code could use both extension.

Looking at what is currently generating for Swift, it seems like the _nested_ `extend` case might be correctly naming the property added with the defining location; however the `extend` at the root of a file doesn't seem to use the proto package to scope the property added in the Swift extension.  `unittest_swift_extension.proto` and `unittest_swift_extension.pb.swift` seem to show this second issue.

Anyway, we should double check both cases to confirm this is all correct and properly scoped.

**Comment by tbkka** [comment]
Changing this would affect the developer-facing API, so I've labelled it accordingly.

**Comment by thomasvl** [comment]
So there is a problem in a few spots.  One thing noticed while looking at this:

```protobuf
message Foo {
    extensions 10 to 1000;
    message Bar {
        message Baz {
            extensions 100 to 1000;
        }
    }
}

extend Foo.Bar.Baz {
   optional string b = 100;
}

extend Foo {
   optional string b = 10;
}
```

Gets flagged as bad by protoc beause 'b' is trying to be declared at the same scope twice.  So The thing being extended doesn't need to be included in the name we generated.  The naming should come complete from the declaration instead.

**Comment by thomasvl** [comment]
Note the same sorta restrictions apply to scoped extends:

```protobuf
# File1.proto
package protobuf_unittest.extend2;
message Foo {
    extensions 10 to 1000;
    message Bar {
        message Baz {
            extensions 100 to 1000;
        }
    }
}
```

```protobuf
# File2.proto
import "File1.proto";
message MyMessage {
  extend protobuf_unittest.extend.Foo.Bar.Baz {
     optional string b = 210;
  }
  extend protobuf_unittest.extend.Foo {
     optional string b = 910;
  }
}
```

Is invalid because of the two definitions of `b` scoped to `MyMessage`.

**Comment by thomasvl** [comment]
So, given:
```protobuf
# file unittest_swift_extension.proto
package protobuf_unittest.extend;

message Foo {
    message Bar {
        message Baz {
            optional int32 a = 1;
            extensions 100 to 1000;
        }
    }
}
```
and
```protobuf
# File unittest_swift_extension2.proto
package protobuf_unittest.extend2;

import "unittest_swift_extension.proto";

message MyMessage {
  extend protobuf_unittest.extend.Foo.Bar.Baz {
     optional string b = 210;
     optional group C = 211 {
        optional int64 c = 1210;
     }
  }
}

extend protobuf_unittest.extend.Foo.Bar.Baz {
  optional string b = 220;
  optional group C = 221 {
    optional int64 c = 1220;
  }
}
```
The scoped extend should be like:
```swift
struct ProtobufUnittest_Extend2_MyMessage: ... {
  ...
  struct Extensions {
    static let b = ProtobufGenericMessageExtension<...>(...)
  ...
  }
}

extension ProtobufUnittest_Extend_Foo.Bar.Baz {
  var ProtobufUnittest_Extend2_MyMessage_b: String { ... }
  var hasProtobufUnittest_Extend2_MyMessage_b: Bool { ... }
  ...
}
```
_Note:_ The `static let b` is fine, scoping of that name is provided by the parent structs; and then the Swift extension of the message to add the extensions, names they using underscore prefixing to model the context where the `extend` was done.

And the top level extend should like be:
```swift
let ProtobufUnittest_Extend2_b = ProtobufGenericMessageExtension<...>(...)
...
extension ProtobufUnittest_Extend_Foo.Bar.Baz {
  var ProtobufUnittest_Extend2_b: String { ... }
  var hasProtobufUnittest_Extend2_b: Bool { ... }
  ...
}
```
_Note:_ The `let ProtobufUnittest_Extend2_b` is scoped since this is a top level define.  The Swift extension of the message class uses the same sorta underscore namespacing.

**Comment by thomasvl** [comment]
And here's the catch; the top level case:

1. The `let` is `ProtobufUnittest_Extend2_b`
1. The property in the message class Swift extensions is also `ProtobufUnittest_Extend2_b`; but it needs to reference the value from the `let`.

So I guess to top level extensions, we change the `let`s to be "[pacakge]_Extensions_[name]" sorta like the `struct Extensions` used when the extends are scoped to another class.
