### ISSUE TITLE
[Question] How to check OneOf enum cases with associated values?

### ISSUE THREAD

**Issue by lolgear** [apple/swift-protobuf#963]
Hi!

For example, I have a following protobuf structure:

```protobuf
message MyPage {
    oneof content {
        Content.Text text = 1;
        Content.Image image = 2;
    }
    message Content {
        message Text {}
        message Image {}
    }
}
```

and corresponding generated code:

```swift
struct MyPage {
  var content: OneOf_Content?

  var text: MyPage.OneOf_Content.Text {
    get {
      if case .text(let v)? = _storage._content {return v}
      return MyPage.OneOf_Content.Text()
    }
    set {_uniqueStorage()._content = .text(newValue)}
  }

  var image: MyPage.OneOf_Content.Image {
    get {
      if case .image(let v)? = _storage._content {return v}
      return MyPage.OneOf_Content.Image()
    }
    set {_uniqueStorage()._content = .image(newValue)}
  }

  enum OneOf_Content {
    case text(Text), image(Image)

    struct Text {}
    struct Image {}
  }
}
```

When I meet this `MyPage` object in client, what should I do? How should I check for enum value? I could only think about something like this:

```swift
let page: MyPage = ... // MyPage
let hasImage = page.content == .image(page.image)
```

Is it ok? Is there any simple and obvious way to achieve this?

**Comment by tbkka** [comment]
You can use a Swift `switch` to handle the different possibilities:
```
  if let content = page.content {
    switch content {
    case .text(let text):
         ... process `text` message ...
    case .image(let image):
         ... process `image` message ...
    }
  }
```

You can also use Swift's `if case` construct to check for just one value:
```
  if case .text(let text)? = mypage.content {
    ... process `text` message ...
  }
```

**Comment by lolgear** [comment]
@tbkka 
And why did you close it?
ifs and switches are too verbose for such a simple equality test.

**Comment by tbkka** [comment]
This is really a question about how to use Swift.  There are many discussions on the Internet about how to work with enums, just search on `swift enum associated values` to find them.

**Comment by lolgear** [comment]
@tbkka 
No, this question is about this library which generate variables that don't have optional values.

Look at definition:

```
  var text: MyPage.OneOf_Content.Text {
    get {
      if case .text(let v)? = _storage._content {return v}
      return MyPage.OneOf_Content.Text()
    }
    set {_uniqueStorage()._content = .text(newValue)}
  }
```

**Comment by thomasvl** [comment]
Those helpers let you directly access the field getting the default value without checking the `oneof` state.  If you need to explicit check the state, use the enum to which state it is in.

**Comment by tbkka** [comment]
Our API documentation has some additional explanation of why we don't use optionals in this way:  See the section `Proto2 optional vs. Swift Optional` in https://github.com/apple/swift-protobuf/blob/master/Documentation/INTERNALS.md

**Comment by lolgear** [comment]
@thomasvl 
@tbkka 
Could you consider adding `has` properties to check OneOf values? It is really annoying to write something like:

```swift
guard let value = message.value else { return false }

if case Event.Message.OneOf_Value.pageShow = value {
    return true
}
return false
```

**Comment by thomasvl** [comment]
Only caring about one case of a oneof doens't sound like a common enough thing to justify the api surface.

You can alway create a Swift extension to provide a helper within your module if you really feel it will improve your specific use case.

**Comment by lolgear** [comment]
@thomasvl 
Sure, I did it two months ago. ( I created several swift extensions to simplify our integration with protobuf models ).
On library side you could consider not to hide "real" state of OneOf value in forest of "non-optional" properties. 
Swift don't have neither good if/switch statements as expressions nor good support for simple equality tests for such a good pattern (GADT?).
