### ISSUE TITLE
Serialized String longer than 128 bytes cannot be deserialized in C++ ParseFromString

### ISSUE THREAD

**Issue by ljtale** [apple/swift-protobuf#967]
Hi
I'm using SwiftProtobuf to build a cross-platform messaging system, and on iOS the protobuf message is serialized in Swift Protobuf and sent to a C++ SDK through Objective C wrapper. This is a sample message:
```
message Event {
   string modelPath = 1;
   int num = 2;
}
```
And here is the serialization code:
```
          let data = try protoMessage.serializedData()
          let dataString =  String(encoding: data, as: UTF8.self)
```
the dataString is passed to C++ SDK via an Objective C wrapper that just takes an string as argument.
Deserialization code in C++ is:
```
protoEvent.ParseFromString(event)
```
The problem I encountered is,  if the string field of the protobuf message is longer than 128 bytes, C++ code `ParseFromString` will return false, and the deserialized string field will be empty. I've tested that if the string is shorter than 128 bytes everything just works fine. 

Can someone give some suggestions on what the problems will be? Thanks!

BTW, I'm using MacOS and build an iOS app for iPhone 7 for testing with XCode.

**Comment by thomasvl** [comment]
```
          let dataString =  String(encoding: data, as: UTF8.self)
```

isn't valid.  The binary form is not UTF8 data, it is binary data.  Yes, the C++ api uses `std::string` but it isn't a string, it is just used a wrapper for a chunk of bytes.  You'll need to create the `std::string` directly from the payload of the `Data` and not let something like a UTF8 decode happen on it (which I would actually expect to fail in a lot of cases).

**Comment by ljtale** [comment]
Thanks Thomas! Do you have a recommended way to pass the serialized Swift Data binary to C++ in this case?

**Comment by thomasvl** [comment]
`Data` exposes the raw bytes and length, use that.  I assume you have something similar to move your `String` into a `std::string`.

**Comment by tbkka** [comment]
You can use a construct like this:
```
let count = data.count
data.withUnsafeBytes { ptr in
   ... Pass ptr and count to your C++ function ...
}
```
