### ISSUE TITLE
Equality is inconsistent with other languages

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#97]
For proto2 messages, the current Swift implementation considers an unset field to be equal to one explicitly set to its default value. This is not equality, but [equivalence (see C++)](https://github.com/google/protobuf/blob/fd046f6263fb17383cafdbb25c361e3451c31105/src/google/protobuf/util/message_differencer.h#L120-L123). Equality distinguishes between an unset field and one explicitly set to its default value.

This should be a quick fix; it simplifies the generator slightly since we don't need to worry about what the default value is, and the tests will need to be modified where they exercise the current behavior.

**Comment by thomasvl** [comment]
Since hash is done via Sources/SwiftProtobuf/HashVisitor.swift the fact that isEqual is special casing default values likely means we're breaking the contract between isEqual and hash - in that the defaults could make isEqual end up true while the hash values are actually different.

**Comment by tbkka** [comment]
We could augment the `test{Format}{Encode|Decode}` macros so that whenever they assert equality, they also assert hash equality.  That would give us some coverage of the hash contract for free on top of our existing tests.  Of course, tailored hash tests would also be a nice addition.

**Comment by thomasvl** [comment]
I still need to do more complete tests for these, but I'm going to go ahead and close this since we believe the methods themselves are fixed.
