### ISSUE TITLE
Benchmarks to understand performance differences of SwiftProtobuf over JSONDecoder?

### ISSUE THREAD

**Issue by gsabran** [apple/swift-protobuf#970]
I have been testing a few things to measure how different decoding solutions compare. I was surprised to see `SwiftProtobuf` be slower than built in JSON based alternatives and I hope to be wrong. I was curious to know
- what existing benchmarks can we look at for `SwiftProtobuf` vs `JSONDecoder` or Dictionary iteration that would invalidate my findings (🤞)
- if you're curious to have a look at [my small benchmark](https://github.com/gsabran/DecodingExperimentation), what could have gone wrong?

I tested the performance of:
- Dictionary iteration from json payload
- `JSONDecoder` decoding of json payload
- [`DictionaryDecoder`](https://github.com/elegantchaos/DictionaryCoding/blob/master/DictionaryCoding.podspec) decoding of json payload
- `SwiftProtobuf` decoding of the corresponding binary payload.

<img width="430" alt="screenshot" src="https://user-images.githubusercontent.com/4228246/77368734-1d842c00-6d1a-11ea-9358-3560c97ff696.png">

**Comment by gsabran** [comment]
Well switching to release build made a tremendous difference! **Proto is at -90%** 🎉🎉🎉

**Comment by tbkka** [comment]
Building Release vs. Debug makes a huge difference in Swift performance.  I'm glad that addressed your concerns.  You might also experiment with SwiftProtobuf's JSON encoding, although be aware that we implement protobuf JSON conventions which have a few quirks.
