### ISSUE TITLE
Performance XCode 11.1 vs XCode 10.1

### ISSUE THREAD

**Issue by mrengine** [apple/swift-protobuf#971]
Hello, 

Could u plz explain why my *.pb.swift has other performance / reading result for other XCode?
The thing is that my project was developed by XCode 10.1 and reading of pb.swift (db has about 53k objects) takes about 1-2 sec max. Now I rebuilt the project under XCode 11.1 and now reading takes me about 5-7 sec.

**Comment by mrengine** [comment]
Found the problem. Something wrong with Pods. If the dependencies were built using Carthage, all is ok, but if using Pods - there is delay.

**Comment by thomasvl** [comment]
Sounds like you might build building in Debug and not Release?
