### ISSUE TITLE
Fix required property serialization

### ISSUE THREAD

**Issue by allevato** [apple/swift-protobuf#98]
For proto2, we need to support two kinds of serialization/parsing:
- **Partial:** Required fields are not "required." When writing a message, if a required field is unset, it is simply not written out. After reading a message, if a required field is not present, the partial message is returned.
- **Full:** Required fields are required. When writing a message, if a required field is unset, an error is thrown. After reading a message, if a required field is not present, an error is thrown.

The typical pattern is to implement full in terms of partial. Implement an `isInitialized` method/property. For full writing, call it to validate before calling the partial write method ([C++ example](https://github.com/google/protobuf/blob/master/src/google/protobuf/message_lite.cc#L236-L237)). For reading, do the partial read and then call it to validate ([C++ example](https://github.com/google/protobuf/blob/master/src/google/protobuf/message_lite.cc#L117-L118)).

proto3 doesn't need to distinguish between partial and full, AFAIK, but we may want keep both to avoid surfacing different APIs (since much of this can be implemented in protocol extensions). For proto3, `isInitialized` could vacuously return true.

**Comment by thomasvl** [comment]
The Java and C++ have some pretty good smarts in the generators to make the code as minimal as possible.  We might even be able to just make the default return `true` and only hook when checks are actually needed.

The serialization apis can also be done in terms of a generated partial api, so the basic impl checks valid before/after calling the partial api.

**Comment by tbkka** [comment]
This could affect the API between the generated code and the library, so I've labelled it accordingly.  I'd like to resolve all remaining such issues fairly soon.

**Comment by thomasvl** [comment]
The C++ generator code for an optimized `isInitialized` - [MessageGenerator::
GenerateIsInitialized](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_message.cc#L3800). The flow in there is pretty simple/logical.  The one nice piece is the recursive check to see if message used for a field also has any required fields, to decided if a call to its `isInitialized` is needed or if it can be optimized out of the generate. The recursive check for required fields is: [HasRequiredFields](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_message.cc#L113-L152).

**Comment by thomasvl** [comment]
Once the `isInitialized` PR (#250) is in, we can move to support within the serialization apis. Glancing at Message.swift, it also shows we don't have a `merge` api like the other languages; so we likely want to add those and make the init methods call the merge methods.  As far as naming, my thought would be _Partial_ should go in the names that don't call `isInitialized` and the others should call the _Partial_ method and then call `isInitialized`, but we likely want #12 done first since that will resolve some of the naming.

**Comment by thomasvl** [comment]
Now that the renaming is done, I'll look at adding the initialization checks into the binary serialization apis.

**Comment by tbkka** [comment]
FYI: I'm about to put up a big PR with a performance overhaul of the encoding side.  (To match the work I did last week on the decoding side.)

**Comment by thomasvl** [comment]
PR #290 added the partial decode support.
PR #303 will add partial encoding support.

I'm rethinking adding any _merge_ support at the moment, and thinking we'll hold off adding it until we have developers needing it.

**Comment by thomasvl** [comment]
PRs in, this should be complete.

PR #307 adds a merge method and it ended up being useful to clean up some tests.
