### ISSUE TITLE
Mismatched versions

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#989]
Swift CI caught a version inconsistency when building SwiftProtobuf:

12:39:50 Error: Version in SwiftProtobuf.xcodeproj/project.pbxproj did not match SwiftProtobuf.podspec

https://ci.swift.org/job/swift-protobuf-linux-ubuntu-16_04/1876/console

**Comment by thomasvl** [comment]
This is just weird, the script hasn't changed, the files didn't really change.

**Comment by thomasvl** [comment]
And I need more coffee, it is the Xcode project that is failing.

**Comment by thomasvl** [comment]
Fixed via #990
