### ISSUE TITLE
`try BookInfo(serializedData: binaryData)` in quickstart style decoding does not fail for type mismatch

### ISSUE THREAD

**Issue by benguild** [apple/swift-protobuf#992]
Hi, I noticed that if you call `try ...(serializedData: ...)` to decode, it doesn't fail if it's a different proto type. I can reproduce this in a project, and instead had to actually start validating the fields to know whether or not the type matches. (whether it's `A` or `B`, etc.)

Does this work as intended for this library? It seems peculiar, as one of the reasons we're using protobufs and not simply decoding JSON into structs is to know in advance what the type of the messages are.

This is on Xcode 11.4.X with proto3.

**Comment by thomasvl** [comment]
The binary format does not include any type info for the message, so there is no way to detect this, the data will end up in fields where the encoding matches otherwise it ends up in the unknown fields.

This behavior is true of all protobuf implementations.
