### ISSUE TITLE
Conformance failure: proto2 + JSON + extension

### ISSUE THREAD

**Issue by tbkka** [apple/swift-protobuf#993]
This popped up on a CI bot:

CONFORMANCE TEST BEGIN ====================================
 
ERROR, test=Recommended.Proto2.JsonInput.FieldNameExtension.Validator: Expected JSON payload but got type 1. request=json_payload: "{\n        \"[protobuf_test_messages.proto2.extension_int32]\": 1\n      }" requested_output_format: JSON message_type: "protobuf_test_messages.proto2.TestAllTypesProto2" test_category: JSON_TEST, response=parse_error: "JSON failed to parse: unknownField(\"[protobuf_test_messages.proto2.extension_int32]\")"

**Comment by thomasvl** [comment]
I sent some email looking for more info on proto2 extension support in JSON.

**Comment by tbkka** [comment]
Let me know what you find.  I just pushed up a draft PR #1002 which is based on the design for TextFormat and the contents of the new conformance test.  It still needs a little work before I'm happy merging it, but it's enough to at least pass that test.

**Comment by thomasvl** [comment]
So far what I've been able to piece together:

Python has some support and tests that include extensions:
- https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/json_format.py
- https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/json_format_test.py

And Go seems to (didn't hunt down their impl, just found a reference to the test):
- https://github.com/golang/protobuf/blob/e9dc0d72c1a35f349f6d6871842199ddaaaf9edc/jsonpb/json_test.go#L317

**Comment by tbkka** [comment]
Thanks, Thomas!  Those seem to verify what I guessed from the conformance test.  Extensions are handled essentially the same as in TextFormat:  The key name is surrounded by `[]` to mark it as an extension field name, but otherwise the coding is the same as regular JSON.

I think that's enough detail to finish up #1002 and get this landed.

**Comment by tbkka** [comment]
Fixed via #1002
