### ISSUE TITLE
Update github actions so upstream master builds aren't pinned

### ISSUE THREAD

**Issue by thomasvl** [apple/swift-protobuf#998]
From the comments on https://github.com/apple/swift-protobuf/pull/973, the config can be changes so things still cache, but we always track `master` for protocolbuffers/protobuf to always get the lastest protoc and conformance tests.

**Comment by toffaletti** [comment]
Addressed in https://github.com/apple/swift-protobuf/pull/1001 ?

**Comment by thomasvl** [comment]
Yup.  Fixed.
